// --------------------------------------------------------------------------------------------------------------------
// <copyright file="AppNotificationBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in AppNotification.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IAppNotificationData.h"




//package OnePoint.PROM.Model 
    


    
@interface  AppNotificationBase : DataObject<DataObject, IAppNotificationData>
{
@private NSNumber *AppNotificationID;
        
@private NSString *Title;
        
@private NSString *Body;
        
@private NSDate *LastUpdated;
        
@private NSNumber *IsRead;
        
@private NSNumber *Type;
        
}


	  

	@property(nonatomic,retain) NSNumber *AppNotificationID;

	
	@property(readwrite,strong) NSString *Title;

	
	@property(readwrite,strong) NSString *Body;

	
	@property(readwrite,strong) NSDate *LastUpdated;

	
	@property(nonatomic,retain) NSNumber *IsRead;

	
	@property(nonatomic,retain) NSNumber *Type;

	@end
         

    

    