//------------------------------------------------------------------------
// Generated on 23-01-2017 01:06:35 PM for ADMIN\User
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------
#import <Foundation/Foundation.h>
#import "GeofenceSurveyBase.h"
//package OnePoint.PROM.Model 

@interface GeofenceSurvey : GeofenceSurveyBase
	
@end


