//------------------------------------------------------------------------
// Generated on 23-01-2017 01:06:35 PM for ADMIN\User
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------
#import <Foundation/Foundation.h>
#import "GeofenceSurveyFactoryBase.h"
#import "GeofenceSurvey.h"
#import "IGeofenceSurveyData.h"
#import <OnePointFramework/IDisposable.h>
//package OnePoint.PROM.Model 

@interface GeofenceSurveyFactory : GeofenceSurveyFactoryBase<IDisposable> {
}

@end

