// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GroupsBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Groups.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IGroupsData.h"




//package OnePoint.PROM.Model 
    


    
@interface  GroupsBase : DataObject<DataObject, IGroupsData>
{
@private NSNumber *GroupID;
        
@private NSNumber *UserID;
        
@private NSString *Name;
        
@private NSString *Description;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private NSNumber *ParentGroupID;
        
@private NSNumber *Level;
        
@private NSNumber *RefID;
        
}


	  
/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *GroupID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *UserID;

	
	@property(readwrite,strong) NSString *Name;

	
	@property(readwrite,strong) NSString *Description;

	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *ParentGroupID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *Level;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *RefID;

	@end
         

    

    