// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in GroupRelationship.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IGroupRelationshipData.h"
#import "IGroupRelationshipFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds GroupRelationship objects
/// </summary>



@interface  GroupRelationshipFactoryBase : DataObjectFactory<IGroupRelationshipData,IGroupRelationshipFactoryBase>
{
}

+(NSString*)  FIELD_NAME_GROUPRELATIONSHIPID;
+(NSString*)  FIELD_NAME_GROUPID;
+(NSString*)  FIELD_NAME_IDENTFIERID;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_GROUPRELATIONSHIPID;
+(NSString*) PARAMETER_NAME_GROUPID;
+(NSString*) PARAMETER_NAME_IDENTFIERID;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyGroupRelationshipID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyGroupRelationshipID;
// Define input parameters once only so they can be reused by other methods
-(void) AddGroupRelationshipIDParameter:(DataHandler *) dataHandler valGroupRelationshipID:(NSNumber *) valGroupRelationshipID;	

-(void) AddGroupIDParameter:(DataHandler *) dataHandler valGroupID:(NSNumber *) valGroupID;	

-(void) AddIdentfierIDParameter:(DataHandler *) dataHandler valIdentfierID:(NSNumber *) valIdentfierID;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyGroupRelationshipID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyGroupRelationshipID query:(NSString *) query;

-(id<IGroupRelationshipData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IGroupRelationshipData>) FindByGroupRelationshipID:(NSNumber *) fieldValue;
-(id<IGroupRelationshipData>) FindByGroupID:(NSNumber *) fieldValue;
-(id<IGroupRelationshipData>) FindByIdentfierID:(NSNumber *) fieldValue;
-(id<IGroupRelationshipData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IGroupRelationshipData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IGroupRelationshipData>) FindObject :(NSNumber *) keyGroupRelationshipID ;
        
-(id<IGroupRelationshipData>) Find:(DataHandler *) dataHandler;
        
-(id<IGroupRelationshipData>) FindAllObjects;

-(id<IGroupRelationshipData>) FindAllObjects:(NSString *) orderByField;

-(id<IGroupRelationshipData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IGroupRelationshipData>) CreateGroupRelationship:(id<IDataReader>) reader;
		
-(id<IGroupRelationshipData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IGroupRelationshipData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end