// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Groups.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IGroupsData.h"
#import "IGroupsFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds Groups objects
/// </summary>



@interface  GroupsFactoryBase : DataObjectFactory<IGroupsData,IGroupsFactoryBase>
{
}

+(NSString*)  FIELD_NAME_GROUPID;
+(NSString*)  FIELD_NAME_USERID;
+(NSString*)  FIELD_NAME_NAME;
+(NSString*)  FIELD_NAME_DESCRIPTION;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*)  FIELD_NAME_PARENTGROUPID;
+(NSString*)  FIELD_NAME_LEVEL;
+(NSString*)  FIELD_NAME_REFID;
+(NSString*) PARAMETER_NAME_GROUPID;
+(NSString*) PARAMETER_NAME_USERID;
+(NSString*) PARAMETER_NAME_NAME;
+(NSString*) PARAMETER_NAME_DESCRIPTION;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_PARENTGROUPID;
+(NSString*) PARAMETER_NAME_LEVEL;
+(NSString*) PARAMETER_NAME_REFID;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyGroupID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyGroupID;
// Define input parameters once only so they can be reused by other methods
-(void) AddGroupIDParameter:(DataHandler *) dataHandler valGroupID:(NSNumber *) valGroupID;	

-(void) AddUserIDParameter:(DataHandler *) dataHandler valUserID:(NSNumber *) valUserID;	

-(void) AddNameParameter:(DataHandler *) dataHandler valName:(NSString *) valName;	

-(void) AddDescriptionParameter:(DataHandler *) dataHandler valDescription:(NSString *) valDescription;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(void) AddParentGroupIDParameter:(DataHandler *) dataHandler valParentGroupID:(NSNumber *) valParentGroupID;	

-(void) AddLevelParameter:(DataHandler *) dataHandler valLevel:(NSNumber *) valLevel;	

-(void) AddRefIDParameter:(DataHandler *) dataHandler valRefID:(NSNumber *) valRefID;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyGroupID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyGroupID query:(NSString *) query;

-(id<IGroupsData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IGroupsData>) FindByGroupID:(NSNumber *) fieldValue;
-(id<IGroupsData>) FindByUserID:(NSNumber *) fieldValue;
-(id<IGroupsData>) FindByName:(NSString *) fieldValue; 
-(id<IGroupsData>) FindByDescription:(NSString *) fieldValue; 
-(id<IGroupsData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IGroupsData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(id<IGroupsData>) FindByParentGroupID:(NSNumber *) fieldValue;
-(id<IGroupsData>) FindByLevel:(NSNumber *) fieldValue;
-(id<IGroupsData>) FindByRefID:(NSNumber *) fieldValue;
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IGroupsData>) FindObject :(NSNumber *) keyGroupID ;
        
-(id<IGroupsData>) Find:(DataHandler *) dataHandler;
        
-(id<IGroupsData>) FindAllObjects;

-(id<IGroupsData>) FindAllObjects:(NSString *) orderByField;

-(id<IGroupsData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IGroupsData>) CreateGroups:(id<IDataReader>) reader;
		
-(id<IGroupsData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IGroupsData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end