// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IAddress" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Address.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IAddress Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   
#import	"IAddressListData.h"

/// <summary>
/// The IAddressData Interface Data Object Base
/// </summary>
@protocol IAddressData <NSObject>
    
-(NSNumber *) AddressID;
-(void) setAddressID:(NSNumber *) value;
-(NSNumber *) AddressListID;
-(void) setAddressListID:(NSNumber *) value;
-(NSString *) AddressSpecified;
-(void) setAddressSpecified:(NSString *) value;
-(NSNumber *) Latitude;
-(void) setLatitude:(NSNumber *) value;
-(NSNumber *) Longitude;
-(void) setLongitude:(NSNumber *) value;
-(NSString *) GeoCodeSpecified;
-(void) setGeoCodeSpecified:(NSString *) value;
-(NSString *) StatusSpecified;
-(void) setStatusSpecified:(NSString *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSString *) UserDef1Specified;
-(void) setUserDef1Specified:(NSString *) value;
-(NSString *) UserDef2Specified;
-(void) setUserDef2Specified:(NSString *) value;
-(NSString *) UserDef3Specified;
-(void) setUserDef3Specified:(NSString *) value;
-(NSString *) UserDef4Specified;
-(void) setUserDef4Specified:(NSString *) value;
-(NSString *) UserDef5Specified;
-(void) setUserDef5Specified:(NSString *) value;
-(NSString *) UserDef6Specified;
-(void) setUserDef6Specified:(NSString *) value;
-(NSString *) UserDef7Specified;
-(void) setUserDef7Specified:(NSString *) value;
-(NSString *) UserDef8Specified;
-(void) setUserDef8Specified:(NSString *) value;
-(NSString *) UserDef9Specified;
-(void) setUserDef9Specified:(NSString *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;
-(id<IAddressListData>) AddressList;


@end
   

   
    

