// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IGeofenceSurvey" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in GeofenceSurvey.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IGeofenceSurvey Interface Data Object Base
/// </summary>

#import <Foundation/Foundation.h>


/// <summary>
/// The IGeofenceSurveyFactoryBase Interface Data Object Base
/// </summary>
	
@protocol IGeofenceSurveyFactoryBase <NSObject>
   
-(NSString *) SelectAllStatement;
-(NSString *)TableName;
-(NSString *)ByPkClause;
-(NSString *)InsertStatement;
-(NSString *)UpdateStatement;
-(NSString *)DeleteStatement;
-(NSString *)DeleteByPk;


-(void) AddGeofenceIDParameter:(DataHandler *) dataHandler withGeofenceID:(NSNumber*) GeofenceID;     
-(void) AddSurveyNameParameter:(DataHandler *) dataHandler withSurveyName:(NSString *) SurveyName;  
-(void) AddSurveyIDParameter:(DataHandler *) dataHandler withSurveyID:(NSNumber*) SurveyID;     
-(void) AddSurveyReferenceParameter:(DataHandler *) dataHandler withSurveyReference:(NSString *) SurveyReference;  
-(void) AddAddressParameter:(DataHandler *) dataHandler withAddress:(NSString *) Address;  
-(void) AddAddressIDParameter:(DataHandler *) dataHandler withAddressID:(NSNumber*) AddressID;     
-(void) AddLatitudeParameter:(DataHandler *) dataHandler withLatitude:(NSNumber*) Latitude;     
-(void) AddLongitudeParameter:(DataHandler *) dataHandler withLongitude:(NSNumber*) Longitude;     
-(void) AddGeoCodeParameter:(DataHandler *) dataHandler withGeoCode:(NSString *) GeoCode;  
-(void) AddCreatedDateParameter:(DataHandler *) dataHandler withCreatedDate:(NSDate *) CreatedDate; 
-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler withLastUpdatedDate:(NSDate *) LastUpdatedDate; 
-(void) AddRangeParameter:(DataHandler *) dataHandler withRange:(NSNumber*) Range;     
-(void) AddDistanceParameter:(DataHandler *) dataHandler withDistance:(NSNumber*) Distance;     
-(void) AddIsEnteredParameter:(DataHandler *) dataHandler withIsEntered:(NSNumber *) IsEntered;

-(id<IGeofenceSurveyData>) FindByGeofenceID:(NSNumber *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindBySurveyName:(NSString *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindBySurveyID:(NSNumber *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindBySurveyReference:(NSString *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByAddress:(NSString *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByAddressID:(NSNumber *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByLatitude:(NSNumber *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByLongitude:(NSNumber *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByGeoCode:(NSString *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByCreatedDate:(NSDate *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByLastUpdatedDate:(NSDate *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByRange:(NSNumber *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByDistance:(NSNumber *) fieldValue;
        
-(id<IGeofenceSurveyData>) FindByIsEntered:(NSNumber *) fieldValue;
        
-(id<IGeofenceSurveyData>) CreateGeofenceSurvey:(id<IDataReader>)reader;

@end
    

   
    

