// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IGroupRelationship" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in GroupRelationship.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IGroupRelationship Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The IGroupRelationshipData Interface Data Object Base
/// </summary>
@protocol IGroupRelationshipData <NSObject>
    
-(NSNumber *) GroupRelationshipID;
-(void) setGroupRelationshipID:(NSNumber *) value;
-(NSNumber *) GroupID;
-(void) setGroupID:(NSNumber *) value;
-(NSNumber *) IdentfierID;
-(void) setIdentfierID:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;

@end
   

   
    

