// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IGroupRelationship" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in GroupRelationship.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IGroupRelationship Interface Data Object Base
/// </summary>

#import <Foundation/Foundation.h>


/// <summary>
/// The IGroupRelationshipFactoryBase Interface Data Object Base
/// </summary>
	
@protocol IGroupRelationshipFactoryBase <NSObject>
   
-(NSString *) SelectAllStatement;
-(NSString *)TableName;
-(NSString *)ByPkClause;
-(NSString *)InsertStatement;
-(NSString *)UpdateStatement;
-(NSString *)DeleteStatement;
-(NSString *)DeleteByPk;


-(void) AddGroupRelationshipIDParameter:(DataHandler *) dataHandler withGroupRelationshipID:(NSNumber*) GroupRelationshipID;     
-(void) AddGroupIDParameter:(DataHandler *) dataHandler withGroupID:(NSNumber*) GroupID;     
-(void) AddIdentfierIDParameter:(DataHandler *) dataHandler withIdentfierID:(NSNumber*) IdentfierID;     
-(void) AddCreatedDateParameter:(DataHandler *) dataHandler withCreatedDate:(NSDate *) CreatedDate; 
-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler withLastUpdatedDate:(NSDate *) LastUpdatedDate; 
-(id<IGroupRelationshipData>) FindByGroupRelationshipID:(NSNumber *) fieldValue;
        
-(id<IGroupRelationshipData>) FindByGroupID:(NSNumber *) fieldValue;
        
-(id<IGroupRelationshipData>) FindByIdentfierID:(NSNumber *) fieldValue;
        
-(id<IGroupRelationshipData>) FindByCreatedDate:(NSDate *) fieldValue;
        
-(id<IGroupRelationshipData>) FindByLastUpdatedDate:(NSDate *) fieldValue;
        
-(id<IGroupRelationshipData>) CreateGroupRelationship:(id<IDataReader>)reader;

@end
    

   
    

