// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ILabelRelationship" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in LabelRelationship.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ILabelRelationship Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The ILabelRelationshipData Interface Data Object Base
/// </summary>
@protocol ILabelRelationshipData <NSObject>
    
-(NSNumber *) LabelRelationshipID;
-(void) setLabelRelationshipID:(NSNumber *) value;
-(NSNumber *) LabelID;
-(void) setLabelID:(NSNumber *) value;
-(NSNumber *) IdentfierID;
-(void) setIdentfierID:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;

@end
   

   
    

