// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IProject" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Project.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IProject Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The IProjectData Interface Data Object Base
/// </summary>
@protocol IProjectData <NSObject>
    
-(NSNumber *) ProjectID;
-(void) setProjectID:(NSNumber *) value;
-(NSNumber *) UserID;
-(void) setUserID:(NSNumber *) value;
-(NSString *) NameSpecified;
-(void) setNameSpecified:(NSString *) value;
-(NSString *) DescriptionSpecified;
-(void) setDescriptionSpecified:(NSString *) value;
-(NSString *) RemarksSpecified;
-(void) setRemarksSpecified:(NSString *) value;
-(NSString *) SearchTagsSpecified;
-(void) setSearchTagsSpecified:(NSString *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;

@end
   

   
    

