// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IScriptContent" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in ScriptContent.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IScriptContent Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   
#import	"IScriptData.h"

/// <summary>
/// The IScriptContentData Interface Data Object Base
/// </summary>
@protocol IScriptContentData <NSObject>
    
-(NSNumber *) ScriptContentID;
-(void) setScriptContentID:(NSNumber *) value;
-(NSNumber *) ScriptID;
-(void) setScriptID:(NSNumber *) value;
-(NSNumber *) Version;
-(void) setVersion:(NSNumber *) value;
-(NSString *) ScriptSpecified;
-(void) setScriptSpecified:(NSString *) value;
-(NSMutableData *) ByteCode;
-(void) setByteCode:(NSMutableData *) value;
-(NSNumber *) Included;
-(void) setIncluded:(NSNumber *) value;
-(BOOL) IncludedSpecified;
-(void) setIncludedSpecified:(BOOL) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;
-(NSString *) FileTypeSpecified;
-(void) setFileTypeSpecified:(NSString *) value;
-(id<IScriptData>) ScriptParent;


@end
   

   
    

