// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISurveyAddress" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SurveyAddress.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ISurveyAddress Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   
#import	"IAddressListData.h"
#import	"ISurveyData.h"

/// <summary>
/// The ISurveyAddressData Interface Data Object Base
/// </summary>
@protocol ISurveyAddressData <NSObject>
    
-(NSNumber *) SurveyAddressID;
-(void) setSurveyAddressID:(NSNumber *) value;
-(NSNumber *) SurveyID;
-(void) setSurveyID:(NSNumber *) value;
-(NSNumber *) AddressListID;
-(void) setAddressListID:(NSNumber *) value;
-(NSNumber *) Range;
-(void) setRange:(NSNumber *) value;
-(BOOL) RangeSpecified;
-(void) setRangeSpecified:(BOOL) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;
-(id<IAddressListData>) AddressList;

-(id<ISurveyData>) Survey;


@end
   

   
    

