// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISurveyPanel" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SurveyPanel.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ISurveyPanel Interface Data Object Base
/// </summary>

#import <Foundation/Foundation.h>


/// <summary>
/// The ISurveyPanelFactoryBase Interface Data Object Base
/// </summary>
	
@protocol ISurveyPanelFactoryBase <NSObject>
   
-(NSString *) SelectAllStatement;
-(NSString *)TableName;
-(NSString *)ByPkClause;
-(NSString *)InsertStatement;
-(NSString *)UpdateStatement;
-(NSString *)DeleteStatement;
-(NSString *)DeleteByPk;


-(void) AddSurveyPanelIDParameter:(DataHandler *) dataHandler withSurveyPanelID:(NSNumber*) SurveyPanelID;     
-(void) AddSurveyIDParameter:(DataHandler *) dataHandler withSurveyID:(NSNumber*) SurveyID;     
-(void) AddPanelIDParameter:(DataHandler *) dataHandler withPanelID:(NSNumber*) PanelID;     
-(void) AddExcludedParameter:(DataHandler *) dataHandler withExcluded:(NSNumber*) Excluded;     
-(void) AddExcludedNullParameter:(DataHandler *) dataHandler;
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler withIsDeleted:(NSNumber*) IsDeleted;     
-(void) AddCreatedDateParameter:(DataHandler *) dataHandler withCreatedDate:(NSDate *) CreatedDate; 
-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler withLastUpdatedDate:(NSDate *) LastUpdatedDate; 
-(id<ISurveyPanelData>) FindBySurveyPanelID:(NSNumber *) fieldValue;
        
-(id<ISurveyPanelData>) FindBySurveyID:(NSNumber *) fieldValue;
        
-(id<ISurveyPanelData>) FindByPanelID:(NSNumber *) fieldValue;
        
-(id<ISurveyPanelData>) FindByExcluded:(NSNumber *) fieldValue;
        
-(id<ISurveyPanelData>) FindByIsDeleted:(NSNumber *) fieldValue;
        
-(id<ISurveyPanelData>) FindByCreatedDate:(NSDate *) fieldValue;
        
-(id<ISurveyPanelData>) FindByLastUpdatedDate:(NSDate *) fieldValue;
        
-(id<ISurveyPanelData>) CreateSurveyPanel:(id<IDataReader>)reader;

@end
    

   
    

