// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISurveyPanel" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SurveyPanel.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ISurveyPanel Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The ISurveyPanelData Interface Data Object Base
/// </summary>
@protocol ISurveyPanelData <NSObject>
    
-(NSNumber *) SurveyPanelID;
-(void) setSurveyPanelID:(NSNumber *) value;
-(NSNumber *) SurveyID;
-(void) setSurveyID:(NSNumber *) value;
-(NSNumber *) PanelID;
-(void) setPanelID:(NSNumber *) value;
-(NSNumber *) Excluded;
-(void) setExcluded:(NSNumber *) value;
-(BOOL) ExcludedSpecified;
-(void) setExcludedSpecified:(BOOL) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;

@end
   

   
    

