// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Label.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "ILabelData.h"
#import "ILabelFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds Label objects
/// </summary>



@interface  LabelFactoryBase : DataObjectFactory<ILabelData,ILabelFactoryBase>
{
}

+(NSString*)  FIELD_NAME_LABELID;
+(NSString*)  FIELD_NAME_USERID;
+(NSString*)  FIELD_NAME_NAME;
+(NSString*)  FIELD_NAME_COLOR;
+(NSString*)  FIELD_NAME_DESCRIPTION;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*)  FIELD_NAME_REFID;
+(NSString*) PARAMETER_NAME_LABELID;
+(NSString*) PARAMETER_NAME_USERID;
+(NSString*) PARAMETER_NAME_NAME;
+(NSString*) PARAMETER_NAME_COLOR;
+(NSString*) PARAMETER_NAME_DESCRIPTION;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_REFID;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyLabelID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyLabelID;
// Define input parameters once only so they can be reused by other methods
-(void) AddLabelIDParameter:(DataHandler *) dataHandler valLabelID:(NSNumber *) valLabelID;	

-(void) AddUserIDParameter:(DataHandler *) dataHandler valUserID:(NSNumber *) valUserID;	

-(void) AddNameParameter:(DataHandler *) dataHandler valName:(NSString *) valName;	

-(void) AddColorParameter:(DataHandler *) dataHandler valColor:(NSString *) valColor;	

-(void) AddDescriptionParameter:(DataHandler *) dataHandler valDescription:(NSString *) valDescription;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(void) AddRefIDParameter:(DataHandler *) dataHandler valRefID:(NSNumber *) valRefID;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyLabelID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyLabelID query:(NSString *) query;

-(id<ILabelData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<ILabelData>) FindByLabelID:(NSNumber *) fieldValue;
-(id<ILabelData>) FindByUserID:(NSNumber *) fieldValue;
-(id<ILabelData>) FindByName:(NSString *) fieldValue; 
-(id<ILabelData>) FindByColor:(NSString *) fieldValue; 
-(id<ILabelData>) FindByDescription:(NSString *) fieldValue; 
-(id<ILabelData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<ILabelData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(id<ILabelData>) FindByRefID:(NSNumber *) fieldValue;
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<ILabelData>) FindObject :(NSNumber *) keyLabelID ;
        
-(id<ILabelData>) Find:(DataHandler *) dataHandler;
        
-(id<ILabelData>) FindAllObjects;

-(id<ILabelData>) FindAllObjects:(NSString *) orderByField;

-(id<ILabelData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<ILabelData>) CreateLabel:(id<IDataReader>) reader;
		
-(id<ILabelData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<ILabelData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end