// --------------------------------------------------------------------------------------------------------------------
// <copyright file="LabelRelationshipBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in LabelRelationship.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "ILabelRelationshipData.h"




//package OnePoint.PROM.Model 
    


    
@interface  LabelRelationshipBase : DataObject<DataObject, ILabelRelationshipData>
{
@private NSNumber *LabelRelationshipID;
        
@private NSNumber *LabelID;
        
@private NSNumber *IdentfierID;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
}


	  
/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *LabelRelationshipID;

	
	@property(nonatomic,retain) NSNumber *LabelID;

	
	@property(nonatomic,retain) NSNumber *IdentfierID;

	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	@end
         

    

    