// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Project.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IProjectData.h"
#import "IProjectFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds Project objects
/// </summary>



@interface  ProjectFactoryBase : DataObjectFactory<IProjectData,IProjectFactoryBase>
{
}

+(NSString*)  FIELD_NAME_PROJECTID;
+(NSString*)  FIELD_NAME_USERID;
+(NSString*)  FIELD_NAME_NAME;
+(NSString*)  FIELD_NAME_DESCRIPTION;
+(NSString*)  FIELD_NAME_REMARKS;
+(NSString*)  FIELD_NAME_SEARCHTAGS;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_PROJECTID;
+(NSString*) PARAMETER_NAME_USERID;
+(NSString*) PARAMETER_NAME_NAME;
+(NSString*) PARAMETER_NAME_DESCRIPTION;
+(NSString*) PARAMETER_NAME_REMARKS;
+(NSString*) PARAMETER_NAME_SEARCHTAGS;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyProjectID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyProjectID;
// Define input parameters once only so they can be reused by other methods
-(void) AddProjectIDParameter:(DataHandler *) dataHandler valProjectID:(NSNumber *) valProjectID;	

-(void) AddUserIDParameter:(DataHandler *) dataHandler valUserID:(NSNumber *) valUserID;	

-(void) AddNameParameter:(DataHandler *) dataHandler valName:(NSString *) valName;	

-(void) AddDescriptionParameter:(DataHandler *) dataHandler valDescription:(NSString *) valDescription;	

-(void) AddRemarksParameter:(DataHandler *) dataHandler valRemarks:(NSString *) valRemarks;	

-(void) AddSearchTagsParameter:(DataHandler *) dataHandler valSearchTags:(NSString *) valSearchTags;	

-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyProjectID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyProjectID query:(NSString *) query;

-(id<IProjectData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IProjectData>) FindByProjectID:(NSNumber *) fieldValue;
-(id<IProjectData>) FindByUserID:(NSNumber *) fieldValue;
-(id<IProjectData>) FindByName:(NSString *) fieldValue; 
-(id<IProjectData>) FindByDescription:(NSString *) fieldValue; 
-(id<IProjectData>) FindByRemarks:(NSString *) fieldValue; 
-(id<IProjectData>) FindBySearchTags:(NSString *) fieldValue; 
-(id<IProjectData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<IProjectData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IProjectData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IProjectData>) FindObject :(NSNumber *) keyProjectID ;
        
-(id<IProjectData>) Find:(DataHandler *) dataHandler;
        
-(id<IProjectData>) FindAllObjects;

-(id<IProjectData>) FindAllObjects:(NSString *) orderByField;

-(id<IProjectData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IProjectData>) CreateProject:(id<IDataReader>) reader;
		
-(id<IProjectData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IProjectData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end