// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ProjectSurveyBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in ProjectSurvey.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IProjectSurveyData.h"



#import "IProjectData.h";
#import "ProjectFactory.h";
#import "ISurveyData.h";
#import "SurveyFactory.h";

//package OnePoint.PROM.Model 
    
	

    
@interface  ProjectSurveyBase : DataObject<DataObject, IProjectSurveyData>
{
@private NSNumber *ProjectSurveyID;
        
@private NSNumber *ProjectID;
        
@private NSNumber *SurveyID;
        
@private NSNumber *Excluded;
        
	@private BOOL isExcludedSpecified;
@private NSNumber *IsDeleted;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private id<IProjectData> relProject; 
@private id<ISurveyData> relSurvey; 
}


	  
/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *ProjectSurveyID;

	
	@property(nonatomic,retain) NSNumber *ProjectID;

	
	@property(nonatomic,retain) NSNumber *SurveyID;

	
	@property(nonatomic,retain) NSNumber *Excluded;

		///<summary>Determines whether Excluded currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isExcludedSpecified;
	
	@property(nonatomic,retain) NSNumber *IsDeleted;

	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	@property(readwrite,strong) id<IProjectData> RelProject; 
@property(readwrite,strong) id<ISurveyData> RelSurvey; 
@end
         

    

    