// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in ProjectSurvey.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IProjectSurveyData.h"
#import "IProjectSurveyFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds ProjectSurvey objects
/// </summary>



@interface  ProjectSurveyFactoryBase : DataObjectFactory<IProjectSurveyData,IProjectSurveyFactoryBase>
{
}

+(NSString*)  FIELD_NAME_PROJECTSURVEYID;
+(NSString*)  FIELD_NAME_PROJECTID;
+(NSString*)  FIELD_NAME_SURVEYID;
+(NSString*)  FIELD_NAME_EXCLUDED;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_PROJECTSURVEYID;
+(NSString*) PARAMETER_NAME_PROJECTID;
+(NSString*) PARAMETER_NAME_SURVEYID;
+(NSString*) PARAMETER_NAME_EXCLUDED;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyProjectSurveyID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyProjectSurveyID;
// Define input parameters once only so they can be reused by other methods
-(void) AddProjectSurveyIDParameter:(DataHandler *) dataHandler valProjectSurveyID:(NSNumber *) valProjectSurveyID;	

-(void) AddProjectIDParameter:(DataHandler *) dataHandler valProjectID:(NSNumber *) valProjectID;	

-(void) AddSurveyIDParameter:(DataHandler *) dataHandler valSurveyID:(NSNumber *) valSurveyID;	

-(void) AddExcludedParameter:(DataHandler *) dataHandler valExcluded:(NSNumber *) valExcluded;	

-(void) AddExcludedNullParameter:(DataHandler *) dataHandler; 
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyProjectSurveyID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyProjectSurveyID query:(NSString *) query;

-(id<IProjectSurveyData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IProjectSurveyData>) FindByProjectSurveyID:(NSNumber *) fieldValue;
-(id<IProjectSurveyData>) FindByProjectID:(NSNumber *) fieldValue;
-(id<IProjectSurveyData>) FindBySurveyID:(NSNumber *) fieldValue;
-(id<IProjectSurveyData>) FindByExcluded:(NSNumber *) fieldValue;
-(id<IProjectSurveyData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<IProjectSurveyData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IProjectSurveyData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IProjectSurveyData>) FindObject :(NSNumber *) keyProjectSurveyID ;
        
-(id<IProjectSurveyData>) Find:(DataHandler *) dataHandler;
        
-(id<IProjectSurveyData>) FindAllObjects;

-(id<IProjectSurveyData>) FindAllObjects:(NSString *) orderByField;

-(id<IProjectSurveyData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IProjectSurveyData>) CreateProjectSurvey:(id<IDataReader>) reader;
		
-(id<IProjectSurveyData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IProjectSurveyData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end