// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ScriptContentBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in ScriptContent.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IScriptContentData.h"



#import "IScriptData.h";
#import "ScriptFactory.h";

//package OnePoint.PROM.Model 
    
	

    
@interface  ScriptContentBase : DataObject<DataObject, IScriptContentData>
{
@private NSNumber *ScriptContentID;
        
@private NSNumber *ScriptID;
        
@private NSNumber *Version;
        
@private NSString *script;
        
@private NSMutableData *ByteCode;
        
@private NSNumber *Included;
        
	@private BOOL isIncludedSpecified;
@private NSNumber *IsDeleted;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private NSString *FileType;
        
@private id<IScriptData> relScriptParent; 
}


	  
/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *ScriptContentID;

	
	@property(nonatomic,retain) NSNumber *ScriptID;

	/// <summary>
/// Gets or sets the always latest one should be picked up
/// </summary>

	@property(nonatomic,retain) NSNumber *Version;

	
	@property(readwrite,strong) NSString *script;

	
	@property(readwrite,strong) NSMutableData *ByteCode;

	/// <summary>
/// Gets or sets the Based on this flag,version of script will included else default will be picked up based on latest version
/// </summary>

	@property(nonatomic,retain) NSNumber *Included;

		///<summary>Determines whether Included currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isIncludedSpecified;
	
	@property(nonatomic,retain) NSNumber *IsDeleted;

	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	
	@property(readwrite,strong) NSString *FileType;

	@property(readwrite,strong) id<IScriptData> RelScriptParent; 
@end
         

    

    