//------------------------------------------------------------------------
// Generated on 10/12/2014 09:24:02 for Sachin\Sachin
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------
#import <Foundation/Foundation.h>
#import "ScriptContentBase.h"
//package OnePoint.PROM.Model 

@interface ScriptContent : ScriptContentBase
	
@end


