// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Script.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IScriptData.h"
#import "IScriptFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds Script objects
/// </summary>



@interface  ScriptFactoryBase : DataObjectFactory<IScriptData,IScriptFactoryBase>
{
}

+(NSString*)  FIELD_NAME_SCRIPTID;
+(NSString*)  FIELD_NAME_USERID;
+(NSString*)  FIELD_NAME_NAME;
+(NSString*)  FIELD_NAME_DESCRIPTION;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_SCRIPTID;
+(NSString*) PARAMETER_NAME_USERID;
+(NSString*) PARAMETER_NAME_NAME;
+(NSString*) PARAMETER_NAME_DESCRIPTION;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyScriptID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyScriptID;
// Define input parameters once only so they can be reused by other methods
-(void) AddScriptIDParameter:(DataHandler *) dataHandler valScriptID:(NSNumber *) valScriptID;	

-(void) AddUserIDParameter:(DataHandler *) dataHandler valUserID:(NSNumber *) valUserID;	

-(void) AddNameParameter:(DataHandler *) dataHandler valName:(NSString *) valName;	

-(void) AddDescriptionParameter:(DataHandler *) dataHandler valDescription:(NSString *) valDescription;	

-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyScriptID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyScriptID query:(NSString *) query;

-(id<IScriptData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IScriptData>) FindByScriptID:(NSNumber *) fieldValue;
-(id<IScriptData>) FindByUserID:(NSNumber *) fieldValue;
-(id<IScriptData>) FindByName:(NSString *) fieldValue; 
-(id<IScriptData>) FindByDescription:(NSString *) fieldValue; 
-(id<IScriptData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<IScriptData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IScriptData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IScriptData>) FindObject :(NSNumber *) keyScriptID ;
        
-(id<IScriptData>) Find:(DataHandler *) dataHandler;
        
-(id<IScriptData>) FindAllObjects;

-(id<IScriptData>) FindAllObjects:(NSString *) orderByField;

-(id<IScriptData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IScriptData>) CreateScript:(id<IDataReader>) reader;
		
-(id<IScriptData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IScriptData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end