// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in ScriptContent.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IScriptContentData.h"
#import "IScriptContentFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds ScriptContent objects
/// </summary>



@interface  ScriptContentFactoryBase : DataObjectFactory<IScriptContentData,IScriptContentFactoryBase>
{
}

+(NSString*)  FIELD_NAME_SCRIPTCONTENTID;
+(NSString*)  FIELD_NAME_SCRIPTID;
+(NSString*)  FIELD_NAME_VERSION;
+(NSString*)  FIELD_NAME_SCRIPT;
+(NSString*)  FIELD_NAME_BYTECODE;
+(NSString*)  FIELD_NAME_INCLUDED;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*)  FIELD_NAME_FILETYPE;
+(NSString*) PARAMETER_NAME_SCRIPTCONTENTID;
+(NSString*) PARAMETER_NAME_SCRIPTID;
+(NSString*) PARAMETER_NAME_VERSION;
+(NSString*) PARAMETER_NAME_SCRIPT;
+(NSString*) PARAMETER_NAME_BYTECODE;
+(NSString*) PARAMETER_NAME_INCLUDED;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_FILETYPE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyScriptContentID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyScriptContentID;
// Define input parameters once only so they can be reused by other methods
-(void) AddScriptContentIDParameter:(DataHandler *) dataHandler valScriptContentID:(NSNumber *) valScriptContentID;	

-(void) AddScriptIDParameter:(DataHandler *) dataHandler valScriptID:(NSNumber *) valScriptID;	

-(void) AddVersionParameter:(DataHandler *) dataHandler valVersion:(NSNumber *) valVersion;	

-(void) AddScriptParameter:(DataHandler *) dataHandler valScript:(NSString *) valScript;	

-(void) AddByteCodeParameter:(DataHandler *) dataHandler valByteCode: (NSMutableData *) valByteCode;	

-(void) AddIncludedParameter:(DataHandler *) dataHandler valIncluded:(NSNumber *) valIncluded;	

-(void) AddIncludedNullParameter:(DataHandler *) dataHandler; 
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(void) AddFileTypeParameter:(DataHandler *) dataHandler valFileType:(NSString *) valFileType;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyScriptContentID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyScriptContentID query:(NSString *) query;

-(id<IScriptContentData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IScriptContentData>) FindByScriptContentID:(NSNumber *) fieldValue;
-(id<IScriptContentData>) FindByScriptID:(NSNumber *) fieldValue;
-(id<IScriptContentData>) FindByVersion:(NSNumber *) fieldValue;
-(id<IScriptContentData>) FindByScript:(NSString *) fieldValue; 
-(id<IScriptContentData>) FindByByteCode:(NSMutableData *) fieldValue; 
-(id<IScriptContentData>) FindByIncluded:(NSNumber *) fieldValue;
-(id<IScriptContentData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<IScriptContentData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IScriptContentData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(id<IScriptContentData>) FindByFileType:(NSString *) fieldValue; 
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IScriptContentData>) FindObject :(NSNumber *) keyScriptContentID ;
        
-(id<IScriptContentData>) Find:(DataHandler *) dataHandler;
        
-(id<IScriptContentData>) FindAllObjects;

-(id<IScriptContentData>) FindAllObjects:(NSString *) orderByField;

-(id<IScriptContentData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IScriptContentData>) CreateScriptContent:(id<IDataReader>) reader;
		
-(id<IScriptContentData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IScriptContentData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end