// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SurveyPanel.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "ISurveyPanelData.h"
#import "ISurveyPanelFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds SurveyPanel objects
/// </summary>



@interface  SurveyPanelFactoryBase : DataObjectFactory<ISurveyPanelData,ISurveyPanelFactoryBase>
{
}

+(NSString*)  FIELD_NAME_SURVEYPANELID;
+(NSString*)  FIELD_NAME_SURVEYID;
+(NSString*)  FIELD_NAME_PANELID;
+(NSString*)  FIELD_NAME_EXCLUDED;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_SURVEYPANELID;
+(NSString*) PARAMETER_NAME_SURVEYID;
+(NSString*) PARAMETER_NAME_PANELID;
+(NSString*) PARAMETER_NAME_EXCLUDED;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keySurveyPanelID ;
//-(BOOL) DeleteByPk:(NSNumber *) keySurveyPanelID;
// Define input parameters once only so they can be reused by other methods
-(void) AddSurveyPanelIDParameter:(DataHandler *) dataHandler valSurveyPanelID:(NSNumber *) valSurveyPanelID;	

-(void) AddSurveyIDParameter:(DataHandler *) dataHandler valSurveyID:(NSNumber *) valSurveyID;	

-(void) AddPanelIDParameter:(DataHandler *) dataHandler valPanelID:(NSNumber *) valPanelID;	

-(void) AddExcludedParameter:(DataHandler *) dataHandler valExcluded:(NSNumber *) valExcluded;	

-(void) AddExcludedNullParameter:(DataHandler *) dataHandler; 
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keySurveyPanelID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keySurveyPanelID query:(NSString *) query;

-(id<ISurveyPanelData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<ISurveyPanelData>) FindBySurveyPanelID:(NSNumber *) fieldValue;
-(id<ISurveyPanelData>) FindBySurveyID:(NSNumber *) fieldValue;
-(id<ISurveyPanelData>) FindByPanelID:(NSNumber *) fieldValue;
-(id<ISurveyPanelData>) FindByExcluded:(NSNumber *) fieldValue;
-(id<ISurveyPanelData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<ISurveyPanelData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<ISurveyPanelData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<ISurveyPanelData>) FindObject :(NSNumber *) keySurveyPanelID ;
        
-(id<ISurveyPanelData>) Find:(DataHandler *) dataHandler;
        
-(id<ISurveyPanelData>) FindAllObjects;

-(id<ISurveyPanelData>) FindAllObjects:(NSString *) orderByField;

-(id<ISurveyPanelData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<ISurveyPanelData>) CreateSurveyPanel:(id<IDataReader>) reader;
		
-(id<ISurveyPanelData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<ISurveyPanelData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end