// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SurveyBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Survey.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "ISurveyData.h"



#import "IScriptData.h";
#import "ScriptFactory.h";

//package OnePoint.PROM.Model 
    
	

    
@interface  SurveyBase : DataObject<DataObject, ISurveyData>
{
@private NSNumber *SurveyID;
        
@private NSNumber *IsGeofencing;
        
@private NSNumber *UserID;
        
@private NSString *Name;
        
@private NSString *Description;
        
@private NSString *Status;
        
@private NSNumber *Type;
        
@private NSNumber *MediaID;
        
	@private NSNumber* isMediaIDSpecified;
@private NSNumber *ScriptID;
        
	@private NSNumber* isScriptIDSpecified;
@private NSNumber *IsDeleted;
        
@private NSNumber *IsOffline;
        
@private NSNumber *IsCapi;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private NSNumber *EstimatedTime;
        
@private NSNumber *Occurences;
        
@private NSDate *DeadLine;
        
@private NSString *SearchTags;
        
@private id<IScriptData> relScript; 
}


	  
/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *SurveyID;

	
	@property(nonatomic,retain) NSNumber *IsGeofencing;

	
	@property(nonatomic,retain) NSNumber *UserID;

	
	@property(readwrite,strong) NSString *Name;

	
	@property(readwrite,strong) NSString *Description;

	
	@property(readwrite,strong) NSString *Status;

	
	@property(nonatomic,retain) NSNumber *Type;

	
	@property(nonatomic,retain) NSNumber *MediaID;

		///<summary>Determines whether MediaID currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,retain) NSNumber* isMediaIDSpecified;
	
	@property(nonatomic,retain) NSNumber *ScriptID;

		///<summary>Determines whether ScriptID currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,retain) NSNumber* isScriptIDSpecified;
	
	@property(nonatomic,retain) NSNumber *IsDeleted;

	
	@property(nonatomic,retain) NSNumber *IsOffline;

	
	@property(nonatomic,retain) NSNumber *IsCapi;

	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	
	@property(nonatomic,retain) NSNumber *EstimatedTime;

	
	@property(nonatomic,retain) NSNumber *Occurences;

	
	@property(readwrite,strong) NSDate *DeadLine;

	
	@property(readwrite,strong) NSString *SearchTags;

	@property(readwrite,strong) id<IScriptData> RelScript; 
@end
         

    

    