//------------------------------------------------------------------------
// Generated on 07/09/2015 16:29:09 for Sachin\Sachin
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------
#import <Foundation/Foundation.h>
#import "SurveyAddressFactoryBase.h"
#import "SurveyAddress.h"
#import "ISurveyAddressData.h"
#import <OnePointFramework/IDisposable.h>
//package OnePoint.PROM.Model 

@interface SurveyAddressFactory : SurveyAddressFactoryBase<IDisposable> {
}

@end

