// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SurveyAddress.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "ISurveyAddressData.h"
#import "ISurveyAddressFactoryBase.h"

//package OnePoint.PROM.Model; 
  

/// <summary>
/// Creates and finds SurveyAddress objects
/// </summary>



@interface  SurveyAddressFactoryBase : DataObjectFactory<ISurveyAddressData,ISurveyAddressFactoryBase>
{
}

+(NSString*)  FIELD_NAME_SURVEYADDRESSID;
+(NSString*)  FIELD_NAME_SURVEYID;
+(NSString*)  FIELD_NAME_ADDRESSLISTID;
+(NSString*)  FIELD_NAME_RANGE;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_SURVEYADDRESSID;
+(NSString*) PARAMETER_NAME_SURVEYID;
+(NSString*) PARAMETER_NAME_ADDRESSLISTID;
+(NSString*) PARAMETER_NAME_RANGE;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keySurveyAddressID ;
//-(BOOL) DeleteByPk:(NSNumber *) keySurveyAddressID;
// Define input parameters once only so they can be reused by other methods
-(void) AddSurveyAddressIDParameter:(DataHandler *) dataHandler valSurveyAddressID:(NSNumber *) valSurveyAddressID;	

-(void) AddSurveyIDParameter:(DataHandler *) dataHandler valSurveyID:(NSNumber *) valSurveyID;	

-(void) AddAddressListIDParameter:(DataHandler *) dataHandler valAddressListID:(NSNumber *) valAddressListID;	

-(void) AddRangeParameter:(DataHandler *) dataHandler valRange:(NSNumber *) valRange;	

-(void) AddRangeNullParameter:(DataHandler *) dataHandler; 
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keySurveyAddressID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keySurveyAddressID query:(NSString *) query;

-(id<ISurveyAddressData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<ISurveyAddressData>) FindBySurveyAddressID:(NSNumber *) fieldValue;
-(id<ISurveyAddressData>) FindBySurveyID:(NSNumber *) fieldValue;
-(id<ISurveyAddressData>) FindByAddressListID:(NSNumber *) fieldValue;
-(id<ISurveyAddressData>) FindByRange:(NSNumber *) fieldValue;
-(id<ISurveyAddressData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<ISurveyAddressData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<ISurveyAddressData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<ISurveyAddressData>) FindObject :(NSNumber *) keySurveyAddressID ;
        
-(id<ISurveyAddressData>) Find:(DataHandler *) dataHandler;
        
-(id<ISurveyAddressData>) FindAllObjects;

-(id<ISurveyAddressData>) FindAllObjects:(NSString *) orderByField;

-(id<ISurveyAddressData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<ISurveyAddressData>) CreateSurveyAddress:(id<IDataReader>) reader;
		
-(id<ISurveyAddressData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<ISurveyAddressData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end