//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/AccessFlags.java
//
//  Created by chinthan on 12/2/13.
//

#import <Foundation/Foundation.h>

#ifndef _AccessFlags_H_
#define _AccessFlags_H_

#define AccessFlags_AccAbstract 1024
#define AccessFlags_AccFinal 16
#define AccessFlags_AccInterface 512
#define AccessFlags_AccPublic 1
#define AccessFlags_AccSuper 32

@interface AccessFlags : NSObject {
}

+ (short int)AccPublic;
+ (short int)AccFinal;
+ (short int)AccSuper;
+ (short int)AccInterface;
+ (short int)AccAbstract;
- (id)init;
@end

#endif // _AccessFlags_H_
