//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/SymbolManagement/Access.java
//
//  Created by chinthan on 1/6/14.
//

typedef enum {
  Access_Get = 0,
  Access_Set = 1,
  Access_Modify = 2,
} Access;
