//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/AliasMap/AliasGenerator.java
//
//  Created by chinthan on 1/15/14.
//
#import "IGenerator.h"

@interface AliasGenerator : NSObject <IGenerator> {
 @public
  NSString *__Alias_;
  id __Configuration_;
  NSString *__Text_;
}

- (NSString *)getAlias;
- (void)setAliasWithNSString:(NSString *)value;
- (id)getConfiguration;
- (void)setConfigurationWithId:(id)value;
- (NSString *)getText;
- (void)setTextWithNSString:(NSString *)value;
- (BOOL)next;
- (BOOL)nextMulti;
- (void)reset;
- (void)resetMulti;
- (id)init;
@end

