//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/AliasMap/AliasMap.java
//
//  Created by chinthan on 1/15/14.
//

#import "IAliasMap.h"
#import "IGenerator.h"

@interface AliasMap : NSObject <IAliasMap> {
 @public
  id<IGenerator> __Generator_;
}

- (id<IGenerator>)getGenerator;
- (void)setGeneratorWithIGenerator:(id<IGenerator>)value;
- (long)aliasIndexWithNSString:(NSString *)aliasName;
- (NSMutableArray *)subAliasesWithNSString:(NSString *)fullName;
- (id)init;
@end


