//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Parser/Ast/AstNode.java
//
//  Created by chinthan on 1/15/14.
//


#import "StringFormat.h"
@class Handler;
@class SymbolTable;

//@protocol IAstNode;
@protocol IParser;
@protocol ISymbol;
#import "IAstNode.h"




@interface  AstNode : NSObject <IAstNode> {
 @public
  NSMutableArray *__Children_;
  id<ISymbol> __Local_;
  SymbolTable *__Table_;
  id<IAstNode> __Parent_;
  id<IParser> __Parser_;
  int __Line_;
  int __Column_;
}

- (id)initWithIParser:(id<IParser>)parser;
- (NSMutableArray *)getChildren;
- (void)setChildrenWithNSMutableArray:(NSMutableArray *)value;
- (id<ISymbol>)getLocal;
- (void)setLocalWithISymbol:(id<ISymbol>)value;
- (SymbolTable *)getTable;
- (void)setTableWithSymbolTable:(SymbolTable *)value;
- (id<IAstNode>)getParent;
- (void)setParentWithIAstNode:(id<IAstNode>)value;
- (id<IParser>)getParser;
- (void)setParserWithIParser:(id<IParser>)value;
- (int)getLine;
- (void)setLineWithInt:(int)value;
- (int)getColumn;
- (void)setColumnWithInt:(int)value;
- (BOOL)getHasChildren;
- (void)addWithIAstNode:(id<IAstNode>)node;
- (void)addWithISymbol:(id<ISymbol>)symbol;
- (void)addWithNSString:(NSString *)name;
- (void)addConstantWithNSString:(NSString *)name withIAstNode:(id<IAstNode>)node;
- (void)addParameterWithNSString:(NSString *)name;
- (NSString *)description;
- (NSString *)toStringWithStringFormatEnum:(StringFormat)format;
- (void)executeWithHandler:(Handler *)param0;
- (void)executeWithHandler:(Handler *)handler withBool:(BOOL)getValue;
@end

