//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/RecordLibrary/AttributeRecord.java
//
//  Created by chinthan on 12/2/13.
//

#import <Foundation/Foundation.h>
@class RecordContext;
@protocol IScriptReader;


#import "BaseRecord.h"

@interface AttributeRecord : BaseRecord {
}
- (NSMutableArray *)readWithRecordContext:(RecordContext *)context withIScriptReader:(id<IScriptReader>)reader;
@end

