//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/AudioControlPositions.java
//
//  Created by chinthan on 1/15/14.
//


typedef enum {
  AudioControlPositions_cpLeft = 0,
  AudioControlPositions_cpRight = 1,
  AudioControlPositions_cpTop = 2,
  AudioControlPositions_cpBottom = 3,
} AudioControlPositions;

