//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/AudioStyle.java
//
//  Created by ashchauhan on 6/20/14.
//

#import "IAudioStyle.h"
#import "AudioControlPositions.h"
#import "RecordModes.h"

@interface AudioStyle : NSObject<IAudioStyle> {
 @public
  NSString *name_;
  AudioControlPositions playControlPosition_;
  RecordModes record_;
  AudioControlPositions recordControlPosition_;
  BOOL __IsEmpty_;
}

- (id)init;
- (BOOL)getIsEmpty;
- (void)setIsEmpty:(BOOL)value;
- (NSString *)getName;
- (void)setName:(NSString *)value;
- (AudioControlPositions)getPlayControlPosition;
- (void)setPlayControlPosition:(AudioControlPositions)value;
- (RecordModes)getRecord;
- (void)setRecord:(RecordModes)value;
- (AudioControlPositions)getRecordControlPosition;
- (void)setRecordControlPosition:(AudioControlPositions)value;

@end

