//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/CallStackItem.java
//
//  Created by chinthan on 12/2/13.
//


#import <Foundation/Foundation.h>
#import "ScriptReader.h"

@class OPGMethod;

@interface CallStackItem : NSObject {
 @public
  NSMutableArray *__Locals_;
  int __Method_;
  int programCounter;
    int previousProgramCounter;

    NSData *__code;
    NSMutableArray *__LineNumbers;
}

@property(nonatomic,assign) int programCounter;


- (id)initWithMethod:(NSMutableArray *)methods withPointerInt:(int)pointer withInt:(int)ProgramCounter withPreviousCounter:(int)previousProgramCounter;
- (NSMutableArray *)getLocals;
- (void)setLocalsWithNSObjectArray:(NSMutableArray *)value;
- (int)getMethod;
- (void)setMethodWithMethod:(int)value;
- (int)getProgramCounter;
- (void)setCode:(NSData *)value;
- (NSData *)getCode;
- (void)setLineNumbers:(NSMutableArray *)value;
- (NSMutableArray *)getLineNumbers;
- (void)setProgramCounterWithInt:(int)value;
- (int)getPreviousProgramCounter;
- (void)setPreviousProgramCounterWithInt:(int)value;
+(CallStackItem *)deserializeWithInputStream:(NSMutableArray *)methods withStream:(NSData *)stream;
+(CallStackItem *)deserializeWithByteStream:(NSMutableArray *)methods withStream:(NSData *)byteStream;
+(CallStackItem *)deserializeWithMethods:(NSMutableArray *)methods withScriptReader:(ScriptReader *)reader;
-(int)getLineNumber:(int)programCounter withBool:(BOOL)isEqual;
-(NSData *)serialize;
@end


