//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/CategoryStyle.java
//
//  Created by ashchauhan on 6/20/14.
//

#import <Foundation/Foundation.h>

#import "ICategoryStyle.h"
@protocol IStyle;

@interface CategoryStyle : NSObject<ICategoryStyle> {
 @public
  id<IStyle> _label;
  id<IStyle> _style;
}

- (id<IStyle>)getLabel;
- (void)setLabel:(id<IStyle>)value;
- (id<IStyle>)getStyle;
- (void)setStyle:(id<IStyle>)value;
- (id)init;
- (id)initWithIStyle:(id<IStyle>)label;
- (id)initWithIStyle:(id<IStyle>)label
          withIStyle:(id<IStyle>)style;
@end
