//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/CategoryTypes.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  CategoryTypes_ctCategory = 0,
  CategoryTypes_ctCategoryList = 1,
} CategoryTypes;


