//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/CategoryFlagConstants.java
//
//  Created by chinthan on 1/15/14.
//


typedef enum {
  CategoryFlagConstants_flNone = 0,
  CategoryFlagConstants_flUser = 1,
  CategoryFlagConstants_flDontknow = 2,
  CategoryFlagConstants_flRefuse = 3,
  CategoryFlagConstants_flNoanswer = 4,
  CategoryFlagConstants_flOther = 5,
  CategoryFlagConstants_flMultiplier = 6,
  CategoryFlagConstants_flExclusive = 7,
  CategoryFlagConstants_flFixedPosition = 8,
  CategoryFlagConstants_flNoFilter = 9,
  CategoryFlagConstants_flInline = 10,
} CategoryFlagConstants;



