//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/CategoryFilterConstants.java
//
//  Created by chinthan on 1/15/14.
//

typedef enum {
  CategoryFilterConstants_cfAll = 0,
  CategoryFilterConstants_cfCategory = 1,
  CategoryFilterConstants_cfExpression = 2,
  CategoryFilterConstants_cfOther = 3,
  CategoryFilterConstants_cfElement = 4,
} CategoryFilterConstants;


