//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/CellStyle.java
//
//  Created by ashchauhan on 6/20/14.
//


#import <Foundation/Foundation.h>

#import "ICellStyle.h"
#import "BorderStyles.h"
#import "IStyle.h"

@interface CellStyle : NSObject<ICellStyle> {
 
  NSString *_bgcolor;
  NSString *_borderbottomcolor;
  BorderStylesEnum _borderbottomstyle;
  long long int _borderbottomwidth;
  NSString *_bordercolor;
  NSString *_borderleftcolor;
  BorderStylesEnum _borderleftstyle;
  long long int _borderleftwidth;
  NSString *_borderrightcolor;
  BorderStylesEnum _borderrightstyle;
  long long int _borderrightwidth;
  BorderStylesEnum _borderstyle;
  NSString *_bordertopcolor;
  BorderStylesEnum _bordertopstyle;
  long long int _bordertopwidth;
  long long int _borderwidth;
  long long int _colspan;
  NSString *_height;
  long long int _padding;
  long long int _paddingbottom;
  long long int _paddingleft;
  long long int _paddingright;
  long long int _paddingtop;
  long long int _repeatheader;
  long long int _repeatsideheader;
  long long int _rowspan;
  NSString *_width;
  BOOL _wrap;
  BOOL _isempty;
    id<IStyle> _style;
}

- (id)init;
- (id)initWithICellStyle:(id<ICellStyle>)from;
- (NSString *)getBgColor;
- (void)setBgColor:(NSString *)value;
- (NSString *)getBorderBottomColor;
- (void)setBorderBottomColor:(NSString *)value;
- (BorderStylesEnum)getBorderBottomStyle;
- (void)setBorderBottomStyle:(BorderStylesEnum)value;
- (long long int)getBorderBottomWidth;
- (void)setBorderBottomWidth:(long long int)value;
- (NSString *)getbordercolor;
- (void)setbordercolor:(NSString *)value;
- (NSString *)getBorderLeftColor;
- (void)setBorderLeftColor:(NSString *)value;
- (BorderStylesEnum)getBorderLeftStyle;
- (void)setBorderLeftStyle:(BorderStylesEnum)value;
- (long long int)getBorderLeftWidth;
- (void)setBorderLeftWidth:(long long int)value;
- (NSString *)getBorderRightColor;
- (void)setBorderRightColor:(NSString *)value;
- (BorderStylesEnum)getBorderRightStyle;
- (void)setBorderRightStyle:(BorderStylesEnum)value;
- (long long int)getBorderRightWidth;
- (void)setBorderRightWidth:(long long int)value;
- (BorderStylesEnum)getBorderStyle;
- (void)setBorderStyle:(BorderStylesEnum)value;
- (NSString *)getBorderTopColor;
- (void)setBorderTopColor:(NSString *)value;
- (BorderStylesEnum)getBorderTopStyle;
- (void)setBorderTopStyle:(BorderStylesEnum)value;
- (long long int)getBorderTopWidth;
- (void)setBorderTopWidth:(long long int)value;
- (long long int)getBorderWidth;
- (void)setBorderWidth:(long long int)value;
- (long long int)getColspan;
- (void)setColspan:(long long int)value;
- (NSString *)getHeight;
- (void)setHeight:(NSString *)value;
- (long long int)getPadding;
- (void)setPadding:(long long int)value;
- (long long int)getPaddingBottom;
- (void)setPaddingBottom:(long long int)value;
- (long long int)getPaddingLeft;
- (void)setPaddingLeft:(long long int)value;
- (long long int)getPaddingRight;
- (void)setPaddingRight:(long long int)value;
- (long long int)getPaddingtop;
- (void)setPaddingtop:(long long int)value;
- (long long int)getRepeatHeader;
- (void)setRepeatHeader:(long long int)value;
- (long long int)getRepeatSideHeader;
- (void)setRepeatSideHeader:(long long int)value;
- (long long int)getRowspan;
- (void)setRowspan:(long long int)value;
- (NSString *)getWidth;
- (void)setWidth:(NSString *)value;
- (BOOL)getWrap;
- (void)setWrap:(BOOL)value;
- (BOOL)getIsEmpty;
- (void)setIsEmpty:(BOOL)value;
- (id)initWithIStyle:(id<IStyle>)style;
- (id)initWithIStyle:(id<IStyle>)style withCellStyle:(id<ICellStyle>)from;

@end
