//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/ConstantNameRef.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ConstantNameRef_H_
#define _ConstantNameRef_H_

@class NSMutableArray;


#import "Constant.h"

@interface ConstantNameRef : Constant {
 @public
  NSMutableArray *__Constants_;
  short int __NameIndex_;
}

- (id)initWithByte:(char)tag
         withShort:(short int)index;
- (id)initWithByte:(char)tag
         withShort:(short int)index
withConstantArray:(NSMutableArray *)consts;
- (NSMutableArray *)getConstants;
- (void)setConstantsWithConstantArray:(NSMutableArray *)value;
- (short int)getNameIndex;
- (void)setNameIndexWithShort:(short int)value;
- (NSString *)description;
@end


#endif // _ConstantNameRef_H_
