//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/ConstantUtf8.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ConstantUtf8_H_
#define _ConstantUtf8_H_


#import "Constant.h"

@interface ConstantUtf8 : Constant {
 @public
  NSString *__Utf8_;
}

- (id)initWithNSString:(NSString *)u8;
- (NSString *)getUtf8;
- (void)setUtf8WithNSString:(NSString *)value;
- (NSString *)description;
@end

//J2OBJC_FIELD_SETTER(ConstantUtf8, __Utf8_, NSString *)

#endif // _ConstantUtf8_H_
