//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/ConstantDouble.java
//
//  Created by chinthan on 12/2/13.
//




#import "Constant.h"

@interface ConstantDouble : Constant {
 @public double Value_;
}
@property(nonatomic,assign) double Value_;

- (id)initWithDouble:(double)d;
@end

