//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/ConstantFloat.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ConstantFloat_H_
#define _ConstantFloat_H_


#import "Constant.h"

@interface ConstantFloat : Constant {
 @public
  float __Value_;
}

- (id)initWithFloat:(float)f;
- (float)getValue;
- (void)setValueWithFloat:(float)value;
- (NSString *)getdescription;
//- (void)copyAllFieldsTo:(ConstantFloat *)other;
@end

#endif // _ConstantFloat_H_
