//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/ConstantLong.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ConstantLong_H_
#define _ConstantLong_H_


#import "Constant.h"

@interface ConstantLong : Constant {
 @public
  long Value_;
}

@property(nonatomic,assign)long Value_;

- (id)initWithLong:(long)l;
@end

#endif // _ConstantLong_H_
