//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/RecordLibrary/ConstantPoolRecord.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ConstantPoolRecord_H_
#define _ConstantPoolRecord_H_

@protocol IScriptReader;


#import "BaseRecord.h"

@interface ConstantPoolRecord : BaseRecord {
 @public
  short int __ConstantPoolSize_;
  NSMutableArray *__Constants_;
}

- (id)init;
- (short int)getConstantPoolSize;
- (void)setConstantPoolSizeWithShort:(short int)value;
- (NSMutableArray *)getConstants;
- (void)setConstantsWithConstantArray:(NSMutableArray *)value;
- (BOOL)readWithIScriptReader:(id<IScriptReader>)reader;
@end


#endif // _ConstantPoolRecord_H_
