//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/ConstantInteger.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ConstantInteger_H_
#define _ConstantInteger_H_


#import "Constant.h"

@interface ConstantInteger : Constant {
 @public
  int Value_;
}
@property(nonatomic,assign) int Value_;

- (id)initWithInt:(int)i;
@end

#endif // _ConstantInteger_H_
