//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/UI/Controls.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebUIControls_H_
//#define _OnePointPlayerWebUIControls_H_


#import <Foundation/Foundation.h>

#import "IControl.h"

@interface Controls : NSObject<IControl> {
    NSMutableArray *array;
}
@property(nonatomic,retain) NSMutableArray *array;
- (id)init;
- (id)initWithObjects:(id)objects;
-(NSMutableArray *)getControlsArray;
-(void)setControlsArray:(NSMutableArray *)value;
-(void)clear;
- (void)addObject:(id)anObject;
- (void)insertObject:(id)anObject atIndex:(NSUInteger)index;
- (void)removeLastObject;
- (void)removeObjectAtIndex:(NSUInteger)index;
- (void)replaceObjectAtIndex:(NSUInteger)index withObject:(id)anObject;
- (NSUInteger)count;
- (id)objectAtIndex:(NSUInteger)index;
-(int)getArray;
//- (id<IControl>)get___idx:(Class)controlType;
//- (void)set___idx:(Class)controlType withIControl:(id<IControl>)value;
@end

//#endif // _OnePointPlayerWebUIControls_H_
