
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Controller.java
//
//  Created by ashchauhan on 3/11/14.
//



// babu
#import <Foundation/Foundation.h>
#import "IPlayer.h"
#import "Questions.h"
#import "Loader.h"
#import "Container.h"
#import "ISymbol.h"
#import "Handler.h"
#import "Workspace.h"

@interface Controller : NSObject<IPlayer> {
 @public
    id<IPlayer> __Player;
    Loader * __Loader;
    Container *__Container;
    Handler *__Handler;
}
- (id<IPlayer>)getPlayer;
- (void)setPlayer:(id<IPlayer>)value;
- (void)loadController:(NSString *)file;
- (void)ask;
+ (int)Main:(NSArray *)args;
- (void)loadFieldWithName:(NSString *)name
                 withValue:(NSString *)value;
- (id)initWithSurveyId:(NSString*)surveyId;

@end
