//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/ControlTypes.java
//
//  Created by chinthan on 1/15/14.
//

typedef enum {
  ControlTypes_ctStatic = 0,
  ControlTypes_ctEdit = 1,
  ControlTypes_ctSingleLineEdit = 2,
  ControlTypes_ctMultiLineEdit = 3,
  ControlTypes_ctDropList = 4,
  ControlTypes_ctComboList = 5,
  ControlTypes_ctRadioButton = 6,
  ControlTypes_ctCheckButton = 7,
  ControlTypes_ctListBox = 8,
  ControlTypes_ctListControl = 9,
  ControlTypes_ctButton = 10,
  ControlTypes_ctDate = 11,
  ControlTypes_ctTime = 12,
  ControlTypes_ctDateTime = 13,
  ControlTypes_ctPassword = 14,
  ControlTypes_ctSlider,
  ControlTypes_ctBarCode ,
  ControlTypes_ctGeoCode,
  ControlTypes_ctMedia,
  ControlTypes_ctDragAndDrop,
   ControlTypes_ctHotSpot,
    ControlTypes_ctStar,
    ControlTypes_ctEmail,
   
} ControlTypes;

