//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebControls/Resources/ControlDefinitions.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebControlsResourcesControlDefinitions_H_
//#define _OnePointPlayerWebWebControlsResourcesControlDefinitions_H_


static NSString *rscCulture;

@interface ControlDefinitions : NSObject {
    
    
}

- (id)init;
+(id)getCulture;
+(void)setCulture:(id)Culture;
+ (id)getResourceManager;
+ (NSString *)getGoto;
+ (NSString *)getNext;
+ (NSString *)getPrevious;
+ (NSString *)getQuit;
@end

//#endif // _OnePointPlayerWebWebControlsResourcesControlDefinitions_H_
