//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/CursorTypes.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  CursorTypes_crAuto = 0,
  CursorTypes_crCrossHair = 1,
  CursorTypes_crDefault = 2,
  CursorTypes_crPointer = 3,
  CursorTypes_crMove = 4,
  CursorTypes_crEResize = 5,
  CursorTypes_crNEResize = 6,
  CursorTypes_crNResize = 7,
  CursorTypes_crNWResize = 8,
  CursorTypes_crWResize = 9,
  CursorTypes_crSWResize = 10,
  CursorTypes_crSResize = 11,
  CursorTypes_crSEResize = 12,
  CursorTypes_crText = 13,
  CursorTypes_crWait = 14,
  CursorTypes_crHelp = 15,
} CursorTypes;

