//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/DefaultStyles.java
//
//  Created by ashchauhan on 6/20/14.
//


#import "IQuestionStyles.h"
#import "IDefaultStyles.h"

@interface DefaultStyles : NSObject<IDefaultStyles> {
 @public
  id<ICategoryStyles> _categories;
  id<IStyle> _default;
  id<IStyles> _grids;
  id<IStyles> _labels;
  id<IStyle> _navigation;
  id<IQuestionStyles> _questions;
}

- (id)init;
- (id)initWithICategoryStyles:(id<ICategoryStyles>)categories withIStyle:(id<IStyle>)defaultStyle withIStyles:(id<IStyles>)grids withIStyles:(id<IStyles>)labels withIStyle:(id<IStyle>)navigation withIQuestionStyles:(id<IQuestionStyles>)questions;
- (id<ICategoryStyles>)getCategories;
- (void)setCategories:(id<ICategoryStyles>)value;
- (id<IStyle>)getDefault;
- (void)setDefault:(id<IStyle>)value;
- (id<IStyles>)getGrids;
- (void)setGrids:(id<IStyles>)value;
- (id<IStyles>)getLabels;
- (void)setLabels:(id<IStyles>)value;
- (id<IStyle>)getNavigation;
- (void)setNavigation:(id<IStyle>)value;
- (id<IQuestionStyles>)getQuestions;
- (void)setQuestions:(id<IQuestionStyles>)value;
@end
