//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/ElementAlignments.java
//
//  Created by chinthan on 1/15/14.
//

typedef enum {
  ElementAlignments_eaDefault = 0,
  ElementAlignments_eaRight = 1,
  ElementAlignments_eaNewLine = 2,
} ElementAlignments;



