//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/BasicTypes/Empty.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _Empty_H_
#define _Empty_H_



@interface Empty : NSObject {
}

- (id)init;
@end

#endif // _Empty_H_
