//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/Source/ErrorHandler.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _ErrorHandler_H_
#define _ErrorHandler_H_



@interface ErrorHandler : NSObject {
}

- (id)init;
@end

#endif // _ErrorHandler_H_
