//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/Source/ErrorList.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _ErrorList_H_
#define _ErrorList_H_

@class ErrorArgs;

@protocol _ErrorHandler < NSObject >
- (void)invokeWithId:(id)o
       withErrorArgs:(ErrorArgs *)e;
- (id)getInvocationList;
@end

@interface ErrorList : NSMutableArray {
 @public
  id<_ErrorHandler> ErrorAdded_;
    NSMutableArray *errorList;
}

- (int)addValWithId:(id)value;
- (id)init;
- (void)copyAllFieldsTo:(ErrorList *)other;
@end




@interface _MultiErrorHandler : NSObject <_ErrorHandler > {
 @public
  id _invocationList_;
}

- (void)invokeWithId:(id)o
withErrorArgs:(ErrorArgs *)e;
+ (id<_ErrorHandler>)combineWith_ErrorHandler:(id<_ErrorHandler>)a with_ErrorHandler:(id<_ErrorHandler>)b;
+ (id<_ErrorHandler>)removeWith_ErrorHandler:(id<_ErrorHandler>)a with_ErrorHandler:(id<_ErrorHandler>)b;
- (id)getInvocationList;
- (void)setInvocationList:(id) list;
- (id)init;
@end


#endif // _ErrorList_H_
