//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/Source/ErrorArgs.java
//
//  Created by chinthan on 1/15/14.
//


@class ErrorInfo;


@interface ErrorArgs : NSObject {
 @public
  ErrorInfo *errorInfo_;
}

- (id)initWithErrorInfo:(ErrorInfo *)errorInfo;
@end


