//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/Source/ErrorInfo.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _ErrorInfo_H_
#define _ErrorInfo_H_
#import "ErrorType.h"




@interface ErrorInfo : NSObject {
 @public
  int __Col_;
  NSString *__FileName_;
  int __Line_;
  NSString *__Message_;
  ErrorType __Type_;
}

- (id)init;
- (id)initWithErrorTypeEnum:(ErrorType)type withNSString:(NSString *)message withInt:(int)line withInt:(int)col;
- (id)initWithErrorTypeEnum:(ErrorType)type withNSString:(NSString *)message withInt:(int)line withInt:(int)col withNSString:(NSString *)fileName;
- (int)getCol;
- (void)setColWithInt:(int)value;
- (NSString *)getFileName;
- (void)setFileNameWithNSString:(NSString *)value;
- (int)getLine;
- (void)setLineWithInt:(int)value;
- (NSString *)getMessage;
- (void)setMessageWithNSString:(NSString *)value;
- (ErrorType)getType;
- (void)setTypeWithErrorTypeEnum:(ErrorType)value;
- (NSString *)description;
@end

#endif // _ErrorInfo_H_
