//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/Source/ErrorType.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _ErrorType_H_
#define _ErrorType_H_




typedef enum {
  ErrorType_SyntaxError = 0,
  ErrorType_SymanticError = 1,
  ErrorType_Warning = 2,
} ErrorType;


#endif // _ErrorType_H_
