//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/ExceptionTable.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ExceptionTable_H_
#define _ExceptionTable_H_



@interface ExceptionTable : NSObject {
 @public
  short int __CatchType_;
  short int __EndPc_;
  short int __HandlerPc_;
  short int __StartPc_;
}

- (short int)getCatchType;
- (void)setCatchTypeWithShort:(short int)value;
- (short int)getEndPc;
- (void)setEndPcWithShort:(short int)value;
- (short int)getHandlerPc;
- (void)setHandlerPcWithShort:(short int)value;
- (short int)getStartPc;
- (void)setStartPcWithShort:(short int)value;
- (id)init;
@end

#endif // _ExceptionTable_H_
