//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/Source/Execute.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _Execute_H_
#define _Execute_H_

#import "ErrorList.h"


@interface Execute : NSObject  {
 @public
  ErrorList *__Errors_;
  NSString *__Source_;
  NSInputStream *__Stream_;
}

- (id)init;
- (id)initWithNSString:(NSString *)source;
- (ErrorList *)getErrors;
- (void)setErrorsWithErrorList:(ErrorList *)value;
- (NSString *)getSource;
- (void)setSourceWithNSString:(NSString *)value;
- (NSInputStream *)getStream;
- (void)setStreamWithJavaIoInputStream:(NSInputStream *)value;
@end

#endif // _Execute_H_
