//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Executor.java
//
//  Created by chinthan on 12/2/13.
//

#import "Stack.h"
#import "CallStackItem.h"
#import "FastStack.h"
#import "OPGMethod.h"
#import "Workspace.h"
#import "OnePointObject.h"
//@class Handler;
#import "Handler.h"
#import "IPlayer.h"

@interface Executor : NSObject {
 @public
  Workspace *environment_;
  BOOL bootStrapping_;
  Stack *callStack_;
  FastStack *stack_;
  CallStackItem *__Current_;
    Handler *handler;
    int programCounter;
    unsigned char* byteData;
    BOOL isEvent;
    
}

@property(nonatomic,retain)Stack *callStack_;

- (CallStackItem *)getCurrent;
- (void)setCurrentWithCallStackItem:(CallStackItem *)value;
- (id)initWithWorkspace:(Workspace *)chosenEnvironment;
- (FastStack *)getDataStack;
- (void)setDataStackWithFastStack:(FastStack *)value;

- (Stack *)getCallStack;
- (void)setCallStack:(Stack *)value;
- (Workspace *)getEnvironment;
- (void)setEnvironmentWithWorkSpace:(Workspace *)value;
- (Handler *)getHandler;
- (void)setHandler:(Handler *)value;
- (BOOL)getBootstrapping;
- (void)setBootstrappingWithBoolean:(BOOL)value;
- (void)callWithId:(id)method;
//- (void)createLocals;
//- (void)createLocalsWithMethod:(OPGMethod *)method
//                                                        withInt:(int)programCounter
//                                              withNSObjectArray:(NSMutableArray *)locals;
- (void)executeWithMethod:(OPGMethod *)chosenMethod
                                                   withInt:(int)newProgramCounter
                                         withNSObjectArray:(NSMutableArray *)methodLocals;

//- (void)executeWithData:(NSData *)code withLineNumberTable:(NSMutableArray *)lineNumbers withProgramCounter:(int)newProgramCounter;
- (void)executeWithMethods:(NSMutableArray *)methods withInt:(int)pointer withProgramCounter:(int)newProgramCounter;
- (void)execute:(BOOL)isevent;
- (void)throwExcWithOnePointObject:(OnePointObject *)exceptionObject;
- (BOOL)tryThrowWithOnePointObject:(OnePointObject *)exceptionObject;
- (void)fillStackTraceWithOnePointObject:(OnePointObject *)exceptionObject;
- (int)getInt32;
- (void)getNewIpWithBoolean:(BOOL)ok;
- (id)initWithCode:(char *)code withArray:(NSMutableArray *)lineNumbers withProgramCounter:(int)locals;
+(Executor *)deserializeWithWorkspace:(Workspace *)workspace withData:(NSData *)byteStream;
+(Executor *)deserializeWithWorkspace:(Workspace *)workspace withScriptReader:(ScriptReader *)reader;

-(void) deserializeWithStream:(NSData*) stream;
-(void) deserialize:(NSMutableData*) byteStream;

-(void)deserializeWithByteStream:(NSData *)byteStream;
-(void)deserializeWithInputStream:(NSData *)stream;
-(void)deserializeWithScriptReader:(ScriptReader *)reader;
-(NSMutableData *)serialize;

@end


