//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/FastStack.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _FastStack_H_
#define _FastStack_H_

#import "ScriptReader.h"


@interface FastStack : NSObject {
 @public
  NSMutableArray *stack_;
  int stackPointer_;
}

- (id)initWithInt:(int)stackSize;
- (NSMutableArray *)getStack;
- (int)getPointer;
- (void)clear;
- (void)drop;
- (void)dropWithInt:(int)dropSize;
- (void)drop2;
- (void)dup;
- (void)dup2;
- (void)dupX1;
- (void)dupX2;
- (void)dup2X1;
- (id)getWithInt:(int)offset;
- (id)pop;
- (void)pushWithId:(id)obj;
- (void)swap;
- (NSString *)description;
+(FastStack *)deserializeWithByteStream:(NSData *)byteStream;
+(FastStack *)deserializeWithInputStream:(NSData *)stream;
+(FastStack *)deserializeWithScriptReader:(ScriptReader *)reader;
-(NSData *)serialize;

@end

//J2OBJC_FIELD_SETTER(FastStack, stack_, NSMutableArray *)

#endif // _FastStack_H_
