//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/Source/FatalError.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _FatalError_H_
#define _FatalError_H_




@interface FatalError : NSObject {
}

- (id)initWithNSString:(NSString *)m;
@end

#endif // _FatalError_H_
