//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Handler.java
//
//  Created by nitin on 1/15/14.
//


@class SymbolTable;
@class FastStack;
@protocol ISavePoint;
@protocol IInterview;
#import "IPlayer.h"
#import "Executor.h"
#import "AstBinaryExpression.h"
#import "Interview.h"
@protocol ISymbol;
#import "InterviewAction.h"
#import "EventType.h"
#import "Stack.h"
#import "ScriptReader.h"

@interface Handler : NSObject {
 @public
    SymbolTable *__Local_;
    SymbolTable *__Global_;
    Executor *__Executor_;
    FastStack *__Stack_;
    FastStack *__StackList_;
    Stack *__SymbolTableStack;
    id<ISymbol> __MetaData;
    id<ISavePoint> __SavePoint;
    id<IPlayer> __Player;
    NSString *__Expression;
    Interview *__Interview;
    InterviewAction __Action;
    NSMutableDictionary *__Events;
}

- (id)initWithExecutor:(Executor *)executor withPlayer:(id<IPlayer>)player withInterview:(Interview *)interview;


- (id<ISymbol>)getMetaData;
- (void)setMetaDataWithISymbol:(id<ISymbol>)value;

- (SymbolTable *)getLocalWithSymbolTable;
- (void)setLocalWithSymbolTable:(SymbolTable *)value;
- (SymbolTable *)getGlobal;
- (void)setGlobal:(SymbolTable *)value;
- (Executor *)getExecutor;
- (void)setExecutorWithExecutor:(Executor *)value;
- (FastStack *)getStack;
- (void)setStackWithCoreFastStack:(FastStack *)value;
- (FastStack *)getStackList;
- (void)setStackListWithJavaUtilStack:(FastStack *)value;

- (id<IPlayer>)getPlayer;
- (void)setPlayer:(id<IPlayer>)value;
- (NSString *)getExpression;
- (void)setExpression:(NSString *)value;
- (NSMutableDictionary *)getEvents;
- (void)setEvents:(NSMutableDictionary *)value;

-(id<ISymbol>)lookupWithNSString:(NSString *)name;
- (void)push;
- (void)pop;
-(void)pushFunction;
- (void)pushWithNSString:(NSString *)name;
- (void)pushEmpty;
- (void)pushStack;
- (void)popStack;
- (int)conditionWithNSString:(NSString *)expression;
- (void)executeWithNSString:(NSString *)expression;
- (void)newObjWithNSString:(NSString *)nameString;
- (void)assignWithNSString:(NSString *)name
                    withId:(id)value;
- (void)newObjWithNSString:(NSString *)name
                    withId:(id)value;
- (void)fieldWithNSString:(NSString *)name
             withNSString:(NSString *)value;
-(void)onError:(id)value;
-(InterviewAction) getAction;

-(void)setAction:(InterviewAction)value;
-(Interview *)getInterview;
-(void)setInterview:(Interview *) value ;

-(id<ISavePoint>) getSavePoint;
-(void)setSavePoint:(id<ISavePoint>) value ;
-(Stack*) getSymbolTableStack ;
-(void) setSymbolTableStack:(Stack*) value ;
-(NSMutableData *)serialize;
-(void)deserializeWithScriptReader:(ScriptReader*) reader;
-(void) deserializeWithStream:(NSData*) stream;
-(void) deserialize:(NSMutableData*) byteStream;

-(void)buildEvents;
-(void)buildevents:(EnumEventType)eventType;
-(void)runEvent:(EnumEventType)eventType withQuestion:(id<IQuestion>)question;
-(BOOL)runFunction:(NSString *)methodName withQuestion:(id<IQuestion>)question;
@end


