//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebControls/Resources/HtmlDefinitions.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebControlsResourcesHtmlDefinitions_H_
//#define _OnePointPlayerWebWebControlsResourcesHtmlDefinitions_H_

#import <Foundation/Foundation.h>

static NSString *resourceCulture;
@interface HtmlDefinitions : NSObject {
   
}

- (id)init;
+(id)getResourceManager;
+ (NSString *)getInput;
+ (NSString *)getSpan;
+(id)getCulture;
+(void)setCulture:(id)value;
@end

//#endif // _OnePointPlayerWebWebControlsResourcesHtmlDefinitions_H_
