//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/HtmlControls/HtmlControl.java
//
//  Created by ashchauhan on 3/11/14.
//





#import "Control.h"
#import "GDataXMLNode.h"
@interface HtmlControl :Control{
 @public
  NSString *__InnerHtml_;
  NSString *__PostHtml_;
  NSString *__PreHtml_;
  NSString *__TagName_;
}

- (id)initWithIControl:(id<IControl>)parent
                             withXML:(NSString *)xml;
- (id)initWithIControl:(id<IControl>)parent
                                   withNode:(GDataXMLNode*)node;
- (NSString *)getInnerHtml;
- (void)setInnerHtml:(NSString *)value;
- (NSString *)getPostHtml;
- (void)setPostHtml:(NSString *)value;
- (NSString *)getPreHtml;
- (void)setPreHtml:(NSString *)value;
- (NSString *)getTagName;
- (void)setTagName:(NSString *)value;
- (void)render:(id<IResponse>)response;
-(void)processXml:(GDataXMLNode*)node;
@end


