//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/HtmlControls/HtmlInput.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebHtmlControlsHtmlInput_H_
//#define _OnePointPlayerWebHtmlControlsHtmlInput_H_

@protocol IControl;
#import "GDataXMLNode.h"

#import "HtmlControl.h"

@interface HtmlInput : HtmlControl {
}

- (id)initWithIControl:(id<IControl>)parent
                                   withId:(GDataXMLNode*)node;
@end

//#endif // _OnePointPlayerWebHtmlControlsHtmlInput_H_
