//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/AliasMap/IAliasMap.java
//
//  Created by chinthan on 1/15/14.
//

#import "IGenerator.h"

@protocol IAliasMap < NSObject >
- (id<IGenerator>)getGenerator;
- (long)aliasIndexWithNSString:(NSString *)aliasName;
- (NSMutableArray *)subAliasesWithNSString:(NSString *)fullName;
- (id)variableInstanceWithNSString:(NSString *)aliasName;
@end

