//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/AliasMap/IAlias.java
//
//  Created by chinthan on 1/15/14.
//

@protocol IAlias <NSObject>
- (NSString *)getName;
- (long)getIndex;
- (void)setIndexWithLong:(long)value;
- (id)getReference;
- (void)setReferenceWithId:(id)value;
@end

