//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/ICategory.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _ICategory_H_
//#define _ICategory_H_

@protocol ICategories;
@protocol ILabel;
@protocol IProperties;
@protocol IQuestion;
@protocol IStyle;
#import <Foundation/Foundation.h>
#import "OrderConstants.h"
#import "Variant.h"
#import "CategoryTypes.h"

@protocol ICategory < NSObject >
- (long)getAttributes;
- (id<ICategories>)getcategories;
- (void)setcategories:(id<ICategories>)value;
- (CategoryTypes)getCategoryType;
- (long)getCount;
- (Variant*)getFactor;
- (NSString *)getFullName;
- (int)getIndex;
- (NSString *)getKeyCode;
- (id<ILabel>)getLabel;
- (NSString *)getName;
- (id<IQuestion>)getOtherQuestion;
- (id<ICategory>)getParent;
- (id<IQuestion>)getParentQuestion;
- (id<IProperties>)getProperties;
- (id<IStyle>)getStyle;
- (Variant*)getValue;
- (Variant*)getFilter;
- (void)setFilter:(Variant*)value;
- (OrderConstants)getOrder;
- (void)setOrder:(OrderConstants)value;
- (Variant*)get___idx:(long)index;
- (void)set___idxWithLong:(long)index
                   withId:(Variant*)value;
- (BOOL)getIsOther;
- (BOOL)getIsCode;
- (BOOL)getIsFixed ;

- (BOOL)getIsNa ;

- (BOOL)getIsDk ;

- (BOOL)getIsRef ;

- (BOOL)getCanFilter ;

-(void)setCanFilter:(BOOL)value ;

@end
