//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/ICategories.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _ICategories_H_
//#define _ICategories_H_
#import <Foundation/Foundation.h>
#import "OrderConstants.h"
#import "SortOrder.h"

@protocol ICategory;

@protocol ICategories < NSObject>
-(int)getCount;
-(int)getCountWithoutOthers;
-(void) setCountWithoutOthers:(int)value ;
- (id)getdefaultproperty;
- (void)setdefaultproperty:(id)value;
- (SortOrder)getOrder;
- (void)setOrder:(SortOrder)value;
-(void)setOrderConstants:(OrderConstants)value;
-(OrderConstants)getOrderConstants;
- (NSMutableArray*)getItems;
- (void)add:(id<ICategory>)value;
- (void)add:(NSString *)key withICategory:(id<ICategory>)value;
- (void)add:(NSString *)key withICategory:(id<ICategory>)value withIndex:(int)index;
- (void)remove:(int)index;
- (void)removeWithNSString:(NSString *)key;
- (void)clear;
- (BOOL)containsKey:(NSString *)key;
- (BOOL)containsValue:(id<ICategory>)value;
- (id)getEnumerator;
-(id)getValue;
- (id<ICategory>)get___idxWithNSString:(NSString *)key;
- (void)set___idxWithNSString:(NSString *)key withICategory:(id<ICategory>)value;
- (id<ICategory>)get___idx:(int)index;
- (void)set___idx:(int)index withICategory:(id<ICategory>)value;
- (void)copy:(id<ICategories>)from ;
- (void)sortList;
@end

