//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/Helpers/ICollectionObject.java
//
//  Created by nitin on 1/15/14.
//

#ifndef _ICollectionObject_H_
#define _ICollectionObject_H_


#import "SortOrder.h"
@protocol ICollectionObject < NSObject >
- (void)addWithId:(id)key
           withId:(id)value;
- (void)addWithId:(id)key
           withId:(id)value
          withInt:(int)index;
- (id)itemWithId:(id)index;
- (void)removeWithInt:(int)index;
- (void)removeWithId:(id)key;
-(SortOrder) getOrder ;

-(void)setOrder:(SortOrder)value;

/**
 * Gets the items.
 */
-(NSArray*)getItems ;

-(int) getCount;

-(id)get___idx:(id) key ;

-(void) set___idx:(id) key value:(id)value ;

/**
 * The item.
 *
 *  @param index
 * The index.
 *
 *  @return
 * The
 *  {@link #TV}
 * .
 */
//TV get___idx(Object index) throws Exception ;

//void set___idx(Object index, TV value) throws Exception ;

-(BOOL) containsKey:(id) key;

-(BOOL) containsValue:(id) value ;

/**
 * The add.
 *
 *  @param key
 * The key.
 *
 *  @param value
 * The value.
 */
-(void) add:(id) key value:(id)value;

/**
 * The add.
 *
 *  @param key
 * The key.
 *
 *  @param value
 * The value.
 *
 *  @param index
 * The index.
 */
-(void) add:(id)key value:(id)value index:(int) index;

/**
 * The remove.
 *
 *  @param index
 * The index.
 */
-(void) removeAtIndex:(int) index ;

/**
 * The remove.
 *
 *  @param key
 * The key.
 */
-(void)removeKey:(id) key;

-(void) clear;

-(void) clearForSort;

-(void) sortList ;
@end

#endif // _ICollectionObject_H_
