//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/IContext.java
//
//  Created by ashchauhan on 3/11/14.
//


#import <Foundation/Foundation.h>

@protocol IRequest;
@protocol IResponse;

@protocol IContext < NSObject>
- (id<IResponse>)getResponse;
- (void)setResponse:(id<IResponse>)value;
- (id<IRequest>)getRequest;
- (void)setRequest:(id<IRequest>)value;
@end

