//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/UI/IControl.java
//
//  Created by ashchauhan on 3/11/14.
//




#import "IResponse.h"
@class Controls;
@class Page;
@protocol IControl <NSCopying,NSObject>
- (NSString *)getClientId;
- (void)setClientId:(NSString *)value;
- (id<IControl>)findControlWithClientID:(NSString *)clientId;
- (id<IControl>)findControl:(id)controlType;
- (id<IControl>)getParent;
- (void)setParent:(id<IControl>)value;
- (void)render:(id<IResponse>)response;
- (Page*)getPage;
- (void)setPage:(Page*)value;
- (Controls *)getControls;
- (void)setControls:(Controls *)value;
@end

