//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IFontStyle.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _IFontStyle_H_
//#define _IFontStyle_H_

#import <Foundation/Foundation.h>


@protocol IFontStyle < NSObject>

- (long int)getEffects;
- (void)setEffects:(long int)value;
- (NSString *)getFamily;
- (void)setFamily:(NSString *)value;
- (long int)getSize;
- (void)setSize:(long int)value;
- (BOOL)getIsEmpty;
- (void)copyTo:(id<IFontStyle>)font;
@end
