//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/AliasMap/IGenerator.java
//
//  Created by chinthan on 1/15/14.
//



@protocol IGenerator < NSObject >
- (NSString *)getAlias;
- (id)getConfiguration;
- (NSString *)getText;
- (void)setTextWithNSString:(NSString *)value;
- (BOOL)next;
- (BOOL)nextMulti;
- (void)reset;
- (void)resetMulti;
@end
