//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IInterviewSampleRecord.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _IInterviewSampleRecord_H_
//#define _IInterviewSampleRecord_H_

@protocol IInterviewSampleField;




@protocol IInterviewSampleRecord < NSObject>
- (void)add:(NSString *)key withIInterviewSampleField:(id<IInterviewSampleField>)value;
- (void)add:(NSString *)key withIInterviewSampleField:(id<IInterviewSampleField>)value withIndex:(int)index;
- (void)remove:(int)index;
- (void)removeWithNSString:(NSString *)key;
-(NSMutableArray*)getItems;
- (int)getCount;
- (void)clear;
- (BOOL)containsKey:(NSString *)key;
- (BOOL)containsValue:(id<IInterviewSampleField>)value;
- (id<IInterviewSampleField>)get___idxWithNSString:(NSString *)key;
- (void)set___idxWithNSString:(NSString *)key withIInterviewSampleField:(id<IInterviewSampleField>)value;
@end

// _IInterviewSampleRecord_H_
