//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/ILabel.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _ILabel_H_
//#define _ILabel_H_
#import <Foundation/Foundation.h>

@protocol ILabelInserts;
@protocol IStyle;
@protocol IQuestion;
@class Interview;


@protocol ILabel <NSObject>
- (id<ILabelInserts>)getinserts;
- (NSString *)getName;
- (void)setName:(NSString *)value;
- (id<IStyle>)getStyle;
- (void)setStyle:(id<IStyle>)value;
- (id)getdefaultproperty;
- (void)setdefaultproperty:(id)value;
- (id<ILabel>)clone;
-(NSString*)getOriginalText;

-(NSString*)description ;
-(NSString*)description:(Interview*) interview withQuestion:(id<IQuestion>)question;
- (id)getowner;
- (void)setowner:(id)value;
@end

// _ILabel_H_
