//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/ILabels.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _ILabels_H_
//#define _ILabels_H_
#import <Foundation/Foundation.h>
@protocol ILabel;

@protocol ILabels < NSObject>

- (id<ILabel>)addNew:(NSString *)name withNSString:(NSString *)text;

- (void)add:(NSString *)key withILabel:(id<ILabel>)value;
- (void)add:(NSString *)key withILabel:(id<ILabel>)value withInt:(int)index;
- (void)remove:(int)index;
- (void)removeWithNSString:(NSString *)key;
- (NSMutableArray*)getItems;
- (int)getCount;
- (void)clear;
- (BOOL)containsKey:(NSString *)key;
- (BOOL)containsValue:(id<ILabel>)value;
- (id)getEnumerator;
- (id<ILabel>)get___idxWithNSString:(NSString *)key;
- (void)set___idxWithNSString:(NSString *)key withILabel:(id<ILabel>)value;
-(id<ILabel>)get___idxWithId:(id)key ;
-(id)get___idxwithint:(NSNumber *) key;
- (void)set___idxWithId:(NSString *)key withILabel:(id<ILabel>)value;
@end

// _ILabels_H_
