//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/ILevel.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _ILevel_H_
//#define _ILevel_H_




@protocol ILevel < NSObject>
@end

// _ILevel_H_
