//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/ImagePositions.java
//
//  Created by chinthan on 1/15/14.
//


typedef enum {
  ImagePositions_ipLeft = 0,
  ImagePositions_ipRight = 1,
  ImagePositions_ipTop = 2,
  ImagePositions_ipBottom = 3,
  ImagePositions_ipImageOnly = 4,
} ImagePositions;


