//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/InnerClass.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _InnerClass_H_
#define _InnerClass_H_



@interface InnerClass : NSObject {
 @public
  short int __InnerClassAccessFlags_;
  NSString *__InnerClassName_;
  NSString *__InnerName_;
  NSString *__OuterClassName_;
}

- (short int)getInnerClassAccessFlags;
- (void)setInnerClassAccessFlagsWithShort:(short int)value;
- (NSString *)getInnerClassName;
- (void)setInnerClassNameWithNSString:(NSString *)value;
- (NSString *)getInnerName;
- (void)setInnerNameWithNSString:(NSString *)value;
- (NSString *)getOuterClassName;
- (void)setOuterClassNameWithNSString:(NSString *)value;
- (id)init;
@end



#endif // _InnerClass_H_
