//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/InterviewStatus.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  InterviewStatus___dummyEnum__0 = 0,
  InterviewStatus_isIdle = 1,
  InterviewStatus_isPost = 2,
  InterviewStatus_isTimedOut = 3,
  InterviewStatus_isStopping = 4,
  InterviewStatus_isComplete = 5,
  InterviewStatus_isStopped = 6,
  InterviewStatus_isShutdown = 7,
} InterviewStatus;


