//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Session/InterviewSession.java
//
//  Created by ashchauhan on 3/21/14.
//

#import <Foundation/Foundation.h>
@protocol IPlayer;
@protocol IRender;
@class Workspace;
@class Interview;
@class Handler;

@interface InterviewSession : NSObject {
 
  NSString *__project_;
  NSString *__SessionId_;
  NSString* projectName;
    id<IPlayer> __player_;
    int __SurveyId;
    Workspace *environment;
    Handler *__handler;
    
    
}

- (id)initWithIPlayer:(id<IPlayer>)player
        withInterview:(Interview *)interview
             withType:(int)renderType;
- (id)initWithIPlayer:(id<IPlayer>)player
          withIrender:(id<IRender>)render
        withInterview:(Interview *)interview
             withType:(int)renderType;
- (id)initWithNSData:(NSData*)classFile withNSData:(NSData*)stringFile
         withIPlayer:(id<IPlayer>)player
       withInterview:(Interview *)interview
            withType:(int)renderType;
- (id)initWithIPlayer:(id<IPlayer>)player withInterview:(Interview *)interview withType:(int)renderType withSurveyId:(NSString *)surveyId withZipFile:(Byte*)zipFile;
- (id)initWithIPlayer:(id<IPlayer>)player withInterview:(Interview *)interview withType:(int)renderType loadStream:(Byte *)byteStream withLength:(int)length withLongStingByteArray:(Byte *)longByte withLongStrLength:(int)longStrLength;

- (id)initWithIPlayer:(id<IPlayer>)player withInterview:(Interview *)interview withType:(int)renderType loadStream:(Byte *)byteStream withLength:(int)length withLongStingByteArray:(Byte *)longByte withLongStrLength:(int)longStrLength withZipFile:(Byte*)zipFile;

-(int) getSurveyId;
-(void)setSurveyId:(int) value;
-(Handler*) getHandler;
-(void)setHandler:(Handler*) value;
- (NSString *)getSessionId;
- (void)setSessionId:(NSString *)value;
- (NSString *)getCompiledFile;
- (void)execute;
- (BOOL)validate;
-(void)updatePlayer:(id)context;
-(Interview *)load;
@end