//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/InterviewAction.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _InterviewAction_H_
//#define _InterviewAction_H_





typedef enum {
  InterviewAction_Continue = 0,
  InterviewAction_Show = 1,
  InterviewAction_Ask = 2,
  InterviewAction_Terminate = 3,
  InterviewAction_Paused = 4,
  InterviewAction_Goto = 5,
  InterviewAction_Restart = 6,
  InterviewAction_Rerun = 7,
} InterviewAction;
