//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IResponse.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _IResponse_H_
//#define _IResponse_H_

#import <Foundation/Foundation.h>

@protocol IResponses;
@protocol IValue;
#import "DataTypeConstants.h"



@protocol IOMIResponse < NSObject>
- (NSString *)getLabel;
- (NSString *)getName;
- (id<IResponses>)getOther;
- (NSString *)getCoded;
- (void)setCoded:(NSString *)value;
- (DataTypeConstants)getDataType;
- (void)setDataType:(DataTypeConstants)value;
- (id)getDefault;
- (void)setDefault:(id)value;
- (id)getInitial;
- (void)setInitial:(id)value;
- (NSNumber *)getIsDirty;
- (void)setIsDirty:(NSNumber *)value;
- (id)getValue;
- (void)setValue:(id)value;
- (void) setvalue:(id)value;
- (id<IValue>)getValueObj;
- (void)setValueObj:(id<IValue>)value;
-(NSDate*)getAsked ;
-(void)setAsked:(NSDate*)value;
-(NSDate*)getAnswered;
-(void)setAnswered:(NSDate*)value;
- (void)clear;
@end

// _IResponse_H_
