//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Parser/IParser.java
//
//  Created by chinthan on 1/15/14.
//


#import "SymbolTable.h"
#import "Errors.h"
#import "IScanner.h"
#import "IToken.h"
#import "NSMutableArray+Error.h"
#import "Handler.h"
//@class Handler;

@protocol IParser <NSObject>
- (Handler *)getHandler;
- (void)setHandler:(Handler *)value;
- (id<IToken>)getLookAhead;
- (id<IScanner>)getScanner;
- (SymbolTable *)getSymbols;
- (void)setSymbols:(SymbolTable *)value;
- (id<IToken>)getToken;
- (Errors *)geterrors;
- (void)seterrorsWithErrors:(Errors *)value;
- (void)semErrWithNSString:(NSString *)msg;
-(BOOL)getCondition;
-(void)setCondition:(BOOL)value;
-(BOOL)getIsSet;
-(void)setIsSet:(BOOL)value;
@end

