//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IQuestion.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _IQuestion_H_
//#define _IQuestion_H_
#import <Foundation/Foundation.h>

@protocol ICategories;
@protocol ILabel;
@protocol ILabels;
@protocol IObjects;
@protocol IQuestions;
@protocol IStyle;
@protocol IValidation;
@protocol ISavePoint;
@protocol MediaTypes;
@class Handler;
@protocol ICategory;
@protocol IProperties;
#import "IOMIResponse.h"
#import "QuestionTypes.h"
#import "OrderConstants.h"
#import "DataTypeConstants.h"
#import "MediaTypes.h"
#import "IQuestionInfo.h"
@protocol IQuestion < NSObject>

- (id<ICategories>)getcategories;
- (void)setcategories:(id<ICategories>)value;
- (NSString *)getBannerTemplate;
- (void)setBannerTemplate:(NSString *)value;
- (id<ILabels>)getBanners;
- (id<ICategories>)getCodes;
- (int)getCount;
- (NSString *)getJson;
- (void)setJson:(NSString *)value;
- (NSString *)getDBFilter;
- (void)setDBFilter:(NSString *)value;
- (NSString *)getErrorTemplate;
- (void)setErrorTemplate:(NSString *)value;
- (id<ILabels>)getErrors;
- (id<IQuestionInfo>)getInfo;
- (BOOL)getIsDBQuestion;
- (id<IQuestions>)getItem;
- (void)setItem:(id<IQuestions>)value;
- (id<ILabel>)getLabel;
- (void)setLabel:(id<ILabel>)value;
-(id<ILabel>)getGotoLabel;
-(void)setGotoLabel:(id<ILabel>)value;
- (NSString *)getLayoutTemplate;
- (void)setLayoutTemplate:(NSString *)value;
- (BOOL)getMustAnswer;
- (void)setMustAnswer:(BOOL)value;
- (NSString *)getNavBarTemplate;
- (void)setNavBarTemplate:(NSString *)value;
- (id<IObjects>)getOtherCategories;
- (id<IQuestion>)getParentQuestion;
- (id<ICategory>)getparentcategory;
- (void)setparentcategory:(id<ICategory>)value;
- (id<IProperties>)getProperties;
- (void)setProperties:(id<IProperties>)value;
-(void) setQuestionDataType:(DataTypeConstants)value ;
- (DataTypeConstants)getQuestionDataType;
- (id)getquestionfilter;
- (void)setquestionfilter:(id)value;
- (NSString *)getQuestionFullName;
- (NSString *)getQuestionName;
- (OrderConstants)getQuestionOrder;
- (void)setQuestionOrder:(OrderConstants)value;
- (NSString *)getQuestionTemplate;
- (void)setQuestionTemplate:(NSString *)value;
- (QuestionTypes)getQuestionType;
- (void)setQuestionType:(QuestionTypes)value;
- (id<IOMIResponse>)getResponse;
- (id<IStyle>)getStyle;
- (id<IValidation>)getValidation;
-(long)getVariableId ;
-(void)setVariableId:(long)value ;
-(BOOL)getIsGrid;
-(BOOL) getIsExpand;
-(MediaTypes)getMediaType ;
-(void)setMediaType:(MediaTypes)value;
-(BOOL) getNoCaseData;
- (void)ask:(Handler*)handler;
- (NSString *)buildDBFilter:(NSString *)fieldName;
- (void)clearOffPathResponse;
- (void)deleteId:(id)index;
- (BOOL)exists:(id)index;
- (void)preserve;
- (id)show:(Handler*)handler withArray:(NSMutableArray *)args;
- (void)clearResponses;
-(id<ICategory>)getParentCategory;
-(id<ISavePoint>)getsavepoint;
-(void)setsavepoint:(id<ISavePoint>)value;


@end

// _IQuestion_H_
