
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IQuestionInfo.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _IQuestionInfo_H_
//#define _IQuestionInfo_H_


#import <Foundation/Foundation.h>

@protocol IQuestionInfo < NSObject>
-(long)getAnswerCount;
-(void)setAnswerCount:(long)value;
-(long)getAskCount;
-(void)setAskCount:(long)value;
-(long)getErrorCount;
-(void)setErrorCount:(long)value;
-(BOOL)getIsOnPath;
-(void)setIsOnPath:(BOOL)value;
-(id)getOffPathCodedResponse;
-(void)setOffPathCodedResponse:(id)value;
-(long)getOnPathAnswerCount;
-(void)setOnPathAnswerCount:(long)value;
-(id)getOffPathResponse;
-(void)setOffPathResponse:(id)value;
@end

