//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IQuestionStyle.java
//
//  Created by ashchauhan on 6/20/14.
//


#import "ICategoryStyles.h"
#import "IStyle.h"
#import "IStyles.h"





@protocol IQuestionStyle < NSObject>
- (id<ICategoryStyles>)getCategories;
- (id<IStyles>)getLabels;
- (id<IStyle>)getStyle;
@end

// _IQuestionStyle_H_
