//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/Helpers/IReadOnlyCollectionObject.java
//
//  Created by nitin on 1/15/14.
//

#ifndef _IReadOnlyCollectionObject_H_
#define _IReadOnlyCollectionObject_H_



@protocol IReadOnlyCollectionObject < NSObject >
- (id)itemWithId:(id)index;
@end

#endif // _IReadOnlyCollectionObject_H_
