//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Debug/IRender.java
//
//  Created by chinthan on 12/2/13.
//



@class IOSByteArray;
@class Executor;



@protocol IRender <NSObject>
- (NSMutableDictionary *)getLines;
- (void)setLinesWithJavaUtilHashMap:(NSMutableDictionary *)value;
- (BOOL)getContinue;
- (void)setContinueWithBoolean:(BOOL)value;
- (BOOL)getRun;
- (void)setRunWithBoolean:(BOOL)value;
- (NSString *)buildAssemblyCodeWithByteArray:(NSData *)code;
- (void)loadInstructionDefinitions;
- (void)displayWithExecutor:(Executor *)executor;
@end

