//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/IResponse.java
//
//  Created by ashchauhan on 3/11/14.
//

#import <Foundation/Foundation.h>

@protocol IResponse<NSObject>
- (void)write:(id)data;
@end

//#endif // _OnePointPlayerIResponse_H_
