//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Parser/IScanner.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _IScanner_H_
#define _IScanner_H_



@protocol IScanner < NSObject >
- (NSString *)getFileName;
@end

#endif // _IScanner_H_
