//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IScript.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _IScript_H_
//#define _IScript_H_




@protocol IScript < NSObject>
- (BOOL)getIsDefault;
- (void)setIsDefault:(BOOL)value;
- (NSString *)getName;
- (void)setName:(NSString *)value;
- (NSString *)getCode;
- (void)setCode:(NSString *)value;
@end

// _IScript_H_
