//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Helpers/IScriptWriter.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _IScriptWriter_H_
#define _IScriptWriter_H_




@protocol IScriptWriter < NSObject >
- (void)close;
- (void)dispose;
- (void)flushStream;
- (void)writeWithBoolean:(BOOL)value;
- (void)writeWithByte:(char)value;
- (void)writeByteValWithByteArray:(NSData *)buffer;
- (void)writeBytesWithByteArray:(Byte *)buffer
                        withInt:(int)index
                        withInt:(int)count;
- (void)writeWithChar:(unichar)ch;
- (void)writeWithCharArray:(Byte *)chars;
- (void)writeWithDouble:(double)value;
- (void)writeWithShort:(short int)value;
- (void)writeIntValWithInt:(int)value;
- (void)writeWithLong:(long)value;
- (void)writeWithFloat:(float)value;
- (void)writeWithNSString:(NSString *)value;
- (NSData *)getBaseStream;
@end

#endif // _IScriptWriter_H_
