//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/ISuperClass.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ISuperClass_H_
#define _ISuperClass_H_



@protocol ISuperClass < NSObject >
- (NSMutableDictionary *)getMethods;
- (void)setMethodsWithJavaUtilHashMap:(NSMutableDictionary *)value;
@end

#endif // _ISuperClass_H_
