//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/ITemplates.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _ITemplates_H_
//#define _ITemplates_H_




@protocol ITemplates < NSObject>
@end

// _ITemplates_H_
