//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Parser/IToken.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _IToken_H_
#define _IToken_H_



@protocol IToken < NSObject >
- (int)getLineNumber;
- (int)getColumnNumber;
@end

#endif // _IToken_H_
