//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IValueAttribute.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _IValueAttribute_H_
//#define _IValueAttribute_H_


#import <Foundation/Foundation.h>

@protocol IValueAttribute < NSObject>
- (NSString *)getName;
- (NSString *)getValue;
@end

// _IValueAttribute_H_
