//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/IValue.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _IValue_H_
//#define _IValue_H_


#import "DataTypeConstants.h"
#import "Variant.h"
@protocol IValue < NSObject>
- (void)appendChunk:(id)data;
- (void)clear;
- (id)getChunk:(long)size;
- (NSMutableArray*)getAttributes;
- (NSNumber *)getIsDirty;
- (void)setIsDirty:(NSNumber *)value;
- (DataTypeConstants)getType;
- (void)setType:(DataTypeConstants)value;
- (Variant*)getvalue;
- (void)setvalue:(Variant*)value;
- (NSData *)getByteValue ;
- (void)setByteValue:(NSData *)value;
@end

// _IValue_H_
