//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/XmlControls/IXmlControl.java
//
//  Created by ashchauhan on 3/11/14.
//

#import <Foundation/Foundation.h>

@protocol IResponse;


@protocol IXmlControl < NSObject>

- (NSMutableArray*)getControls;
-(void)setControls:(NSMutableArray*)value;
-(BOOL)getHasControls;
- (NSMutableString*)getXmlBuilder;
- (void)setXmlBuilder:(NSMutableString *)value;
- (void)render:(id<IResponse>)response;

@end
