//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/IntermediateControls/IXmlInterControl.java
//
//  Created by ashchauhan on 4/1/14.
//

#import <Foundation/Foundation.h>

@class XmlControlMapper;
@class XmlInterPage;
@class Interview;
@class GDataXMLNode;
@class GDataXMLDocument;
@protocol IQuestion;
@protocol IResponse;

@protocol IXmlInterControl<NSObject>

- (NSMutableArray *)getControls;
- (void)setControls:(NSMutableArray *)value;
- (BOOL)getHasControls;
- (id<IQuestion>)getQuestion;
- (void)setQuestion:(id<IQuestion>)value;
-(Interview*)getInterview;
-(void)setInterview:(Interview*)interview;
-(GDataXMLNode*)getNode;
-(void)setNode:(GDataXMLNode*)value;
- (NSMutableString*)getXmlBuilder;
- (void)setXmlBuilder:(NSMutableString *)value;
-(GDataXMLDocument*)getXmlDoc;
-(void)setXmlDoc:(GDataXMLDocument*)value;
- (XmlControlMapper *)getMap;
- (void)setMap:(XmlControlMapper *)value;
- (id<IXmlInterControl>)getParent;
- (void)setParent:(id<IXmlInterControl>)value;
- (XmlInterPage *)getPage;
- (void)setPage:(XmlInterPage *)value;
- (NSString *)addPropertyWithName:(NSString *)name
                               withValue:(id)value
                          withBool:(BOOL)onlyIfNotEmpty;
- (NSMutableString *)buildControls;
-(void)render:(id<IResponse>)response;

@end
