//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/SupportingClasses/KeyNotFoundException.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _KeyNotFoundException_H_
#define _KeyNotFoundException_H_




#define KeyNotFoundException_serialVersionUID 1

@interface KeyNotFoundException : NSException {
}

- (id)init;
@end

#endif // _KeyNotFoundException_H_
