//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/Labels.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _Labels_H_
//#define _Labels_H_

#import "ILabels.h"


#import "CollectionObject.h"

@interface Labels : CollectionObject<ILabels> {
}

- (id<ILabel>)addNew:(NSString *)name withNSString:(NSString *)text;
- (id)init;
@end

// _Labels_H_
