//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/LabelInsert.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _LabelInsert_H_
//#define _LabelInsert_H_



#import "ILabelInsert.h"

@interface LabelInsert : NSObject < ILabelInsert > {
 @public
  NSString *_name;
  id _defaultproperty;
}

- (id)initWithNSString:(NSString *)name;
- (NSString *)getname;
- (void)setname:(NSString *)value;
- (id)getdefaultproperty;
- (void)setdefaultproperty:(id)value;

@end
