//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/LabelInserts.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _LabelInserts_H_
//#define _LabelInserts_H_



#import "CollectionObject.h"
#import "ILabelInserts.h"

@interface LabelInserts : CollectionObject<ILabelInserts>{
}
-(SortOrder)getOrder;
- (id)init;
@end

// _LabelInserts_H_
