//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/LanguageConstants.java
//
//  Created by chinthan on 1/15/14.
//

typedef enum {
  LanguageConstants_langILANGUAGE = 0,
  LanguageConstants_langSLANGUAGE = 1,
  LanguageConstants_langSENGLANGUAGE = 2,
  LanguageConstants_langSABBREVLANGNAME = 3,
  LanguageConstants_langSNATIVELANGNAME = 4,
  LanguageConstants_langICOUNTRY = 5,
  LanguageConstants_langSCOUNTRY = 6,
  LanguageConstants_langSENGCOUNTRY = 7,
  LanguageConstants_langSABBREVCTRYNAME = 8,
  LanguageConstants_langSNATIVECTRYNAME = 9,
  LanguageConstants_langIDEFAULTLANGUAGE = 10,
  LanguageConstants_langIDEFAULTCOUNTRY = 11,
  LanguageConstants_langIDEFAULTCODEPAGE = 12,
  LanguageConstants_langIDEFAULTANSICODEPAGE = 13,
  LanguageConstants_langSISO639LANGNAME = 14,
  LanguageConstants_langSISO3166CTRYNAME = 15,
} LanguageConstants;

