//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/Library.java
//
//  Created by nitin on 2/11/14.
//


#import "Variant.h"
#import "Categories.h"
#import "Interview.h"
#import "IQuestion.h"
#import "ICategory.h"

@interface Library : NSObject {
@public
    long long int __RandomSeed_;
}
+(NSArray*)cCatArray:(NSString*)value;
+(NSDate*)cDate:(NSString*)value;
+(NSString*)categorical:(NSArray*)values;
- (id)init;
- (long)getRandomSeed;
- (void)setRandomSeedWithLong:(long)value;
- (Variant *)abs:(id)value;
- (NSNumber *)ascw:(id)value;
-(NSNumber *) answercount:(id)answer;
- (Variant *)atn:(id)value;
- (BOOL)cbool:(id)value;
- (BOOL)cboolean:(id)value;
- (NSDate *)cdate:(id)value;
- (double)cdbl:(id)value;
- (long)clng:(id)value;
- (long)clong:(id)value;
- (NSString*)cstr:(id)value;
- (NSString*)ctext:(id)value;
- (NSString *)categorize:(id)value :(id)categorical;
- (NSString *)chrw:(id)value;
- (NSNumber *)cos:(id)value;
- (id)createobject:(NSString *)value;
- (NSDate *)date:(id)value;
- (Variant *)dateadd:(id)value;
- (NSNumber*)datediff:(NSDate *)date1 :(NSDate *)date2 :(NSString *)interval;
- (NSDate *)datenow;
- (NSDate *)datenow:(id)value;
- (Variant *)datepart:(id)value;
- (NSDate*)dateonly:(NSDate*)value;
- (NSNumber *)day:(NSDate *)value;
-(Variant *)definedcategories:(id)value;
- (NSString*)dump:(id)value;
- (Variant *)eval:(id)value;
- (Variant *)exp:(id)value;
- (Variant *)findWithId:(id)value;
- (NSString *)format:(id)value
        withNSString:(NSString *)style
            withLong:(long long int)width
            withLong:(long long int)locale;
- (NSString *)getanswer:(id)answer :(NSNumber *)index;
- (NSString *)hex:(id)value;
- (NSNumber *)hour:(id)value;
- (Variant *)iIfWithId:(id)value;
- (NSNumber *)instr:(id)value;
- (Variant *)inTWithId:(id)value;
- (Variant *)lbound:(id)value;
- (NSString *)lcase:(id)value;
- (NSString *)replace:(NSString *)value :(NSString *)what :(NSString *)with;
- (NSString *)ltrim:(id)value;
- (NSString *)left:(id)value :(long long int)length;
- (NSNumber *)len:(id)value;
- (Variant *)logWithId:(id)value;
-(NSString*) makestring:(id)values,...;
- (NSString *)midWithId:(id)value
                 withId:(id)start
                 withId:(id)length;
- (NSNumber *)minute:(id)value;
- (NSNumber *)month:(NSDate *)value;
- (NSString *)monthname:(id)value;
+(id)cleanobject:(id)value :(BOOL)butNotCategoricals;
- (NSDate *)now;
- (NSDate *)now:(NSString *)dateType;
- (NSString *)oct:(id)value;
- (Variant *)rGBWithId:(id)value;
- (NSString *)rtrim:(id)value;
- (id)ran:(id)value;
- (id)ran:(id)value :(id)items;
- (void)randomizeWithLong:(long long int)value;
- (Variant *)reDimWithId:(id)value;
- (NSString *)rightWithId:(id)value
                 withLong:(long long int)length;

- (id)rnd:(id)value;
- (id)rnd:(id)from :(id)to;

- (Variant *)rndwithid:(id)value;
- (double)roundWithDouble:(double)value;
- (NSNumber *)second:(id)value;
- (NSNumber *)sgn:(id)value;
- (Variant *)shellWithId:(id)value;
- (Variant *)shellExecuteWithId:(id)value;
- (Variant *)sinWithId:(id)value;
- (NSArray *)split:(NSString *)value :(NSString *)delimiter;
- (id)findItemWithId:(id)list
              withId:(id)key;
- (BOOL)isNullObjectWithId:(id)obj;
- (Variant *)sqrWithId:(id)value;
- (NSNumber *)sqrt:(id)value;
- (Variant *)tanWithId:(id)value;
- (Variant *)timeWithId:(id)value;
- (Variant *)timeNowWithId:(id)value;
- (NSString *)trim:(id)value;
- (Variant *)typeName:(id)value;
- (NSDate*)utctolocaltime:(id)value;
- (NSDate*)localtoutctime:(id)value;
- (Variant *)ubound:(id)value;
- (NSString *)ucase:(id)value;
- (Variant *)validateWithId:(id)value
                     withId:(id)min
                     withId:(id)max
                     withId:(id)express;
- (Variant *)validateWithId:(id)value
                     withId:(id)min
                     withId:(id)max
                     withId:(id)express
                     withId:(id)describe;
- (Variant *)varTyepNameWithId:(id)value;
- (Variant *)varTypeWithId:(id)value;
- (NSString *)weekdayname:(id)value;
+(BOOL)contains:(id)value withNSString:(NSString*) item;
+(BOOL)iscategorical:(NSString *)value;
+(NSString *)categoricaltostring:(NSMutableArray *)values;
-(Categories *)cCategorical:(id)value;
-(NSNumber *)containsSome:(id)value withAnswers:(id)answers;
-(NSNumber *)containsSome:(id)value withAnswers:(id)answers withlong:(long)min;
-(NSNumber *)containsSome:(id)value withAnswers:(id)answers withlongMin:(long)min withLongMax:(long)max;
-(NSNumber *)containsSome:(id)value withAnswers:(id)answers withlongMin:(long)min withLongMax:(long)max withBool:(BOOL)exactly;
-(NSNumber *)containsany:(id)value :(id)answers;
-(NSNumber *)containsany:(id)value :(id)answers :(BOOL)exactly;
-(NSNumber *)hasanswer:(id)value :(id)answers;
- (NSNumber *)year:(NSDate *)value;
- (NSNumber *)quarter:(NSDate *)date;
-(NSString *)displaycache:(Interview *)interview;
-(NSNumber *)isempty:(id)value;


@end

