//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/LineNumberTableAttribute.java
//
//  Created by chinthan on 12/2/13.
//




#import "Attribute.h"

@interface LineNumberTableAttribute : Attribute {
 @public
  NSMutableArray *__LineNumberInfo_;
}

- (id)initWithLineNumberTableArray:(NSMutableArray *)lineNumberInfo;
- (NSMutableArray *)getLineNumberInfo;
- (void)setLineNumberInfoWithLineNumberTableArray:(NSMutableArray *)value;
@end

