//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebControls/Literal.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebControlsLiteral_H_
//#define _OnePointPlayerWebWebControlsLiteral_H_

#import "QueryManager.h"

#import "IControl.h"
#import "Control.h"

@interface Literal :Control {
    NSString *__Text_;
}

- (id)initWithIControl:(id<IControl>)parent withText:(NSString*)literalText;
- (id)initWithIControl:(id<IControl>)parent
      withQueryManager:(QueryManager *)arguments;
-(NSString*)getText;
-(void)setText:(NSString*)value;
-(void)render:(id<IResponse>)response;
@end

//#endif // _OnePointPlayerWebWebControlsLiteral_H_
