//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/LocalVariableTable.java
//
//  Created by chinthan on 12/2/13.
//




@interface LocalVariableTable : NSObject {
 @public
  NSString *__Descriptor_;
  short int __Index_;
  short int __Length_;
  NSString *__Name_;
  short int __StartPc_;
}

- (NSString *)getDescriptor;
- (void)setDescriptorWithNSString:(NSString *)value;
- (short int)getIndex;
- (void)setIndexWithShort:(short int)value;
- (short int)getLength;
- (void)setLengthWithShort:(short int)value;
- (NSString *)getName;
- (void)setNameWithNSString:(NSString *)value;
- (short int)getStartPc;
- (void)setStartPcWithShort:(short int)value;
- (id)init;
@end


