//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/LocalVariableTableAttribute.java
//
//  Created by chinthan on 12/2/13.
//




#import "Attribute.h"

@interface LocalVariableTableAttribute : Attribute {
 @public
  NSMutableArray *__LocalVariableInfo_;
}

- (NSMutableArray *)getLocalVariableInfo;
- (void)setLocalVariableInfoWithLocalVariableTableArray:(NSMutableArray *)value;
- (id)initWithLocalVariableTableArray:(NSMutableArray *)localVariableInfo;
@end


