//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/BasicTypes/Long.java
//
//  Created by chinthan on 1/15/14.
//


@class Range;

@interface Long : NSObject {
 @public
  Range *__Range_;
}

- (Range *)getRange;
- (void)setRangeWithRange:(Range *)value;
- (id)init;
@end


