//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Meta/MdmElement.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _MdmElement_H_
#define _MdmElement_H_



@interface MdmElement : NSObject {
 @public
  NSString *__Name_;
  short int __Value_;
}

- (NSString *)getName;
- (void)setNameWithNSString:(NSString *)value;
- (short int)getValue;
- (void)setValueWithShort:(short int)value;
- (id)init;
@end


#endif // _MdmElement_H_
