//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Meta/MetaProperty.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _MetaProperty_H_
#define _MetaProperty_H_



@interface MetaProperty : NSObject {
}

- (id)init;
@end

#endif // _MetaProperty_H_
