//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Meta/MetaDocument.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _MetaDocument_H_
#define _MetaDocument_H_

@class OnePointClass;



@interface MetaDocument : NSObject {
 @public
  NSMutableArray *__Fields_;
}

- (NSMutableArray *)getFields;
- (void)setFieldsWithNSMutableArray:(NSMutableArray *)value;
+ (OnePointClass *)getClassDeclaration;
- (id)init;
@end


#endif // _MetaDocument_H_
