//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Meta/MetaField.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _MetaField_H_
#define _MetaField_H_

@class NSMutableArray;



@interface MetaField : NSObject {
 @public
  NSString *__Name_;
  NSString *__Label_;
  NSMutableArray *__Properties_;
}

- (NSString *)getName;
- (void)setNameWithNSString:(NSString *)value;
- (NSString *)getLabel;
- (void)setLabelWithNSString:(NSString *)value;
- (NSMutableArray *)getProperties;
- (void)setPropertiesWithNSMutableArray:(NSMutableArray *)value;
- (id)init;
@end


#endif // _MetaField_H_
