
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/Navigations.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _Navigations_H_
//#define _Navigations_H_

//@protocol  IQuestion;
#import "NavigationTypes.h"
#import "INavigations.h"
#import "INavigation.h"

@interface Navigations:NSObject<INavigation,INavigations> {
    
    id<IQuestion> _navlist;
    NavigationTypesEnum _default;
    NavigationTypesEnum _lastselected;
    NSMutableArray *_navigationsarray;
}
@property(nonatomic,strong)NSMutableArray *_navigationsarray;
- (id)init;
- (id)initWithIQuestion:(id<IQuestion>)navList;
- (id<INavigation>)get___idxWithNavigationTypes:(NavigationTypesEnum)navType;
- (void)set___idxWithNavigationTypes:(NavigationTypesEnum)navType withINavigation:(id<INavigation>)value;
- (id<INavigation>)get___idxwithnsstring:(NSString *)value;
- (id<INavigation>)add:(id)navType;
- (void)remove:(NavigationTypesEnum)navType;
- (void)buildInitialButtons;
- (void)addDefaultButton:(id<IQuestion>)field;
- (id<INavigation>)get___idxwithnavigations:(NSNumber *)navType;

@end
