//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/Navigation.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _Navigation_H_
//#define _Navigation_H_


#import "INavigation.h"
#import "NavigationTypes.h"
@interface Navigation: NSObject<INavigation> {

  id<IStyle> _style;
  id<ILabel> _label;
  id<ISavePoints> _targets;
    NavigationTypesEnum _type;
}

- (id)initWithId:(NavigationTypesEnum)type;
- (id)initWithIStyle:(id<IStyle>)style
     withISavePoints:(id<ISavePoints>)targets
                                      withNavigationTypes:(NavigationTypesEnum)type;
- (id)initWithIStyle:(id<IStyle>)style
     withISavePoints:(id<ISavePoints>)targets
                                      withNavigationTypes:(NavigationTypesEnum)type
          withILabel:(id<ILabel>)label;
- (id<ILabel>)getLabel;
- (void)setLabel:(id<ILabel>)value;
- (id<IStyle>)getStyle;
- (void)setStyle:(id<IStyle>)value;
- (id<ISavePoints>)getTargets;
- (void)setTargets:(id<ISavePoints>)value;

@end
