//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/IOM/NavigationTypes.java
//
//  Created by nitin on 1/15/14.
//

#import <Foundation/Foundation.h>

typedef enum {
  nvNone = 0,
  nvNext = 1,
  nvPrev = 2,
  nvFirst = 3,
  nvLast = 4,
  nvGoto = 5,
  nvStop = 6,
 
} NavigationTypesEnum;

@protocol NavigationTypes
-(NavigationTypesEnum)getEnum:(NSString *)value;
@end

@interface NavigationTypes :NSObject<NavigationTypes>{
    NavigationTypesEnum enumValue;
}

@property(nonatomic,assign) NavigationTypesEnum enumValue;


-(NavigationTypesEnum)getEnum;
-(void)setEnum:(NSString *)value;

-(NavigationTypesEnum)getEnum:(NSString *)value;
@end