//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/Helpers/Networker.java
//
//  Created by nitin on 2/12/14.
//

#ifndef _Networker_H_
#define _Networker_H_

@interface Networker : NSObject {
}

- (NSString *)getComputerName;
- (NSString *)getUserDomain;
- (NSString *)getUserName;
- (id)init;
@end

#endif // _Networker_H_
