//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/NextPage.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _NextPage_H_
//#define _NextPage_H_

@protocol ILabel;
@protocol ILabels;
@protocol INavigations;
@protocol IStyles;



#import "INextPage.h"

@interface NextPage : NSObject < INextPage > {
 @public
  id<ILabels> _banners;
  id<ILabels> _errors;
  id<INavigations> _navigations;
  NSString *_routingcontext;
  id<IStyles> _styles;
  id<ILabel> _title;
  id<ILabel> _label;
  NSString *_language;
  NSString *_layouttemplate;
  BOOL _mustanswer;
}

- (id<ILabels>)getBanners;
- (void)setBanners:(id<ILabels>)value;
- (id<ILabels>)getErrors;
- (void)setErrors:(id<ILabels>)value;
- (id<INavigations>)getNavigations;
- (void)setNavigations:(id<INavigations>)value;
- (NSString *)getRoutingContext;
- (void)setRoutingContext:(NSString *)value;
- (id<IStyles>)getStyles;
- (void)setStyles:(id<IStyles>)value;
- (id<ILabel>)getTitle;
- (void)setTitle:(id<ILabel>)value;
- (id<ILabel>)getLabel;
- (void)setLabel:(id<ILabel>)value;
- (NSString *)getLanguage;
- (void)setLanguage:(NSString *)value;
- (NSString *)getLayoutTemplate;
- (void)setLayoutTemplate:(NSString *)value;
- (BOOL)getMustAnswer;
- (void)setMustAnswer:(BOOL)value;
- (id)init;

@end
