//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/SupportingClasses/ObjectEquals.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ObjectEquals_H_
#define _ObjectEquals_H_

@class Executor;


#import "OPGMethod.h"

@interface ObjectEquals : OPGMethod {
}

- (id)init;
- (void)executeWithExecutor:(Executor *)executor;
@end

#endif // _ObjectEquals_H_
