//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/ObjectTypesConstants.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  ObjectTypesConstants_mtUnknown = 0,
  ObjectTypesConstants_mtVariable = 1,
  ObjectTypesConstants_mtArray = 2,
  ObjectTypesConstants_mtGrid = 3,
  ObjectTypesConstants_mtClass = 4,
  ObjectTypesConstants_mtElement = 5,
  ObjectTypesConstants_mtElements = 6,
  ObjectTypesConstants_mtLabel = 7,
  ObjectTypesConstants_mtField = 8,
  ObjectTypesConstants_mtHelperFields = 9,
  ObjectTypesConstants_mtFields = 10,
  ObjectTypesConstants_mtTypes = 11,
  ObjectTypesConstants_mtProperties = 12,
  ObjectTypesConstants_mtRouting = 13,
  ObjectTypesConstants_mtContexts = 14,
  ObjectTypesConstants_mtLanguages = 15,
  ObjectTypesConstants_mtLevelObject = 16,
  ObjectTypesConstants_mtVariableInstance = 17,
  ObjectTypesConstants_mtRoutingItem = 18,
  ObjectTypesConstants_mtCompound = 19,
  ObjectTypesConstants_mtElementInstance = 20,
  ObjectTypesConstants_mtElementInstances = 21,
  ObjectTypesConstants_mtLanguage = 22,
  ObjectTypesConstants_mtRoutingItems = 23,
  ObjectTypesConstants_mtRanges = 24,
  ObjectTypesConstants_mtCategories = 25,
  ObjectTypesConstants_mtCategoryMap = 26,
  ObjectTypesConstants_mtDataSources = 27,
  ObjectTypesConstants_mtDocument = 28,
  ObjectTypesConstants_mtVersion = 29,
  ObjectTypesConstants_mtVersions = 30,
  ObjectTypesConstants_mtVariables = 31,
  ObjectTypesConstants_mtDataSource = 32,
  ObjectTypesConstants_mtAliasMap = 33,
  ObjectTypesConstants_mtIndexElement = 34,
  ObjectTypesConstants_mtIndicesElements = 35,
  ObjectTypesConstants_mtPages = 36,
  ObjectTypesConstants_mtParameters = 37,
  ObjectTypesConstants_mtPage = 38,
  ObjectTypesConstants_mtItems = 39,
  ObjectTypesConstants_mtContext = 40,
  ObjectTypesConstants_mtContextAlternatives = 41,
  ObjectTypesConstants_mtElementList = 42,
  ObjectTypesConstants_mtGoto = 43,
  ObjectTypesConstants_mtTemplate = 44,
  ObjectTypesConstants_mtTemplates = 45,
  ObjectTypesConstants_mtStyle = 46,
  ObjectTypesConstants_mtNote = 47,
  ObjectTypesConstants_mtNotes = 48,
  ObjectTypesConstants_mtIfBlock = 49,
  ObjectTypesConstants_mtConditionalRouting = 50,
  ObjectTypesConstants_mtDBElements = 51,
  ObjectTypesConstants_mtDBQuestionDataProvider = 52,
} ObjectTypesConstants;


