//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/OffPathDataModes.java
//
//  Created by chinthan on 1/15/14.
//

typedef enum {
  OffPathDataModes_dmClearOnExit = 0,
  OffPathDataModes_dmClearOnComplete = 1,
  OffPathDataModes_dmKeep = 2,
  OffPathDataModes___dummyEnum__0 = 3,
  OffPathDataModes_dmClearOnNavigateBack = 4,
} OffPathDataModes;


