//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/OnePointClass.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _OnePointClass_H_
#define _OnePointClass_H_

@class ExceptionTable;
@class LineNumberTable;
@class SuperClass;
@class Workspace;



@interface OnePointClass : NSObject {
 @public
  NSMutableArray *__Constants_;
  ExceptionTable *__Exceptions_;
  NSMutableDictionary *__FieldNames_;
  NSMutableDictionary *__InterfaceMethods_;
  LineNumberTable *__LineNumbers_;
  NSMutableDictionary *__MethodNames_;
  NSMutableArray *__Methods_;
  NSString *__SourceFile_;
  NSMutableDictionary *__StaticFieldNames_;
  NSMutableArray *__StaticFields_;
  SuperClass *__Super_;
}

- (id)init;
- (id)initWithSuperClass:(SuperClass *)superClass
                                                  withInt:(int)constantCount
         withMethodArray:(NSMutableArray *)method
                                        withNSStringArray:(NSMutableArray *)methodNames
                                        withNSObjectArray:(NSMutableArray *)staticFields
                                        withNSStringArray:(NSMutableArray *)staticFieldNames
                                        withNSStringArray:(NSMutableArray *)fieldNames;
- (id)initWithWorkspace:(Workspace *)environment;
- (NSMutableArray *)getConstants;
- (void)setConstantsWithNSObjectArray:(NSMutableArray *)value;
- (ExceptionTable *)getExceptions;
- (void)setExceptionsWithExceptionTable:(ExceptionTable *)value;
- (NSMutableDictionary *)getFieldNames;
- (void)setFieldNamesWithJavaUtilHashMap:(NSMutableDictionary *)value;
- (NSMutableDictionary *)getInterfaceMethods;
- (void)setInterfaceMethodsWithJavaUtilHashMap:(NSMutableDictionary *)value;
- (LineNumberTable *)getLineNumbers;
- (void)setLineNumbersWithLineNumberTable:(LineNumberTable *)value;
- (NSMutableDictionary *)getMethodNames;
- (void)setMethodNamesWithJavaUtilHashMap:(NSMutableDictionary *)value;
- (NSMutableArray *)getMethods;
- (void)setMethodsWithMethodArray:(NSMutableArray *)value;
- (NSString *)getSourceFile;
- (void)setSourceFileWithNSString:(NSString *)value;
- (NSMutableDictionary *)getStaticFieldNames;
- (void)setStaticFieldNamesWithJavaUtilHashMap:(NSMutableDictionary *)value;
- (NSMutableArray *)getStaticFields;
- (void)setStaticFieldsWithNSObjectArray:(NSMutableArray *)value;
- (SuperClass *)getSuper;
- (void)setSuperWithSuperClass:(SuperClass *)value;
+ (int)getParametersSizeWithNSString:(NSString *)descriptor
                             withInt:(int)size2;
- (void)loadConstantsWithWorkspace:(Workspace *)environment;
- (void)loadFieldsWithWorkspace:(Workspace *)environment;
- (void)loadInterfacesWithWorkspace:(Workspace *)environment;
- (void)loadMethodsWithWorkspace:(Workspace *)environment;
- (int) indexOfString:(NSString *)mainText withKey:(NSString *)text;
- (void)copyAllFieldsTo:(OnePointClass *)other;
@end



#endif // _OnePointClass_H_
