//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/OpenConstants.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  OpenConstants___dummyEnum__0 = 0,
  OpenConstants_oREAD = 1,
  OpenConstants_oREADWRITE = 2,
  OpenConstants_oNOSAVE = 3,
} OpenConstants;



