//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Parser/Ast/Operator.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
   Operator_Add = 0,
   Operator_Subtract = 1,
   Operator_Multiply = 2,
   Operator_Divide = 3,
   Operator_Equal = 4,
   Operator_LessThan = 5,
   Operator_GreaterThan = 6,
   Operator_Or = 7,
   Operator_And = 8,
   Operator_NotEqual = 9,
   Operator_GreaterThanOrEqualTo = 10,
   Operator_Group = 11,
   Operator_LessThanOrEqualTo = 12,
   Operator_Assignment = 13,
   Operator_SubField = 14,
   Operator_Negative = 15,
   Operator_Unknown = 16,
    Operator_Not = 17,
    Operator_Is = 18,
    Operator_Pointer = 19,
    Operator_Mod = 20,


}  Operator;


