//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/Category.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _Category_H_
//#define _Category_H_



#import "CategoryTypes.h"
#import "ICategory.h"
@class Interview;

@protocol IProperties;
@interface OPGCategory : NSObject<ICategory> {
    
  id<IQuestion> _parentquestion;
  BOOL _iscode;
  long  _attributes;
  id<ICategories> _categories;
  NSString *_fullname;
  int _index;
  NSString *_keycode;
  id<ILabel> _label;
  NSString *_name;
  id<IQuestion> _otherquestion;
  id<ICategory> _parent;
  id<IProperties> _properties;
  id<IStyle> _style;
  Variant *_factor;
  CategoryTypes _categorytype;
    BOOL _canfilter;
    Variant *_filter;
    OrderConstants _order;
    BOOL _useNamespace;    
}

- (id)initWithInterview:(Interview *)ainterview;
- (id)initWithInterview:(Interview *)ainterview withName:(NSString *)name;
- (id)initWithInterview:(Interview *)ainterview withIQuestion:(id<IQuestion>)question
          withNSString:(NSString *)name;
-(id)initWithSerializationInfo:(id)info withStreamingContext:(id)context;
- (id)initWithInterview:(Interview *)interview
          withIQuestion:(id<IQuestion>)question
          withICategory:(id<ICategory>)category
           withNSString:(id)jsonString
            withBoolean:(BOOL)isSubList withOrder:(NSString*)order withLabel:(NSString*)label withBool:(BOOL)fix;

-(void)setCategoryType:(CategoryTypes)value;
-(CategoryTypes)getCategoryType;
- (long)getAttributes;
- (void)setAttributes:(long)value;
- (id<ICategories>)getcategories;
- (void)setcategories:(id<ICategories>)value;
- (int)getCount;
- (NSString *)getFullName;
- (void)setFullName:(NSString *)value;
- (int)getIndex;
- (void)setIndex:(int)value;
- (NSString *)getKeyCode;
- (void)setKeyCode:(NSString *)value;
- (id<ILabel>)getLabel;
- (void)setLabel:(id<ILabel>)value;
- (NSString *)getName;
- (void)setName:(NSString *)value;
- (id<IQuestion>)getOtherQuestion;
- (void)setOtherQuestion:(id<IQuestion>)value;
- (id<ICategory>)getParent;
- (void)setParent:(id<ICategory>)value;
- (id<IProperties>)getProperties;
- (void)setProperties:(id<IProperties>)value;
- (id<IStyle>)getStyle;
- (void)setStyle:(id<IStyle>)value;
- (BOOL)getIsCode;
- (BOOL)getIsOther;
- (BOOL)getIsExclusive;
- (void)setIsExclusive:(BOOL)value;
- (void)setControlType;
- (void)processProperties:(Interview *)interview withId:(id)json;

@end
