//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/Label.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _Label_H_
//#define _Label_H_
#import <Foundation/Foundation.h>
#import "ILabel.h"
@class Interview;
@protocol IFontStyle;
@protocol ILabelInserts;
@protocol IStyle;
@protocol IQuestions;
@protocol IInterviewSampleRecord;


@interface OPGLabel:NSObject <ILabel> {
  NSString *_labeltext;
  id<ILabelInserts> _inserts;
  NSString *_name;
  id<IStyle> _style;
    id _defaultproperty;
    id _owner;
    Interview *_interview;
     id<IQuestion>  _question;
     id<IQuestions>  _questions;
}

@property(nonatomic,retain)id _defaultproperty;
- (id)init;
- (id)initWithInterview:(Interview *)ainterview;
- (id)initWithInterview:(Interview *)ainterview withString:(NSString *)atext;

- (id)initWithNSString:(NSString *)text;
- (id)initWithNSString:(NSString *)text withIStyle:(id<IStyle>)style;
- (id)initWithInterview:(Interview *)ainterview withName:(NSString *)aname
           withNSString:(NSString *)atext;

- (id)initWithInterview:(Interview *)ainterview withName:(NSString *)aname
           withNSString:(NSString *)atext withIStyle:(id<IStyle>)astyle;
- (id)initWithInterview:(Interview *)ainterview
          withIQuestion:(id<IQuestion> )aquestion withNSString:(NSString *)atext;
- (id<ILabelInserts>)getinserts;
- (void)setinserts:(id<ILabelInserts>)value;
- (NSString *)getName;
- (void)setName:(NSString *)value;
- (id<IStyle>)getStyle;
- (void)setStyle:(id<IStyle>)value;
- (id<IFontStyle>)getFont;
- (void)setFont:(id<IFontStyle>)value;
- (id)getdefaultproperty;
- (void)setdefaultproperty:(id)value;
- (NSString *)description;
- (NSString *)toString:(Interview *)interview;
- (id<ILabel>)clone;
+ (NSString *)seekEnd:(NSString *)text;
- (NSString *)description:(Interview *)interview withQuestion:(id<IQuestion>)question;

@end
