//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/Style.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _Style_H_
//#define _Style_H_

@protocol IAudioStyle;
@protocol IFontStyle;
@protocol IStyle;
@protocol ICellStyle;
@protocol ISliderStyle;
#import "CursorTypes.h"
#import "Alignments.h"
#import "ElementAlignments.h"
#import "ImagePositions.h"
#import "Orientations.h"
#import "VerticalAlignments.h"
#import "ControlTypes.h"
#import "ControlStyle.h"
#import "IMediaStyle.h"

@interface OPGStyle : NSObject<IStyle,IFontStyle> {
 @public
  id<IAudioStyle> _audio;
  NSString *_bgcolor;
  id<ICellStyle> _cell;
    AlignmentsEnm _align;
  NSString *_color;
  long long int _columns;
  id<IControlStyle> _control;
  id<IFontStyle> _font;
  NSString *_height;
  BOOL _hidden;
  NSString *_image;
  long long int _indent;
  long long int _rows;
  BOOL _usecascadestyles;
  NSString *_width;
  long long int _zindex;
  BOOL _isempty;
  id _parent;
  CursorTypes _cursor;
    ElementAlignments _elementalign;
    ImagePositions _imageposition;
    Orientations _orientation;
    VerticalAlignmentsEnm _verticalalign;
    id<IMediaStyle> _media;
    id<ISliderStyle> _slider;
    NSString *_mask;
    NSString *_placeholder;
    

}

- (id)init;
- (id)initWithIStyle:(id<IStyle>)parent;
- (id)initWithId:(id)json;
- (id)initWithIAudioStyle:(id<IAudioStyle>)audio withICellStyle:(id<ICellStyle>)cell withIControlStyle:(id<IControlStyle>)control withIFontStyle:(id<IFontStyle>)font;
- (id)initWithIAudioStyle:(id<IAudioStyle>)audio withICellStyle:(id<ICellStyle>)cell withIControlStyle:(id<IControlStyle>)control withIFontStyle:(id<IFontStyle>)font  withIStyle:(id<IStyle>)parent;

- (id<IAudioStyle>)getAudio;
- (void)setAudio:(id<IAudioStyle>)value;
- (NSString *)getBgcolor;
- (void)setBgcolor:(NSString *)value;
- (id)getCell;
- (void)setCell:(id)value;
- (NSString *)getColor;
- (void)setColor:(NSString *)value;
- (long long int)getColumns;
- (void)setColumns:(long long int)value;
- (id<IControlStyle>)getControl;
- (void)setControl:(id<IControlStyle>)value;
- (id<IFontStyle>)getFont;
- (void)setFont:(id<IFontStyle>)value;
- (NSString *)getHeight;
- (void)setHeight:(NSString *)value;
- (BOOL)getHidden;
- (void)setHidden:(BOOL)value;
- (NSString *)getImage;
- (void)setImage:(NSString *)value;
- (long long int)getIndent;
- (void)setIndent:(long long int)value;
- (BOOL)getIsEmpty;
- (void)setIsEmpty:(BOOL)value;
- (id)getParent;
- (void)setParent:(id)value;
- (long long int)getRows;
- (void)setRows:(long long int)value;
- (BOOL)getUseCascadeStyles;
- (void)setUseCascadeStyles:(BOOL)value;
- (NSString *)getWidth;
- (void)setWidth:(NSString *)value;
- (long long int)getZIndex;
- (void)setZIndex:(long long int)value;
- (void)copyTo:(id<IStyle>)destination;
- (void)copyTo:(id<IStyle>)destination withBoolean:(BOOL)allCascadedStyles;
-(NSString *)getPlaceholder;
-(void)setPlaceholder:(NSString *)value;
- (void)processProperties:(id)json;
- (void)processIndividualProperties:(id)category;
- (void)processControlType:(NSString *)controlType;
- (void)prrocessProperty:(id)json;
-(Orientations) getOrientation;
-(void)setOrientation:(Orientations) value ;
-(VerticalAlignmentsEnm) getVerticalAlign;
-(void)setVerticalAlign:(VerticalAlignmentsEnm)value;
-(void)setCursor:(CursorTypes)value;
-(CursorTypes)getCursor;
-(ImagePositions) getImagePosition;
-(void)setImagePosition:(ImagePositions) value;
- (void)setElementAlign:(ElementAlignments)value;
- (ElementAlignments)getElementAlign;
- (AlignmentsEnm)getAlign;
- (void)setAlign:(AlignmentsEnm)value;
-(id<ISliderStyle>) getSlider ;
-(void) setSlider:(id<ISliderStyle>)value;
@end
