//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/SupportingClasses/OpLibrary.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _OpLibrary_H_
#define _OpLibrary_H_

@class Executor;


#import "SuperClass.h"

@interface OpLibrary : SuperClass {
}

+ (NSString *)Name;
- (id)init;
- (void)askWithExecutor:(Executor *)executor;
- (void)equalToStringWithExecutor:(Executor *)executor;
@end

#endif // _OpLibrary_H_
