//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/SupportingClasses/OpMetaData.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _OpMetaData_H_
#define _OpMetaData_H_

@class Executor;


#import "SuperClass.h"

@interface OpMetaData : SuperClass {
}

+ (NSString *)Name;
- (id)init;
- (void)stringToStringWithExecutor:(Executor *)executor;
- (void)intToStringWithExecutor:(Executor *)executor;
@end

#endif // _OpMetaData_H_
