//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/SupportingClasses/OpVariant.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _OpVariant_H_
#define _OpVariant_H_

@class Executor;


#import "SuperClass.h"

@interface OpVariant : SuperClass {
}

+ (NSString *)Name;
- (id)init;
- (NSString *)notEqualToWithExecutor:(Executor *)executor;
- (NSString *)equalToIntegerWithExecutor:(Executor *)executor;
- (NSString *)equalToFloatWithExecutor:(Executor *)executor;
- (NSString *)equalToStringWithExecutor:(Executor *)executor;
- (NSString *)intToStringWithExecutor:(Executor *)executor;
- (NSString *)setValueIntegerWithExecutor:(Executor *)executor;
- (NSString *)setValueStringWithExecutor:(Executor *)executor;
- (NSString *)setValueVariantWithExecutor:(Executor *)executor;
- (NSString *)addWithExecutor:(Executor *)executor;
- (NSString *)subtractWithExecutor:(Executor *)executor;
- (NSString *)divideWithExecutor:(Executor *)executor;
- (NSString *)multiplyWithExecutor:(Executor *)executor;
- (NSString *)addStringWithExecutor:(Executor *)executor;
@end

#endif // _OpVariant_H_
