//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/OrderConstants.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  OrderConstants_oNormal = 0,
  OrderConstants_oRandomize = 1,
  OrderConstants_oRotate = 2,
  OrderConstants_oReverse = 3,
  OrderConstants_oAscending = 4,
  OrderConstants_oDescending = 5,
  OrderConstants_oCustom = 6,
} OrderConstants;


