//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/Orientations.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  Orientations_orDefault = 0,
  Orientations_orRow = 1,
  Orientations_orColumn = 2,
} Orientations;


