//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/UI/Page.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _Page_H_
//#define _Page_H_

#import "TemplateManager.h"
#import  "QueryManager.h"
#import  "WebApplication.h"
#import  "XmlPage.h"
#import  "IControl.h"
#import "Control.h"
#import "XmlIntermediate.h"
#import "OPGScanner.h"
@interface Page :Control {
 @public
  id<IControl> __TemplateControl_;
  id<IControl> __Body_;
  id<IControl> __Form_;
  id<IControl> __Header_;
  WebApplication *__Application_;
  TemplateManager *__Templates_;
  BOOL __IncludeCssNames_;
  XmlPage *__XmlPage_;
  XmlIntermediate *__Intermediate;
  id<IControl> __MrPage;
    int __RenderType;
    id<IQuestion> __Question_;
    id<IQuestions> __Questions_;
   // OPGScanner *scanner;
    NSMutableArray *__Banners;
    NSMutableArray *__QuestionsIndex;
    NSDate *start;
    NSDate *end;
    
    NSMutableArray *__RenderedBanners;
}


- (id)initWithWebApplication:(id<IApplication>)application;
- (id<IControl>)getTemplateControl;
- (void)setTemplateControl:(id<IControl>)value;
- (id<IControl>)getBody;
- (void)setBody:(id<IControl>)value;
- (id<IControl>)getForm;
- (void)setForm:(id<IControl>)value;
- (id<IControl>)getHeader;
- (void)setHeader:(id<IControl>)value;
- (WebApplication *)getApplication;
- (void)setApplication:(WebApplication *)value;
- (TemplateManager *)getTemplates;
- (void)setTemplates:(TemplateManager *)value;
- (BOOL)getIncludeCssNames;
- (void)setIncludeCssNames:(BOOL)value;
- (XmlPage *)getXmlPage;
-(XmlIntermediate*) getIntermediate;
-(void)setIntermediate:(XmlIntermediate*) value ;
-(id<IControl>) getMrPage;
-(void)setMrPage:(id<IControl>) value;
-(id<IQuestion>)getQuestion;
-(void)setQuestion:(id<IQuestion>)question;
-(id<IQuestions>)getQuestions;
-(void)setQuestions:(id<IQuestions>)value;
- (void)setXmlPage:(XmlPage *)value;
-(void)setRenderType:(int) value;
-(int)getRenderType ;
-(NSMutableArray*) getBanners;
-(void)setBanners:(NSMutableArray*) value;
- (void)checkPageProperties:(QueryManager *)arguments;
-(NSMutableArray*)getQuestionsIndex ;
-(void) setQuestionsIndex:(NSMutableArray*) value ;
- (void)createControls;
-(void)createControls:(id<IQuestion>) question;
-(void)createControls:(id<IQuestion>) question templateManager:(TemplateManager*)templates;
-(void)setRenderedBanners:(NSMutableArray*)value;
-(NSMutableArray*)getRenderedBanners;
@end
//#endif // _Page_H_
