//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Parser/Parser.java
//
//  Created by nitin on 3/24/14.
//


@class Scanner;
@class Token;
#import "AstIdentifier.h"
@class Errors;
#import "IAstNode.h"
#include "IParser.h"
#import "Operator.h"

#define Parser__EOF 0
#define Parser__NL 1
#define Parser__ident 2
#define Parser__label 3
#define Parser__integerConstant 4
#define Parser__realConstant 5
#define Parser__characterConstant 6
#define Parser__stringConstant 7
#define Parser__specialstringConstant 8
#define Parser__and 9
#define Parser__assignment 10
#define Parser__colon 11
#define Parser__comma 12
#define Parser__decrement 13
#define Parser__divide 14
#define Parser__dot 15
#define Parser__conditionalequality 16
#define Parser__greater 17
#define Parser__greaterorequals 18
#define Parser__increment 19
//#define Parser__leftbrace 20
#define Parser__leftbrack 20
#define Parser__leftpar 21
#define Parser__lessthan 22
#define Parser__lessoreqals 23
#define Parser__minus 24
#define Parser__notequals 25
#define Parser__not 26
#define Parser__plus 27
#define Parser__rightbrace 28
#define Parser__rightbrack 29
#define Parser__rightpar 30
#define Parser__semicolon 31
#define Parser__times 32
#define Parser__hat 33
#define Parser__Dim 34
#define Parser__As 35

//#define Parser__text 12
#define Parser_maxT 52
#define Parser_minErrDist 2
#define Parser_x FALSE
#define Parser_T TRUE


@interface Parser : NSObject < IParser > {
 @public
    BOOL _Condition;
    BOOL __IsSet;
  Token *t_;
  Token *la_;
  int errDist_;
  Scanner *scanner_;
  id<IAstNode> RootNode_;
  Errors *errors;
   @private
    Handler *__Handler;
    SymbolTable *__Symbols;
    
}

+ (int)_EOF;
+ (int)_NL;
+ (int)_ident;
+ (int)_label;
+ (int)_integerConstant;
+ (int)_realConstant;
+ (int)_characterConstant;
+ (int)_stringConstant;
+ (int)_specialstringConstant;
+ (int)_routingdata;
+ (int)_long;
+ (int)_double;
+ (int)_text;
+ (int)_date;
+ (int)_boolean;
+ (int)_categorical;
+ (int)_define;
+ (int)_info;
+ (int)_loop;
+ (int)_grid;
+ (int)_compound;
+ (int)_block;
+ (int)_page;
+ (int)_analysis;
+ (int)_question;
+ (int)_qc;
+ (int)_paper;
+ (int)_cardcol;
+ (int)_mobile;
+ (int)_and;
+ (int)_assignment;
+ (int)_colon;
+ (int)_comma;
+ (int)_decrement;
+ (int)_divide;
+ (int)_dot;
+ (int)_conditionalequality;
+ (int)_greater;
+ (int)_greaterorequals;
+ (int)_increment;
+ (int)_leftbrace;
+ (int)_leftbrack;
+ (int)_leftpar;
+ (int)_lessthan;
+ (int)_lessoreqals;
+ (int)_minus;
+ (int)_notequals;
+ (int)_not;
+ (int)_plus;
+ (int)_rightbrace;
+ (int)_rightbrack;
+ (int)_rightpar;
+ (int)_semicolon;
+ (int)_times;
+ (int)_hat;
+ (int)_Dim;
+ (int)_As;
+ (int)maxT;
+ (BOOL)T;
+ (BOOL)x;
+ (int)minErrDist;
+ (NSMutableArray *)set;

-(SymbolTable *)getSymbols;
-(void)setSymbols:(SymbolTable *)value;
-(Handler *)getHandler;
-(void)setHandler:(Handler *)value;
-(BOOL)getCondition;
-(void)setCondition:(BOOL)value;
-(BOOL)getIsSet;
-(void)setIsSet:(BOOL)value;

- (Token *)PeekWithInt:(int)n;
- (id)initWithScanner:(Scanner *)scanner;
- (void)SynErrWithInt:(int)n;
- (void)SemErrWithNSString:(NSString *)msg;
- (void)Get;
- (void)ExpectWithInt:(int)n;
- (BOOL)StartOfWithInt:(int)s;
- (void)ExpectWeakWithInt:(int)n
                  withInt:(int)follow;
- (BOOL)WeakSeparatorWithInt:(int)n
                     withInt:(int)syFol
                     withInt:(int)repFol;
- (void)Evaluate;
- (id<IAstNode>)ExpressionWithBoolean:(BOOL)isCond;
- (id<IAstNode>)AndExpressionWithBoolean:(BOOL)isCond;
- (id<IAstNode>)EqualityExpressionWithBoolean:(BOOL)isCond;
- (id<IAstNode>)RelativeExpressionWithBoolean:(BOOL)isCond;
- (Operator)EqualityOperatorWithBoolean:(BOOL)isCond;
- (id<IAstNode>)AddExpressionWithBoolean:(BOOL)isCond;
- (Operator)RelativeOperator;
- (id<IAstNode>)TermExpressionWithBoolean:(BOOL)isCond;
- (Operator)AddOperator;
- (id<IAstNode>)FactorWithBoolean:(BOOL)isCond;
- (Operator)FactorOperator;
- (NSString *)Identifier;
//- (NSMutableArray *)ArgumentListWithBoolean:(BOOL)isCond;
- (void)SubFactorWithAstIdentifier:(AstIdentifier *)e withBoolean:(BOOL)isCond;
- (id<IAstNode>)Constant;
- (NSString *)SubIdentifier;
- (void)Parse;
@end



