//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebControls/Label.java
//
//  Created by ashchauhan on 3/11/14.
//


@class QueryManager;
@protocol IControl;


#import "Control.h"

@interface PlayerLabel : Control {
}

- (id)initWithIControl:(id<IControl>)parent;
- (id)initWithIControl:(id<IControl>)parent
      withQueryManager:(QueryManager *)arguments;
@end

