//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebControls/ProgressBar.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebControlsProgressBar_H_
//#define _OnePointPlayerWebWebControlsProgressBar_H_

#import "QueryManager.h"
#import "Control.h"


#import "Control.h"
#import "ProgressOrientation.h"
#import "ProgressDisplay.h"
#import "WebResponse.h"
@interface ProgressBar : Control {
    NSString *__Colour;
    ProgressOrientation __Orientation;
    ProgressDisplay __Progress;
    BOOL __ShowBar;
    BOOL __ShowCounts;
    NSString *__Type;
}

- (id)initWithIControl:(id<IControl>)parent
      withQueryManager:(QueryManager *)arguments;
@end

//#endif // _OnePointPlayerWebWebControlsProgressBar_H_
