//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/Properties.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _Properties_H_
//#define _Properties_H_



#import "IProperties.h"
#import "CollectionObject.h"
@interface  Properties :CollectionObject <IProperties> {
    NSString* _name;
}

- (id)init;
- (id)initWithNSString:(NSString *)name;
-(id<IProperty>)getByIndex:(int)index;

@end

// _Properties_H_
