//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/QuestionTypes.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  QuestionTypes_qtSimple = 0,
  QuestionTypes_qtLoopCategorical = 1,
  QuestionTypes_qtLoopNumeric = 2,
  QuestionTypes_qtCompound = 3,
  QuestionTypes_qtBlock = 4,
  QuestionTypes_qtPage = 5,
  QuestionTypes_qtDerived = 6,
} QuestionTypes;


