//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/QuestionStyle.java
//
//  Created by ashchauhan on 6/20/14.
//

#import "ICategoryStyles.h"
#import "IStyle.h"
#import "IStyles.h"
#import "IQuestionStyle.h"

@interface QuestionStyle : NSObject <IQuestionStyle> {
 @public
  id<ICategoryStyles> _categories;
  id<IStyles> _labels;
  id<IStyle> _style;
}

- (id)initWithICategoryStyles:(id<ICategoryStyles>)categories
                  withIStyles:(id<IStyles>)labels
                   withIStyle:(id<IStyle>)style;
- (id<ICategoryStyles>)getCategories;
- (void)setCategories:(id<ICategoryStyles>)value;
- (id<IStyles>)getLabels;
- (void)setLabels:(id<IStyles>)value;
- (id<IStyle>)getStyle;
- (void)setStyle:(id<IStyle>)value;

@end
