//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/QuestionInfo.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _QuestionInfo_H_
//#define _QuestionInfo_H_



#import "IQuestionInfo.h"

@interface  

QuestionInfo : NSObject < IQuestionInfo > {
 @public
  long long int _answercount;
  long long int _askcount;
  long long int _errorcount;
  BOOL _isonpath;
  id _offpathcodedresponse;
  id _offpathresponse;
  long long int _onpathanswercount;
}

- (long long int)getAnswerCount;
- (void)setAnswerCount:(long long int)value;
- (long long int)getAskCount;
- (void)setAskCount:(long long int)value;
- (long long int)getErrorCount;
- (void)setErrorCount:(long long int)value;
- (BOOL)getIsOnPath;
- (void)setIsOnPath:(BOOL)value;
- (id)getOffPathCodedResponse;
- (void)setOffPathCodedResponse:(id)value;
- (id)getOffPathResponse;
- (void)setOffPathResponse:(id)value;
- (long long int)getOnPathAnswerCount;
- (void)setOnPathAnswerCount:(long long int)value;
- (id)init;

@end
