//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/QuestionStyles.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _QuestionStyles_H_
//#define _QuestionStyles_H_


#import "IQuestionStyles.h"
#import "CollectionObject.h"
@interface QuestionStyles : CollectionObject<IQuestionStyles> {
    
}
- (void)add:(int)key withIQuestionStyle:(id<IQuestionStyle>)value;
- (id)init;
@end

// _QuestionStyles_H_
