//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/BasicTypes/Range.java
//
//  Created by chinthan on 1/15/14.
//

#import "IRange.h"
#import <Foundation/Foundation.h>

@interface Range : NSObject<IRange> {
    
 @public
  id __From_;
  id __To_;
  id __Specific_;
  BOOL __Exclude_;
  BOOL __Thru_;
    id __Step;
}

- (id)getFrom;
- (void)setFrom:(id)value;
- (id)getTo;
- (void)setTo:(id)value;
- (id)getSpecific;
- (void)setSpecific:(id)value;
- (BOOL)getExclude;
- (void)setExclude:(BOOL)value;
- (BOOL)getThru;
- (void)setThru:(BOOL)value;
- (id)init;
@end

