//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/RecordLibrary/RecordHelpers/RecordElementType.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _RecordElementType_H_
#define _RecordElementType_H_



typedef enum {
  RecordElementType___dummyEnum__0 = 0,
  RecordElementType_String = 1,
  RecordElementType_Byte = 2,
  RecordElementType_Int8 = 3,
  RecordElementType_Int16 = 4,
  RecordElementType_Int32 = 5,
  RecordElementType_Int64 = 6,
  RecordElementType_Float = 7,
  RecordElementType_Double = 8,
  RecordElementType_Bit = 9,
} RecordElementType;


#endif // _RecordElementType_H_
