//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/Helpers/Reflector.java
//
//  Created by nitin on 2/12/14.
//

#import <objc/runtime.h>
#import "Handler.h"

@interface Reflector : NSObject {
 @public
  NSMutableArray *parameters_;
  NSMutableArray *types_;
}

- (id)initWithNSMutableArray:(NSMutableArray *)arguments;
+ (BOOL)isArrayWithId:(id)obj;
+ (id)getPropertyWithId:(id)obj
           withNSString:(NSString *)name;
+ (objc_property_t)getItemPropertyWithId:(id)obj;
+ (id)getDefaultPropertyWithId:(id)obj
                        withId:(id)prop;
+ (id)getPropertyValue:(Handler *)handler withID:(id)obj
          withNSString:(NSString *)name;
+ (id)findFieldWithId:(id)obj
              withId:(id)key;
+ (id)findItemWithId:(id)obj
              withId:(id)key;
- (SEL)findMethodWithId:(id)obj
          withNSString:(NSString *)name;
- (id)invokeCollectionWithId:(id)obj
                withNSString:(NSString *)name;
- (id)invokeMethodWithId:(id)obj
            withNSString:(NSString *)name;
+ (id)searchDefaultPropertyWithId:(NSObject **)value;
+(void)setValue:(NSString *)property withObject:(id)obj withValue:(id)value;
- (SEL)findMethodWithId:(id)obj
           withNSString:(NSString *)name withArguments:(NSMutableArray*)list;

@end

