//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/Response.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _Response_H_
//#define _Response_H_
#import <Foundation/Foundation.h>
@protocol IQuestion;
@protocol IResponses;
@protocol IValue;
#import "Interview.h"


@class Variant;
#import "Value.h"
#import "IOMIResponse.h"
#import "Results.h"
@interface Response : NSObject < IOMIResponse > {
 @public
    NSString *_coded;
    DataTypeConstants _datatype;
    id _defaultproperty;
    id _initial;
    NSNumber *_isdirty;
    NSString *_name;
    id<IResponses> _other;
    id<IValue> _valueobj;
    id<IQuestion> _question;
    Variant *_responsevalue;
    NSDate *_answered;
    NSDate *_asked;
    id _value;
    id _default;
    id<IValue> _responseivalue;
    Interview *_interview;
}

- (id)init;
- (id)initWithIQuestion:(id<IQuestion>)question_ withInterview:(Interview *)interview;
- (id)initWithIQuestion:(id<IQuestion>)question_ withNSString:(NSString *)name withIResponses:(id<IResponses>)responses;
- (NSString *)getCoded;
- (void)setCoded:(NSString *)value;
- (DataTypeConstants)getDataType;
- (void)setDataType:(DataTypeConstants)value;
- (id)getdefaultproperty;
- (void)setdefaultproperty:(id)value;
- (id)getInitial;
- (void)setInitial:(id)value;
- (NSNumber *)getIsDirty;
- (void)setIsDirty:(NSNumber *)value;
- (NSString *)getLabel;
- (void)setLabel:(NSString *)value;
- (NSString *)getName;
- (void)setName:(NSString *)value;
- (id<IResponses>)getOther;
- (void)setOther:(id<IResponses>)value;
- (id)getValue;
- (void)setValue:(id)value;
- (id<IValue>)getValueObj;
- (void)setValueObj:(id<IValue>)value;
- (void)clear;
-(void)setAnswered:(NSDate *)value;

@end

