//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/RoutingTypeConstants.java
//
//  Created by chinthan on 1/15/14.
//


typedef enum {
  RoutingTypeConstants_rEmpty = 0,
  RoutingTypeConstants_rVariable = 1,
  RoutingTypeConstants_rGrid = 2,
  RoutingTypeConstants_rArray = 3,
  RoutingTypeConstants_rClass = 4,
  RoutingTypeConstants_rCompound = 5,
  RoutingTypeConstants_rPage = 6,
  RoutingTypeConstants_rComment = 7,
  RoutingTypeConstants_rGoto = 8,
  RoutingTypeConstants_rConditionalGoto = 9,
  RoutingTypeConstants_rExit = 10,
  RoutingTypeConstants_rScriptLabel = 11,
  RoutingTypeConstants_rQCItem = 12,
  RoutingTypeConstants_rScriptBasicItem = 13,
  RoutingTypeConstants_rObject = 14,
  RoutingTypeConstants_rIfBlock = 15,
  RoutingTypeConstants_rSetResponse = 16,
} RoutingTypeConstants;


