//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Meta/Routing.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _Routing_H_
#define _Routing_H_



@interface Routing : NSObject {
}

- (id)init;
@end

#endif // _Routing_H_
