//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/SavePoints.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _SavePoints_H_
//#define _SavePoints_H_




#import "ISavePoints.h"

@interface SavePoints : NSObject<ISavePoints> {
 @public
    NSMutableArray *_savePointsArray;
  BOOL __UseQuestionLabels_;
  id<ISavePoint> __CachedPoint_;
}
@property(nonatomic,strong) NSMutableArray *savePointsArray;
- (BOOL)getUseQuestionLabels;
- (void)setUseQuestionLabels:(BOOL)value;
- (id<ISavePoint>)getCachedPoint;
- (void)setCachedPoint:(id<ISavePoint>)value;
- (id<ISavePoint>)get___idxWithNSString:(NSString *)name;
- (void)set___idxWithNSString:(NSString *)name withISavePoint:(id<ISavePoint>)value;
- (BOOL)containsKey:(NSString *)key;
- (void)add:(id<ISavePoint>)item;
- (id)init;
-(void)clear;
-(NSString *)getUniqueKey:(NSString *)key withForm:(int)form;
-(int)searchForLastItem:(NSString *)key withForm:(int)form;
@end
