//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nitin/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Parser/Scanner.java
//
//  Created by nitin on 3/21/14.
//


@class StartStates;
@class Token;
#import "IScanner.h"
#import "Buffer.h"

#define Scanner_EOL '\x0a'
#define Scanner_eofSym 0
#define Scanner_maxT 52
#define Scanner_noSym 52

@interface Scanner : NSObject <IScanner>{
 @public
  unichar valCh_;
  Buffer *buffer_;
  Token *t_;
  int ch_;
  int pos_;
  int charPos_;
  int col_;
  int line_;
  int oldEols_;
  Token *tokens_;
  Token *pt_;
  char *tval_;

  //NSMutableData *tval_;
  int tlen_;
}

+ (unichar)EOL;
+ (int)eofSym;
+ (int)maxT;
+ (int)noSym;
+ (StartStates *)start;
+ (NSMutableDictionary *)literals;
- (id)initWithNSString:(NSString *)fileName;
- (id)initWithInputStream:(NSInputStream *)s withData:(NSData*)byteData;
- (void)Init;
- (void)NextCh;
- (void)AddCh;
- (BOOL)Comment0;
- (void)CheckLiteral;
- (Token *)NextToken;
- (void)SetScannerBehindT;
- (Token *)Scan;
- (Token *)Peek;
- (void)ResetPeek;
@end


