//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Helpers/ScriptReader.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _ScriptReader_H_
#define _ScriptReader_H_

#import "IScriptReader.h"
#import "BTBinaryTools.h"


@interface ScriptReader : NSData < IScriptReader > {
    BTBinaryStreamReader *reader;
    NSInputStream *inputReader;
}

- (id)initWithJavaIoInputStream:(NSData *)inputStream;
- (double)readDoubles;
- (short int)readInt16;
- (int)readInt32;
- (long)readInt64;
- (float)readSingle;
- (short int)readUInt16;
- (int)readUInt32;
- (void)dispose;
- (int)peekChar;
- (char)readSByte;
- (long)readUInt64;
- (double)readDecimal;
- (NSString *)readStringWithLength:(int)length;
- (NSString *)readString;
- (NSData *)readCharsWithInt:(int)count;
- (NSData *)readBytesWithInt:(int)count;
- (NSData *)getBaseStream;
@end

#endif // _ScriptReader_H_
