//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Helpers/ScriptWriter.java
//
//  Created by chinthan on 12/2/13.
//



#import "IScriptWriter.h"
#import "BTBinaryTools.h"

@interface ScriptWriter : NSData < IScriptWriter > {
    BTBinaryStreamWriter *writer;

}

- (id)initWithJavaIoOutputStream:(NSOutputStream *)awriter;
- (void)writeWithByte:(char)data;
- (void)writeWithBoolean:(BOOL)data;
- (void)writeWithChar:(unichar)data;
- (void)writeWithShort:(short int)data;
- (void)writeWithFloat:(float)data;
- (void)writeWithDouble:(double)data;
- (void)writeWithLong:(long long)data;
- (void)writeWithNSString:(NSString *)data;
- (void)dispose;
- (NSInputStream *)getBaseStream;
- (void)flushStream;
- (void)writeIntValWithInt:(int)data;
- (void)writeByteValWithByteArray:(NSData *)data;
- (void)writeWithCharArray:(char [])chars;
- (void)writeBytesWithByteArray:(Byte *)buffer
                        withInt:(int)index
                        withInt:(int)count;
- (void)writedata:(NSData *)data;
- (void)writeIntValWithInt:(int)data;
- (void)writedatedata:(NSData *)data;

@end

