//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Session/SessionManager.java
//
//  Created by ashchauhan on 3/21/14.
//

#import "CacheManager.h"

@interface  SessionManager : NSObject {
}
+(CacheManager*)getSession;
+ (void)add:(NSString *)key
                 withValue:(id)value;
+ (void)add:(NSString *)key
                 withValue:(id)value
                 withPriority:(id)priority
                 withAction:(id)action
                 withExpiration:(id)expiration;
+ (id)find:(NSString *)key;
+ (void)save:(NSString *)key
                  withValue:(id)value;
+ (void)clear;
+ (void)remove:(NSString *)key;
- (id)init;
@end
