//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/SourceTypeConstants.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  SourceTypeConstants_sDataField = 0,
  SourceTypeConstants_sExpression = 1,
  SourceTypeConstants_sExpressions = 2,
  SourceTypeConstants_sNoCaseData = 3,
  SourceTypeConstants_sNone = 4,
} SourceTypeConstants;


