//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/StackMapTableAttribute.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _StackMapTableAttribute_H_
#define _StackMapTableAttribute_H_


#import "Attribute.h"

@interface StackMapTableAttribute : Attribute {
}

- (id)init;
@end

#endif // _StackMapTableAttribute_H_
