//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/Source/StringFormat.java
//
//  Created by chinthan on 1/15/14.
//

typedef enum {
  StringFormat_Normal = 0,
  StringFormat_Summary = 1,
  StringFormat_Extended = 2,
  StringFormat_Descriptor = 3,
  StringFormat_Tuples = 4,
    StringFormat_Type = 5,

} StringFormat;



