//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebControls/SubTemplate.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebControlsSubTemplate_H_
//#define _OnePointPlayerWebWebControlsSubTemplate_H_


#import "Control.h"

@interface SubTemplate :Control{
}

- (id)initWithIControl:(id<IControl>)parent;
@end

//#endif // _OnePointPlayerWebWebControlsSubTemplate_H_
