//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/VirtualMachine/Core/SuperClass.java
//
//  Created by chinthan on 12/2/13.
//

#ifndef _SuperClass_H_
#define _SuperClass_H_



#import "ISuperClass.h"

@interface SuperClass : NSObject < ISuperClass > {
 @public
  NSMutableArray *__FieldList_;
  NSMutableArray *__StaticFieldList_;
  NSMutableDictionary *__Fields_;
  NSMutableDictionary *__Methods_;
  NSMutableDictionary *__StaticFields_;
  NSString *__BaseName_;
}

- (id)init;
- (NSMutableArray *)getFieldList;
- (void)setFieldListWithNSMutableArray:(NSMutableArray *)value;
- (NSMutableArray *)getStaticFieldList;
- (void)setStaticFieldListWithNSMutableArray:(NSMutableArray *)value;
- (NSMutableDictionary *)getFields;
- (void)setFieldsWithJavaUtilHashMap:(NSMutableDictionary *)value;
- (NSMutableDictionary *)getMethods;
- (void)setMethodsWithJavaUtilHashMap:(NSMutableDictionary *)value;
- (NSMutableDictionary *)getStaticFields;
- (void)setStaticFieldsWithJavaUtilHashMap:(NSMutableDictionary *)value;
- (NSString *)getBaseName;
- (void)setBaseNameWithNSString:(NSString *)value;
- (id)get___idxWithNSString:(NSString *)index;
- (void)set___idxWithNSString:(NSString *)index
                       withId:(id)value;
- (void)addFieldWithNSString:(NSString *)name
                      withId:(id)value
                 withBoolean:(BOOL)defaultValue;
- (void)addStaticFieldWithNSString:(NSString *)name
                            withId:(id)value
                       withBoolean:(BOOL)defaultValue;
@end


#endif // _SuperClass_H_
