//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/SymbolManagement/SymbolType.java
//
//  Created by chinthan on 1/6/14.
//

typedef enum {
  SymbolType_Class = 0,
  SymbolType_Structure = 1,
  SymbolType_Field = 2,
  SymbolType_Interface = 3,
  SymbolType_Constant = 4,
  SymbolType_Method = 5,
  SymbolType_Label = 6,
  SymbolType_Enumerator = 7,
} SymbolType;
