//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Helpers/SymbolManagement/SymbolTable.java
//
//  Created by chinthan on 1/6/14.
//

#ifndef _SymbolTable_H_
#define _SymbolTable_H_

#import "ISymbol.h"
#import "SymbolTable.h"
#import "ScriptReader.h"
#import "ScriptWriter.h"
#import "Handler.h"


@interface SymbolTable : NSObject <ISymbol> {
 @public
  NSMutableDictionary *globalSymbols_;
  NSMutableDictionary *symbolLookup_;
  NSMutableArray *symbols_;
  NSMutableArray *__Children_;
  SymbolTable *__Parent_;
  BOOL __AllowDuplicates_;
}

- (id)init;
- (id)initWithBoolean:(BOOL)allowDuplicates;
- (id)initWithSymbolTable:(SymbolTable *)parent;
- (NSMutableArray *)getChildren;
- (void)setChildrenWithNSMutableArray:(NSMutableArray *)value;
- (int)getCount;
- (SymbolTable *)getParent;
- (void)setParentWithSymbolTable:(SymbolTable *)value;
- (BOOL)getAllowDuplicates;
- (void)setAllowDuplicatesWithBoolean:(BOOL)value;
- (NSMutableArray *)getSymbols;
- (id<ISymbol>)get___idxWithNSString:(NSString *)reference;
- (void)set___idxWithNSString:(NSString *)reference withISymbol:(id<ISymbol>)value;
- (id<ISymbol>)get___idxwithint:(NSNumber *)pointer;
- (void)set___idxWithInt:(int)pointer withISymbol:(id<ISymbol>)value;
- (BOOL)addWithISymbol:(id<ISymbol>)symbol;
- (BOOL)insertWithISymbol:(id<ISymbol>)symbol;
- (SymbolTable *)addChild;
- (void)insertChild:(SymbolTable *)table;
- (BOOL)containsWithNSString:(NSString *)reference;
- (NSString *)getEnumerator;
- (id<ISymbol>)lookupWithNSString:(NSString *)reference;
- (BOOL)searchWithNSString:(NSString *)reference;
- (NSEnumerator *)iEnumerable___GetEnumerator;
- (id)iterator;
-(SymbolTable *)getRoot;
+(SymbolTable *)deserializeWithHandler:(Handler *)handler withSymbolTable:(SymbolTable*)parent withStream:(NSMutableData*)byteStream;
+(SymbolTable *)deserializeWithHandler:(Handler *)handler withSymboltable:(SymbolTable *)parent withScriptReader:(ScriptReader *)reader;
-(NSData *)serialize;
@end


#endif // _SymbolTable_H_
