//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/Templates/TemplateTypes.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _TemplateTypes_H_
//#define _TemplateTypes_H_


//#include "java/lang/Enum.h"

typedef enum {
  TemplateTypes_Grid = 0,
  TemplateTypes_Question = 1,
  TemplateTypes_Banner = 2,
  TemplateTypes_NavBar = 3,
  TemplateTypes_Error = 4,
  TemplateTypes_Layout = 5,
} TemplateTypes;

//#endif // _TemplateTypes_H_
