//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Expressions/Parser/UTF8Buffer.java
//
//  Created by chinthan on 1/15/14.
//

#ifndef _UTF8Buffer_H_
#define _UTF8Buffer_H_


#import "Buffer.h"

@interface UTF8Buffer : Buffer {
}

- (id)initWithBuffer:(Buffer *)b;
- (int)read;
@end

#endif // _UTF8Buffer_H_
