//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/chinthan/Framework/Logger/ConvertCode/OnePoint/Runtime/Common/ValidatedActions.java
//
//  Created by chinthan on 1/15/14.
//



typedef enum {
  ValidatedActions_vaRaiseError = 0,
  ValidatedActions_vaUpdateErrors = 1,
  ValidatedActions_vaAssignDefault = 2,
  ValidatedActions_vaAssignInitial = 3,
} ValidatedActions;



