//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Runtime/Common/IOM/ValueAttribute.java
//
//  Created by ashchauhan on 6/20/14.
//

//#ifndef _ValueAttribute_H_
//#define _ValueAttribute_H_



#import "IValueAttribute.h"

@interface  

ValueAttribute : NSObject < IValueAttribute > {
 @public
  NSString *__Name_;
  NSString *__Value_;
}

- (NSString *)getName;
- (void)setName:(NSString *)value;
- (NSString *)getValue;
- (void)setValue:(NSString *)value;
- (id)init;

@end
