//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebApplication.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebApplication_H_
//#define _OnePointPlayerWebWebApplication_H_

#import "IContext.h"
#import "NSString+HTML.h"
#import "IApplication.h"
#import "Interview.h"
@interface WebApplication : NSObject<IApplication> {
 @public
  id<IContext> __Context_;
    Interview *__interview_;
}

- (id)initWithInterview:(Interview*)interview withIContext:(id<IContext>)context;
-(void)setInteview:(Interview*)value;
-(Interview*)getInterview;
+ (NSString *)urlDecode:(NSString *)url;
+ (NSString *)urlEncode:(NSString *)url;
+ (NSString *)htmlEncode:(id)value;
+ (NSString *)htmlDecode:(NSString *)value;
- (id<IContext>)getContext;
- (void)setContext:(id<IContext>)value;

@end
//#endif // _OnePointPlayerWebWebApplication_H_
