//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebBrowser.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebBrowser_H_
//#define _OnePointPlayerWebWebBrowser_H_

#import <Foundation/Foundation.h>

@interface WebBrowser : NSObject {
 @public
  BOOL __JavaScript_;
}

- (BOOL)getJavaScript;
- (void)setJavaScript:(BOOL)value;
- (id)init;

@end

//#endif // _OnePointPlayerWebWebBrowser_H_
