//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebContext.java
//
//  Created by ashchauhan on 3/11/14.
//



#import "IRequest.h"
#import "IResponse.h"
#import "IContext.h"
#import "WebRequest.h"
#import "WebResponse.h"
@interface WebContext : NSObject<IContext > {
 @public
  id<IRequest> __Request;
  id<IResponse> __Response;
}
-(id)initWithContext:(id)context;
- (id<IRequest>)getRequest;
- (void)setRequest:(id<IRequest>)value;
- (id<IResponse>)getResponse;
- (void)setResponse:(id<IResponse>)value;
- (id)init;
@end

