//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebPlayer.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebPlayer_H_
//#define _OnePointPlayerWebWebPlayer_H_

#import <UIKit/UIKit.h>

@class Container;
@class Page;
@class TemplateManager;
@class HttpContext;
@class WebContext;
@class XmlControlMapper;
@class WebApplication;
@protocol IQuestion;
@class Results;
@protocol IResponse;
@class Interview;
@class HtmlPage;
#import "IPlayer.h"
#import "NavigationTypes.h"
#import "IosRuntimeInteractor.h"
@class WebSession;
@interface WebPlayer : NSObject <IPlayer> {
    Page *__page_;
    Container *__Resources_;
    HttpContext *_context;
    NSMutableDictionary *responses;
    NSMutableDictionary *appResponse;

    WebApplication *__application;
    NavigationTypesEnum navType;
    UIWebView *webView;
    NSString *__Goto;
    WebSession *Session;
    id<IosRuntimeInteractor> interactor;
    HtmlPage *htmlPage;
   
}
@property(nonatomic,strong)NSMutableDictionary *responses;
@property(nonatomic,strong)Page *__page_;
@property(nonatomic,strong)UIWebView *webView;
-(id)initWithInteractor:(id<IosRuntimeInteractor>)interactor_;
-(id)initWithContext:(HttpContext*)context;
- (id)initWithInterview:(id)interview
          withResouceContainer:(id)resourceContainer
          withContext:(id)context;
-(void)initializeWithInterview:(Interview*) interview withContaier:(Container*)resourceContainer  withType:(int)renderType;
-(HttpContext*)getAppContext;

-(NSString *)getName;

-(Container*)getResources;
-(void)setResources:(Container*)resources;

-(NSMutableDictionary*)getAppResponse;
-(void)setAppResponse:(NSMutableDictionary*)appResp;

-(void)setPage:(Page*)page;
-(Page*)getPage;
-(int)ask:(id<IQuestion>)question;
-(int)ask;
-(id)show:(id<IQuestion>) question;

-(BOOL)getPostBackRequired;
-(BOOL)validate;
-(void)updateContext:(HttpContext *)context;

-(void)UpdateQuestionResponse:(id<IResponse>)response withResult:(Results*)result;
-(NSData*)checkForResource:(NSString*)name;

-(void)checkNavigation:(NSString *)navigationType withValue:(NSString *)value;
-(void)updateUrl:(BOOL)terminate;
-(void)loadTargetPage;
-(void)setGoto:(NSString*)value;
-(NSString*)getGoto;
-(WebSession*)getWebSession;
-(void)setWebSession:(WebSession*)value;

@end
