//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebRequest.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebRequest_H_
//#define _OnePointPlayerWebWebRequest_H_

#import "WebBrowser.h"
#import "NSMutableURLRequest+Form.h"
#import "WebAnswers.h"
#import "IRequest.h"
#import "WebBrowser.h"
#import "NavigationTypes.h"
#import "IRequest.h"
#import <UIKit/UIKit.h>
@interface WebRequest : NSObject<IRequest > {
 @public
  UIWebView *__Browser_;
    id<IAnswers> __Answers_;
    NSMutableURLRequest *__Request_;
    NavigationTypesEnum __Action_;
}
-(id)initWithWebview:(UIWebView*)webview;
- (UIWebView *)getBrowser;
- (void)setBrowser:(UIWebView *)value;
- (id)initWithRequest:(NSMutableURLRequest*)request;

@end
