//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Web/WebResponse.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerWebWebResponse_H_
//#define _OnePointPlayerWebWebResponse_H_


#import "IResponse.h"
#import "NSHTTPURLResponse+Write.h"
#import "IResponse.h"
@interface WebResponse : NSObject<IResponse > {
    NSHTTPURLResponse *__Response_;
   
}
-(id)initWithNSString:(NSString*)htmlFilePath;
- (id)initWithResponse:(NSHTTPURLResponse*)response;
- (void)write:(id)text;
@end

//#endif // _OnePointPlayerWebWebResponse_H_
