//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/XmlControls/XmlCategory.java
//
//  Created by ashchauhan on 3/11/14.
//
#import <Foundation/Foundation.h>

@class XmlControl;

@protocol ICategory;

@interface XmlCategory : XmlControl {
}
- (id)initWithCategory:(id<ICategory>)category;
@end
