//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/XmlControls/XmlControlStyle.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerXmlXmlControlsXmlControlStyle_H_
//#define _OnePointPlayerXmlXmlControlsXmlControlStyle_H_


#import "XmlControl.h"
#import "IControlStyle.h"
@interface XmlControlStyle :XmlControl {
}
- (id)initWithInterview:(Interview*)interview withIControlStyle:(id<IControlStyle>)control;
- (NSString *)getControlType:(id<IControlStyle>)control;
@end

//#endif // _OnePointPlayerXmlXmlControlsXmlControlStyle_H_
