//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/IntermediateControls/XmlInterCategory.java
//
//  Created by ashchauhan on 4/1/14.
//

//#ifndef _OnePointPlayerXmlIntermediateControlsXmlInterCategory_H_
//#define _OnePointPlayerXmlIntermediateControlsXmlInterCategory_H_
#import <Foundation/Foundation.h>
@protocol IXmlInterControl;

#import "XmlInterLabel.h"
#import "XmlInterControl.h"
#import "XmlInterStyle.h"
#import "XmlInterQuestion.h"
#import "OPGStyle.h"

@interface XmlInterCategory :XmlInterControl {
    
}
- (id)initWithIXmlInterControl:(id<IXmlInterControl>)parent
                  withCategory:(id<ICategory>)category withBool:(BOOL)justCategory withInt:(int)categoryType withBool:(BOOL)includeLabel;
- (id)initWithIXmlInterControl:(id<IXmlInterControl>)parent withCategory:(id<ICategory>)category;
- (id)initWithIXmlInterControl:(id<IXmlInterControl>)parent withCategory:(id<ICategory>)category withInt:(int)categoryType;
- (id)initWithIXmlInterControl:(id<IXmlInterControl>)parent
                  withCategory:(id<ICategory>)category withInt:(int)categoryType withBool:(BOOL)includeLabel withStyle:(id<IStyle>)inheritedStyle;
-(void)justCategory:(id<ICategory>)category withBool:(BOOL)includeLabel;
@end
