//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/IntermediateControls/XmlInterNavigation.java
//
//  Created by ashchauhan on 4/1/14.
//

//#ifndef _XmlInterNavigation_H_
//#define _XmlInterNavigation_H_

@protocol IXmlInterControl;

#import "XmlInterStyle.h"
#import "XmlInterControl.h"
#import "NavigationTypes.h"
#import "INavigation.h"
#import "NavigationTypes.h"
@interface XmlInterNavigation : XmlInterControl {
}

- (id)initWithIXmlInterControl:(id<IXmlInterControl>)parent;
- (NSString *)navType:(id)navigation;
@end

 // _XmlInterNavigation_H_
