
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/IntermediateControls/XmlInterControl.java
//
//  Created by ashchauhan on 4/1/14.
//

//#ifndef _XmlInterControl_H_
//#define _XmlInterControl_H_

#import <Foundation/Foundation.h>


#import "IXmlInterControl.h"
#import "XmlControl.h"
@class XmlInterPage;
@class XmlControlMapper;

@interface XmlInterControl:XmlControl<IXmlInterControl> {
    
  id<IXmlInterControl> __Parent_;
  XmlInterPage *__Page_;
  XmlControlMapper *__Map_;
    BOOL __UseTableLayout;
}

- (id)initWithIXmlInterControl:(id<IXmlInterControl>)control;
- (id)initWithInterview:(Interview*)interview withQuestion:(id<IQuestion>)question;
- (id<IXmlInterControl>)getParent;
- (void)setParent:(id<IXmlInterControl>)value;
- (XmlInterPage *)getPage;
- (void)setPage:(XmlInterPage *)value;
- (XmlControlMapper *)getMap;
- (void)setMap:(XmlControlMapper *)value;

@end

