//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/IntermediateControls/XmlInterControlStyle.java
//
//  Created by ashchauhan on 4/1/14.
//

//#ifndef _OnePointPlayerXmlIntermediateControlsXmlInterControlStyle_H_
//#define _OnePointPlayerXmlIntermediateControlsXmlInterControlStyle_H_

@protocol IXmlInterControl;

#import "ControlTypes.h"

#import "XmlInterControl.h"
#import "IControlStyle.h"
@interface XmlInterControlStyle :XmlInterControl {
}

- (id)initWithIXmlInterControl:(id<IXmlInterControl>)parent withControl:(id<IControlStyle>)control;

+ (NSString *)getControlType:(id<IControlStyle>)control;
@end


