//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/Intermediate/XmlIntermediateNavigation.java
//
//  Created by ashchauhan on 3/21/14.
//


@protocol NavButtonType;

#import "GDataXMLNode.h"
#import "XmlControl.h"

@interface XmlIntermediateNavigation :XmlControl {
    NSArray *__nodes_;
    int enumerator;
}

- (id)initWithXmlDocument:(GDataXMLDocument*)document;
- (BOOL)getNextNavigation;
- (NSString *)getNavigationType:(NavButtonType)navType;
@end
