//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/IntermediateControls/XmlInterQuestion.java
//
//  Created by ashchauhan on 4/1/14.
//

//#ifndef _OnePointPlayerXmlIntermediateControlsXmlInterQuestion_H_
//#define _OnePointPlayerXmlIntermediateControlsXmlInterQuestion_H_

@protocol IXmlInterControl;

#import "XmlInterControl.h"
#import "XmlControlMapper.h"
#import "XmlQuestion.h"
#import "XmlInterLabel.h"
#import "XmlInterControlStyle.h"
#import "XmlInterCategories.h"
#import "IQuestion.h"
#import <math.h>
@interface XmlInterQuestion : XmlInterControl {
    NSString* __FullQuestionName;
    NSString*  __Max;
    NSString* __Min;
}

- (id)initWithIXmlInterControl:(id<IXmlInterControl>)parent withQuestion:(id<IQuestion>)question isOther:(BOOL)isOther;
- (id)initWithIXmlInterControl:(id<IXmlInterControl>)parent withQuestion:(id<IQuestion>)question;

- (BOOL)getIsPage;
- (void)processQuestion;
- (void)checkValidation;
- (NSString *)getQuestionDataType;
- (NSString *)getQuestionType;
-(NSString*)getFullQuestionName;
@end
