//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/XmlControls/XmlPage.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerXmlXmlControlsXmlPage_H_
//#define _OnePointPlayerXmlXmlControlsXmlPage_H_


#import "XmlControl.h"
#import "XmlQuestion.h"
#import "XmlNavigation.h"
@interface XmlPage :XmlControl {
}

- (id)initWithInterview:(Interview *)interview withQuestion:(id<IQuestion>)question;
@end

//#endif // _OnePointPlayerXmlXmlControlsXmlPage_H_
