//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/XmlControls/XmlQuestion.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerXmlXmlControlsXmlQuestion_H_
//#define _OnePointPlayerXmlXmlControlsXmlQuestion_H_


#import "XmlControl.h"
#import "XmlLabel.h"
#import "XmlStyle.h"
#import "XmlCategory.h"
@interface XmlQuestion : XmlControl {
}

- (id)initWithQuestion:(id<IQuestion>)question;
- (BOOL)getIsPage;
- (NSString *)getQuestionDataType;
- (NSString *)getQuestionType;
-(void)processQuestion;
@end

//#endif // _OnePointPlayerXmlXmlControlsXmlQuestion_H_
