//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/XmlControls/XmlStyle.java
//
//  Created by ashchauhan on 3/11/14.
//

//#ifndef _OnePointPlayerXmlXmlControlsXmlStyle_H_
//#define _OnePointPlayerXmlXmlControlsXmlStyle_H_


#import "XmlControl.h"
#import "IStyle.h"
#import "XmlControlStyle.h"
@interface XmlStyle :XmlControl {
    id<IStyle> __Style_;
}

- (id)initWithXmlStyle:(id<IStyle>)style;
- (NSString *)getElementAlign;
-(id<IStyle>) getStyle;
-(void)setStyle:(id<IStyle>) value;

@end

//#endif // _OnePointPlayerXmlXmlControlsXmlStyle_H_
