//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ashchauhan/Desktop/SampleApp/OnePoint/Player/Xml/Templates/XmlTemplateManager.java
//
//  Created by ashchauhan on 3/11/14.
//


#import <Foundation/Foundation.h>

@interface XmlTemplateManager : NSObject {
}
+(NSString*)getTemplate:(NSString*)name;
- (id)init;
@end


