// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IPanelPanellist" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanelPanellist.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IPanelPanellist Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   
#import	"IPanelData.h"
#import	"IPanellistProfileData.h"

/// <summary>
/// The IPanelPanellistData Interface Data Object Base
/// </summary>
@protocol IPanelPanellistData <NSObject>
    
-(NSNumber *) PanelPanellistID;
-(void) setPanelPanellistID:(NSNumber *) value;
-(NSNumber *) PanelID;
-(void) setPanelID:(NSNumber *) value;
-(NSNumber *) PanellistID;
-(void) setPanellistID:(NSNumber *) value;
-(NSNumber *) Included;
-(void) setIncluded:(NSNumber *) value;
-(BOOL) IncludedSpecified;
-(void) setIncludedSpecified:(BOOL) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(id<IPanelData>) Panel;

-(id<IPanellistProfileData>) PanellistProfile;


@end
   

   
    

