// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IPanellistProfile" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanellistProfile.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IPanellistProfile Interface Data Object Base
/// </summary>

#import <Foundation/Foundation.h>


/// <summary>
/// The IPanellistProfileFactoryBase Interface Data Object Base
/// </summary>
	
@protocol IPanellistProfileFactoryBase <NSObject>
   
-(NSString *) SelectAllStatement;
-(NSString *)TableName;
-(NSString *)ByPkClause;
-(NSString *)InsertStatement;
-(NSString *)UpdateStatement;
-(NSString *)DeleteStatement;
-(NSString *)DeleteByPk;


-(void) AddPanellistIDParameter:(DataHandler *) dataHandler withPanellistID:(NSNumber*) PanellistID;     
-(void) AddTitleParameter:(DataHandler *) dataHandler withTitle:(NSString *) Title;  
-(void) AddFirstNameParameter:(DataHandler *) dataHandler withFirstName:(NSString *) FirstName;  
-(void) AddLastNameParameter:(DataHandler *) dataHandler withLastName:(NSString *) LastName;  
-(void) AddUserNameParameter:(DataHandler *) dataHandler withUserName:(NSString *) UserName;  
-(void) AddEmailParameter:(DataHandler *) dataHandler withEmail:(NSString *) Email;  
-(void) AddMobileNumberParameter:(DataHandler *) dataHandler withMobileNumber:(NSString *) MobileNumber;  
-(void) AddPasswordParameter:(DataHandler *) dataHandler withPassword:(NSString *) Password;  
-(void) AddPasswordEncryptedParameter:(DataHandler *) dataHandler withPasswordEncrypted:(NSString *) PasswordEncrypted;  
-(void) AddPasswordLastUpdatedParameter:(DataHandler *) dataHandler withPasswordLastUpdated:(NSDate *) PasswordLastUpdated; 
-(void) AddDOBParameter:(DataHandler *) dataHandler withDOB:(NSDate *) DOB; 
-(void) AddWebsiteParameter:(DataHandler *) dataHandler withWebsite:(NSString *) Website;  
-(void) AddAddress1Parameter:(DataHandler *) dataHandler withAddress1:(NSString *) Address1;  
-(void) AddAddress2Parameter:(DataHandler *) dataHandler withAddress2:(NSString *) Address2;  
-(void) AddPostalCodeParameter:(DataHandler *) dataHandler withPostalCode:(NSString *) PostalCode;  
-(void) AddGeoLocationParameter:(DataHandler *) dataHandler withGeoLocation:(NSString *) GeoLocation;  
-(void) AddMediaIDParameter:(DataHandler *) dataHandler withMediaID:(NSString *) MediaID;  
-(void) AddCountryCodeParameter:(DataHandler *) dataHandler withCountryCode:(NSNumber*) CountryCode;     
-(void) AddTermsConditionParameter:(DataHandler *) dataHandler withTermsCondition:(NSNumber*) TermsCondition;     
-(void) AddTermsConditionNullParameter:(DataHandler *) dataHandler;
-(void) AddStatusParameter:(DataHandler *) dataHandler withStatus:(NSNumber*) Status;     
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler withIsDeleted:(NSNumber*) IsDeleted;     
-(void) AddCreatedDateParameter:(DataHandler *) dataHandler withCreatedDate:(NSDate *) CreatedDate; 
-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler withLastUpdatedDate:(NSDate *) LastUpdatedDate; 
-(void) AddSearchTagParameter:(DataHandler *) dataHandler withSearchTag:(NSString *) SearchTag;  
-(void) AddRemarkParameter:(DataHandler *) dataHandler withRemark:(NSString *) Remark;  
-(void) AddGenderParameter:(DataHandler *) dataHandler withGender:(NSNumber*) Gender;     
-(void) AddGenderNullParameter:(DataHandler *) dataHandler;
-(void) AddMaritalStatusParameter:(DataHandler *) dataHandler withMaritalStatus:(NSNumber*) MaritalStatus;     
-(void) AddMaritalStatusNullParameter:(DataHandler *) dataHandler;
-(id<IPanellistProfileData>) FindByPanellistID:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileData>) FindByTitle:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByFirstName:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByLastName:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByUserName:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByEmail:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByMobileNumber:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByPassword:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByPasswordEncrypted:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByPasswordLastUpdated:(NSDate *) fieldValue;
        
-(id<IPanellistProfileData>) FindByDOB:(NSDate *) fieldValue;
        
-(id<IPanellistProfileData>) FindByWebsite:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByAddress1:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByAddress2:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByPostalCode:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByGeoLocation:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByMediaID:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByCountryCode:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileData>) FindByTermsCondition:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileData>) FindByStatus:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileData>) FindByIsDeleted:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileData>) FindByCreatedDate:(NSDate *) fieldValue;
        
-(id<IPanellistProfileData>) FindByLastUpdatedDate:(NSDate *) fieldValue;
        
-(id<IPanellistProfileData>) FindBySearchTag:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByRemark:(NSString *) fieldValue;
        
-(id<IPanellistProfileData>) FindByGender:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileData>) FindByMaritalStatus:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileData>) CreatePanellistProfile:(id<IDataReader>)reader;

@end
    

   
    

