// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IPanellistProfile" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanellistProfile.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IPanellistProfile Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   
#import	"ICountryData.h"

/// <summary>
/// The IPanellistProfileData Interface Data Object Base
/// </summary>
@protocol IPanellistProfileData <NSObject>
    
-(NSNumber *) PanellistID;
-(void) setPanellistID:(NSNumber *) value;
-(NSString *) TitleSpecified;
-(void) setTitleSpecified:(NSString *) value;
-(NSString *) FirstNameSpecified;
-(void) setFirstNameSpecified:(NSString *) value;
-(NSString *) LastNameSpecified;
-(void) setLastNameSpecified:(NSString *) value;
-(NSString *) UserNameSpecified;
-(void) setUserNameSpecified:(NSString *) value;
-(NSString *) EmailSpecified;
-(void) setEmailSpecified:(NSString *) value;
-(NSString *) MobileNumberSpecified;
-(void) setMobileNumberSpecified:(NSString *) value;
-(NSString *) PasswordSpecified;
-(void) setPasswordSpecified:(NSString *) value;
-(NSString *) PasswordEncryptedSpecified;
-(void) setPasswordEncryptedSpecified:(NSString *) value;
-(NSDate *) PasswordLastUpdated;
-(void) setPasswordLastUpdated:(NSDate *) value;
-(NSDate *) DOB;
-(void) setDOB:(NSDate *) value;
-(NSString *) WebsiteSpecified;
-(void) setWebsiteSpecified:(NSString *) value;
-(NSString *) Address1Specified;
-(void) setAddress1Specified:(NSString *) value;
-(NSString *) Address2Specified;
-(void) setAddress2Specified:(NSString *) value;
-(NSString *) PostalCodeSpecified;
-(void) setPostalCodeSpecified:(NSString *) value;
-(NSString *) GeoLocationSpecified;
-(void) setGeoLocationSpecified:(NSString *) value;
-(NSString *) MediaIDSpecified;
-(void) setMediaIDSpecified:(NSString *) value;
-(NSNumber *) CountryCode;
-(void) setCountryCode:(NSNumber *) value;
-(NSNumber *) TermsCondition;
-(void) setTermsCondition:(NSNumber *) value;
-(BOOL) TermsConditionSpecified;
-(void) setTermsConditionSpecified:(BOOL) value;
-(NSNumber *) Status;
-(void) setStatus:(NSNumber *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;
-(NSString *) SearchTagSpecified;
-(void) setSearchTagSpecified:(NSString *) value;
-(NSString *) RemarkSpecified;
-(void) setRemarkSpecified:(NSString *) value;
-(NSNumber *) Gender;
-(void) setGender:(NSNumber *) value;
-(BOOL) GenderSpecified;
-(void) setGenderSpecified:(BOOL) value;
-(NSNumber *) MaritalStatus;
-(void) setMaritalStatus:(NSNumber *) value;
-(BOOL) MaritalStatusSpecified;
-(void) setMaritalStatusSpecified:(BOOL) value;
-(id<ICountryData>) Country;


@end
   

   
    

