// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IPanel" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Panel.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IPanel Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The IPanelData Interface Data Object Base
/// </summary>
@protocol IPanelData <NSObject>
    
-(NSNumber *) PanelID;
-(void) setPanelID:(NSNumber *) value;
-(NSNumber *) ThemeTemplateID;
-(void) setThemeTemplateID:(NSNumber *) value;
-(NSNumber *) ThemeTemplateIDSpecified;
-(void) setThemeTemplateIDSpecified:(NSNumber *) value;
-(NSString *) NameSpecified;
-(void) setNameSpecified:(NSString *) value;
-(NSString *) DescriptionSpecified;
-(void) setDescriptionSpecified:(NSString *) value;
-(NSNumber *) PanelType;
-(void) setPanelType:(NSNumber *) value;
-(NSString *) SearchTagSpecified;
-(void) setSearchTagSpecified:(NSString *) value;
-(NSString *) RemarkSpecified;
-(void) setRemarkSpecified:(NSString *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;
-(NSNumber *) UserID;
-(void) setUserID:(NSNumber *) value;

@end
   

   
    

