// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IPanellistProfileVariableDataType" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanellistProfileVariableDataType.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IPanellistProfileVariableDataType Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The IPanellistProfileVariableDataTypeData Interface Data Object Base
/// </summary>
@protocol IPanellistProfileVariableDataTypeData <NSObject>
    
-(NSNumber *) TypeID;
-(void) setTypeID:(NSNumber *) value;
-(NSNumber *) Type;
-(void) setType:(NSNumber *) value;
-(NSString *) NameSpecified;
-(void) setNameSpecified:(NSString *) value;
-(NSString *) DescriptionSpecified;
-(void) setDescriptionSpecified:(NSString *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;

@end
   

   
    

