// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IPanellistProfileVariable" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanellistProfileVariable.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IPanellistProfileVariable Interface Data Object Base
/// </summary>

#import <Foundation/Foundation.h>


/// <summary>
/// The IPanellistProfileVariableFactoryBase Interface Data Object Base
/// </summary>
	
@protocol IPanellistProfileVariableFactoryBase <NSObject>
   
-(NSString *) SelectAllStatement;
-(NSString *)TableName;
-(NSString *)ByPkClause;
-(NSString *)InsertStatement;
-(NSString *)UpdateStatement;
-(NSString *)DeleteStatement;
-(NSString *)DeleteByPk;


-(void) AddVariableIDParameter:(DataHandler *) dataHandler withVariableID:(NSNumber*) VariableID;     
-(void) AddNameParameter:(DataHandler *) dataHandler withName:(NSString *) Name;  
-(void) AddPanelIDParameter:(DataHandler *) dataHandler withPanelID:(NSNumber*) PanelID;     
-(void) AddTypeIDParameter:(DataHandler *) dataHandler withTypeID:(NSNumber*) TypeID;     
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler withIsDeleted:(NSNumber*) IsDeleted;     
-(void) AddIsBasicParameter:(DataHandler *) dataHandler withIsBasic:(NSNumber*) IsBasic;     
-(void) AddCreatedDateParameter:(DataHandler *) dataHandler withCreatedDate:(NSDate *) CreatedDate; 
-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler withLastUpdatedDate:(NSDate *) LastUpdatedDate; 
-(id<IPanellistProfileVariableData>) FindByVariableID:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileVariableData>) FindByName:(NSString *) fieldValue;
        
-(id<IPanellistProfileVariableData>) FindByPanelID:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileVariableData>) FindByTypeID:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileVariableData>) FindByIsDeleted:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileVariableData>) FindByIsBasic:(NSNumber *) fieldValue;
        
-(id<IPanellistProfileVariableData>) FindByCreatedDate:(NSDate *) fieldValue;
        
-(id<IPanellistProfileVariableData>) FindByLastUpdatedDate:(NSDate *) fieldValue;
        
-(id<IPanellistProfileVariableData>) CreatePanellistProfileVariable:(id<IDataReader>)reader;

@end
    

   
    

