// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IPanel" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Panel.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The IPanel Interface Data Object Base
/// </summary>

#import <Foundation/Foundation.h>


/// <summary>
/// The IPanelFactoryBase Interface Data Object Base
/// </summary>
	
@protocol IPanelFactoryBase <NSObject>
   
-(NSString *) SelectAllStatement;
-(NSString *)TableName;
-(NSString *)ByPkClause;
-(NSString *)InsertStatement;
-(NSString *)UpdateStatement;
-(NSString *)DeleteStatement;
-(NSString *)DeleteByPk;


-(void) AddPanelIDParameter:(DataHandler *) dataHandler withPanelID:(NSNumber*) PanelID;     
-(void) AddThemeTemplateIDParameter:(DataHandler *) dataHandler withThemeTemplateID:(NSNumber*) ThemeTemplateID;     
-(void) AddThemeTemplateIDNullParameter:(DataHandler *) dataHandler;
-(void) AddNameParameter:(DataHandler *) dataHandler withName:(NSString *) Name;  
-(void) AddDescriptionParameter:(DataHandler *) dataHandler withDescription:(NSString *) Description;  
-(void) AddPanelTypeParameter:(DataHandler *) dataHandler withPanelType:(NSNumber*) PanelType;     
-(void) AddSearchTagParameter:(DataHandler *) dataHandler withSearchTag:(NSString *) SearchTag;  
-(void) AddRemarkParameter:(DataHandler *) dataHandler withRemark:(NSString *) Remark;  
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler withIsDeleted:(NSNumber*) IsDeleted;     
-(void) AddCreatedDateParameter:(DataHandler *) dataHandler withCreatedDate:(NSDate *) CreatedDate; 
-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler withLastUpdatedDate:(NSDate *) LastUpdatedDate; 
-(void) AddUserIDParameter:(DataHandler *) dataHandler withUserID:(NSNumber*) UserID;     
-(id<IPanelData>) FindByPanelID:(NSNumber *) fieldValue;
        
-(id<IPanelData>) FindByThemeTemplateID:(NSNumber *) fieldValue;
        
-(id<IPanelData>) FindByName:(NSString *) fieldValue;
        
-(id<IPanelData>) FindByDescription:(NSString *) fieldValue;
        
-(id<IPanelData>) FindByPanelType:(NSNumber *) fieldValue;
        
-(id<IPanelData>) FindBySearchTag:(NSString *) fieldValue;
        
-(id<IPanelData>) FindByRemark:(NSString *) fieldValue;
        
-(id<IPanelData>) FindByIsDeleted:(NSNumber *) fieldValue;
        
-(id<IPanelData>) FindByCreatedDate:(NSDate *) fieldValue;
        
-(id<IPanelData>) FindByLastUpdatedDate:(NSDate *) fieldValue;
        
-(id<IPanelData>) FindByUserID:(NSNumber *) fieldValue;
        
-(id<IPanelData>) CreatePanel:(id<IDataReader>)reader;

@end
    

   
    

