// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISample" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Sample.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ISample Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The ISampleData Interface Data Object Base
/// </summary>
@protocol ISampleData <NSObject>
    
-(NSNumber *) SampleID;
-(void) setSampleID:(NSNumber *) value;
-(NSString *) NameSpecified;
-(void) setNameSpecified:(NSString *) value;
-(NSString *) DescriptionSpecified;
-(void) setDescriptionSpecified:(NSString *) value;
-(NSNumber *) UserID;
-(void) setUserID:(NSNumber *) value;
-(NSString *) SampleQuerySpecified;
-(void) setSampleQuerySpecified:(NSString *) value;
-(NSString *) SampleSqlQuerySpecified;
-(void) setSampleSqlQuerySpecified:(NSString *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;

@end
   

   
    

