// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISampleQueryCondition" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SampleQueryCondition.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ISampleQueryCondition Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The ISampleQueryConditionData Interface Data Object Base
/// </summary>
@protocol ISampleQueryConditionData <NSObject>
    
-(NSNumber *) SampleQueryConditionID;
-(void) setSampleQueryConditionID:(NSNumber *) value;
-(NSString *) NameSpecified;
-(void) setNameSpecified:(NSString *) value;
-(NSString *) DescriptionSpecified;
-(void) setDescriptionSpecified:(NSString *) value;
-(NSString *) OperatorSpecified;
-(void) setOperatorSpecified:(NSString *) value;
-(NSString *) SqlOperatorSpecified;
-(void) setSqlOperatorSpecified:(NSString *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;

@end
   

   
    

