// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISamplePanel" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SamplePanel.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ISamplePanel Interface Data Object Base
/// </summary>

#import <Foundation/Foundation.h>


/// <summary>
/// The ISamplePanelFactoryBase Interface Data Object Base
/// </summary>
	
@protocol ISamplePanelFactoryBase <NSObject>
   
-(NSString *) SelectAllStatement;
-(NSString *)TableName;
-(NSString *)ByPkClause;
-(NSString *)InsertStatement;
-(NSString *)UpdateStatement;
-(NSString *)DeleteStatement;
-(NSString *)DeleteByPk;


-(void) AddSamplePanelIDParameter:(DataHandler *) dataHandler withSamplePanelID:(NSNumber*) SamplePanelID;     
-(void) AddSampleIDParameter:(DataHandler *) dataHandler withSampleID:(NSNumber*) SampleID;     
-(void) AddPanelIDParameter:(DataHandler *) dataHandler withPanelID:(NSNumber*) PanelID;     
-(void) AddIsDeletedParameter:(DataHandler *) dataHandler withIsDeleted:(NSNumber*) IsDeleted;     
-(void) AddCreatedDateParameter:(DataHandler *) dataHandler withCreatedDate:(NSDate *) CreatedDate; 
-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler withLastUpdatedDate:(NSDate *) LastUpdatedDate; 
-(id<ISamplePanelData>) FindBySamplePanelID:(NSNumber *) fieldValue;
        
-(id<ISamplePanelData>) FindBySampleID:(NSNumber *) fieldValue;
        
-(id<ISamplePanelData>) FindByPanelID:(NSNumber *) fieldValue;
        
-(id<ISamplePanelData>) FindByIsDeleted:(NSNumber *) fieldValue;
        
-(id<ISamplePanelData>) FindByCreatedDate:(NSDate *) fieldValue;
        
-(id<ISamplePanelData>) FindByLastUpdatedDate:(NSDate *) fieldValue;
        
-(id<ISamplePanelData>) CreateSamplePanel:(id<IDataReader>)reader;

@end
    

   
    

