// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISamplePanel" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SamplePanel.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ISamplePanel Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   

/// <summary>
/// The ISamplePanelData Interface Data Object Base
/// </summary>
@protocol ISamplePanelData <NSObject>
    
-(NSNumber *) SamplePanelID;
-(void) setSamplePanelID:(NSNumber *) value;
-(NSNumber *) SampleID;
-(void) setSampleID:(NSNumber *) value;
-(NSNumber *) PanelID;
-(void) setPanelID:(NSNumber *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;

@end
   

   
    

