// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISamplePanellist" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SamplePanellist.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


/// <summary>
/// The ISamplePanellist Interface Data Object Base
/// </summary>
 
#import <Foundation/Foundation.h>   
#import	"IPanellistProfileData.h"

/// <summary>
/// The ISamplePanellistData Interface Data Object Base
/// </summary>
@protocol ISamplePanellistData <NSObject>
    
-(NSNumber *) SamplePanellistID;
-(void) setSamplePanellistID:(NSNumber *) value;
-(NSNumber *) SampleID;
-(void) setSampleID:(NSNumber *) value;
-(NSNumber *) PanellistID;
-(void) setPanellistID:(NSNumber *) value;
-(NSNumber *) PanelID;
-(void) setPanelID:(NSNumber *) value;
-(NSNumber *) Excluded;
-(void) setExcluded:(NSNumber *) value;
-(NSNumber *) IsDeleted;
-(void) setIsDeleted:(NSNumber *) value;
-(NSDate *) CreatedDate;
-(void) setCreatedDate:(NSDate *) value;
-(NSDate *) LastUpdatedDate;
-(void) setLastUpdatedDate:(NSDate *) value;
-(id<IPanellistProfileData>) PanellistProfile;


@end
   

   
    

