// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanellistProfile.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IPanellistProfileData.h"
#import "IPanellistProfileFactoryBase.h"

//package OnePoint.POM.Model; 
  

/// <summary>
/// Creates and finds PanellistProfile objects
/// </summary>



@interface  PanellistProfileFactoryBase : DataObjectFactory<IPanellistProfileData,IPanellistProfileFactoryBase>
{
}

+(NSString*)  FIELD_NAME_PANELLISTID;
+(NSString*)  FIELD_NAME_TITLE;
+(NSString*)  FIELD_NAME_FIRSTNAME;
+(NSString*)  FIELD_NAME_LASTNAME;
+(NSString*)  FIELD_NAME_USERNAME;
+(NSString*)  FIELD_NAME_EMAIL;
+(NSString*)  FIELD_NAME_MOBILENUMBER;
+(NSString*)  FIELD_NAME_PASSWORD;
+(NSString*)  FIELD_NAME_PASSWORDENCRYPTED;
+(NSString*)  FIELD_NAME_PASSWORDLASTUPDATED;
+(NSString*)  FIELD_NAME_DOB;
+(NSString*)  FIELD_NAME_WEBSITE;
+(NSString*)  FIELD_NAME_ADDRESS1;
+(NSString*)  FIELD_NAME_ADDRESS2;
+(NSString*)  FIELD_NAME_POSTALCODE;
+(NSString*)  FIELD_NAME_GEOLOCATION;
+(NSString*)  FIELD_NAME_MEDIAID;
+(NSString*)  FIELD_NAME_COUNTRYCODE;
+(NSString*)  FIELD_NAME_TERMSCONDITION;
+(NSString*)  FIELD_NAME_STATUS;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*)  FIELD_NAME_SEARCHTAG;
+(NSString*)  FIELD_NAME_REMARK;
+(NSString*)  FIELD_NAME_GENDER;
+(NSString*)  FIELD_NAME_MARITALSTATUS;
+(NSString*) PARAMETER_NAME_PANELLISTID;
+(NSString*) PARAMETER_NAME_TITLE;
+(NSString*) PARAMETER_NAME_FIRSTNAME;
+(NSString*) PARAMETER_NAME_LASTNAME;
+(NSString*) PARAMETER_NAME_USERNAME;
+(NSString*) PARAMETER_NAME_EMAIL;
+(NSString*) PARAMETER_NAME_MOBILENUMBER;
+(NSString*) PARAMETER_NAME_PASSWORD;
+(NSString*) PARAMETER_NAME_PASSWORDENCRYPTED;
+(NSString*) PARAMETER_NAME_PASSWORDLASTUPDATED;
+(NSString*) PARAMETER_NAME_DOB;
+(NSString*) PARAMETER_NAME_WEBSITE;
+(NSString*) PARAMETER_NAME_ADDRESS1;
+(NSString*) PARAMETER_NAME_ADDRESS2;
+(NSString*) PARAMETER_NAME_POSTALCODE;
+(NSString*) PARAMETER_NAME_GEOLOCATION;
+(NSString*) PARAMETER_NAME_MEDIAID;
+(NSString*) PARAMETER_NAME_COUNTRYCODE;
+(NSString*) PARAMETER_NAME_TERMSCONDITION;
+(NSString*) PARAMETER_NAME_STATUS;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_SEARCHTAG;
+(NSString*) PARAMETER_NAME_REMARK;
+(NSString*) PARAMETER_NAME_GENDER;
+(NSString*) PARAMETER_NAME_MARITALSTATUS;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyPanellistID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyPanellistID;
// Define input parameters once only so they can be reused by other methods
-(void) AddPanellistIDParameter:(DataHandler *) dataHandler valPanellistID:(NSNumber *) valPanellistID;	

-(void) AddTitleParameter:(DataHandler *) dataHandler valTitle:(NSString *) valTitle;	

-(void) AddFirstNameParameter:(DataHandler *) dataHandler valFirstName:(NSString *) valFirstName;	

-(void) AddLastNameParameter:(DataHandler *) dataHandler valLastName:(NSString *) valLastName;	

-(void) AddUserNameParameter:(DataHandler *) dataHandler valUserName:(NSString *) valUserName;	

-(void) AddEmailParameter:(DataHandler *) dataHandler valEmail:(NSString *) valEmail;	

-(void) AddMobileNumberParameter:(DataHandler *) dataHandler valMobileNumber:(NSString *) valMobileNumber;	

-(void) AddPasswordParameter:(DataHandler *) dataHandler valPassword:(NSString *) valPassword;	

-(void) AddPasswordEncryptedParameter:(DataHandler *) dataHandler valPasswordEncrypted:(NSString *) valPasswordEncrypted;	

-(void) AddPasswordLastUpdatedParameter:(DataHandler *) dataHandler valPasswordLastUpdated: (NSDate *) valPasswordLastUpdated;	

-(void) AddDOBParameter:(DataHandler *) dataHandler valDOB: (NSDate *) valDOB;	

-(void) AddWebsiteParameter:(DataHandler *) dataHandler valWebsite:(NSString *) valWebsite;	

-(void) AddAddress1Parameter:(DataHandler *) dataHandler valAddress1:(NSString *) valAddress1;	

-(void) AddAddress2Parameter:(DataHandler *) dataHandler valAddress2:(NSString *) valAddress2;	

-(void) AddPostalCodeParameter:(DataHandler *) dataHandler valPostalCode:(NSString *) valPostalCode;	

-(void) AddGeoLocationParameter:(DataHandler *) dataHandler valGeoLocation:(NSString *) valGeoLocation;	

-(void) AddMediaIDParameter:(DataHandler *) dataHandler valMediaID:(NSString *) valMediaID;	

-(void) AddCountryCodeParameter:(DataHandler *) dataHandler valCountryCode:(NSNumber *) valCountryCode;	

-(void) AddTermsConditionParameter:(DataHandler *) dataHandler valTermsCondition:(NSNumber *) valTermsCondition;	

-(void) AddTermsConditionNullParameter:(DataHandler *) dataHandler; 
-(void) AddStatusParameter:(DataHandler *) dataHandler valStatus:(NSNumber *) valStatus;	

-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(void) AddSearchTagParameter:(DataHandler *) dataHandler valSearchTag:(NSString *) valSearchTag;	

-(void) AddRemarkParameter:(DataHandler *) dataHandler valRemark:(NSString *) valRemark;	

-(void) AddGenderParameter:(DataHandler *) dataHandler valGender:(NSNumber *) valGender;	

-(void) AddGenderNullParameter:(DataHandler *) dataHandler; 
-(void) AddMaritalStatusParameter:(DataHandler *) dataHandler valMaritalStatus:(NSNumber *) valMaritalStatus;	

-(void) AddMaritalStatusNullParameter:(DataHandler *) dataHandler; 
-(BOOL) ProcessPkStatement :(NSNumber *) keyPanellistID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyPanellistID query:(NSString *) query;

-(id<IPanellistProfileData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IPanellistProfileData>) FindByPanellistID:(NSNumber *) fieldValue;
-(id<IPanellistProfileData>) FindByTitle:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByFirstName:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByLastName:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByUserName:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByEmail:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByMobileNumber:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByPassword:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByPasswordEncrypted:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByPasswordLastUpdated:(NSDate *) fieldValue;  
-(id<IPanellistProfileData>) FindByDOB:(NSDate *) fieldValue;  
-(id<IPanellistProfileData>) FindByWebsite:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByAddress1:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByAddress2:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByPostalCode:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByGeoLocation:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByMediaID:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByCountryCode:(NSNumber *) fieldValue;
-(id<IPanellistProfileData>) FindByTermsCondition:(NSNumber *) fieldValue;
-(id<IPanellistProfileData>) FindByStatus:(NSNumber *) fieldValue;
-(id<IPanellistProfileData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<IPanellistProfileData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IPanellistProfileData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(id<IPanellistProfileData>) FindBySearchTag:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByRemark:(NSString *) fieldValue; 
-(id<IPanellistProfileData>) FindByGender:(NSNumber *) fieldValue;
-(id<IPanellistProfileData>) FindByMaritalStatus:(NSNumber *) fieldValue;
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IPanellistProfileData>) FindObject :(NSNumber *) keyPanellistID ;
        
-(id<IPanellistProfileData>) Find:(DataHandler *) dataHandler;
        
-(id<IPanellistProfileData>) FindAllObjects;

-(id<IPanellistProfileData>) FindAllObjects:(NSString *) orderByField;

-(id<IPanellistProfileData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IPanellistProfileData>) CreatePanellistProfile:(id<IDataReader>) reader;
		
-(id<IPanellistProfileData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IPanellistProfileData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end