// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PanelPanellistBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanelPanellist.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IPanelPanellistData.h"



#import "IPanelData.h";
#import "PanelFactory.h";
#import "IPanellistProfileData.h";
#import "PanellistProfileFactory.h";

//package OnePoint.POM.Model 
    
	

    
@interface  PanelPanellistBase : DataObject<DataObject, IPanelPanellistData>
{
@private NSNumber *PanelPanellistID;
        
@private NSNumber *PanelID;
        
@private NSNumber *PanellistID;
        
@private NSNumber *Included;
        
	@private BOOL isIncludedSpecified;
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private NSNumber *IsDeleted;
        
@private id<IPanelData> relPanel; 
@private id<IPanellistProfileData> relPanellistProfile; 
}


	  

	@property(nonatomic,retain) NSNumber *PanelPanellistID;

	
	@property(nonatomic,retain) NSNumber *PanelID;

	
	@property(nonatomic,retain) NSNumber *PanellistID;

	
	@property(nonatomic,retain) NSNumber *Included;

		///<summary>Determines whether Included currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isIncludedSpecified;
	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	
	@property(nonatomic,retain) NSNumber *IsDeleted;

	@property(readwrite,strong) id<IPanelData> RelPanel; 
@property(readwrite,strong) id<IPanellistProfileData> RelPanellistProfile; 
@end
         

    

    