// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanelTheme.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IPanelThemeData.h"
#import "IPanelThemeFactoryBase.h"

//package OnePoint.POM.Model; 
  

/// <summary>
/// Creates and finds PanelTheme objects
/// </summary>



@interface  PanelThemeFactoryBase : DataObjectFactory<IPanelThemeData,IPanelThemeFactoryBase>
{
}

+(NSString*)  FIELD_NAME_PANELTHEMEID;
+(NSString*)  FIELD_NAME_THEMETEMPLATEID;
+(NSString*)  FIELD_NAME_PANELID;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_PANELTHEMEID;
+(NSString*) PARAMETER_NAME_THEMETEMPLATEID;
+(NSString*) PARAMETER_NAME_PANELID;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyPanelThemeID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyPanelThemeID;
// Define input parameters once only so they can be reused by other methods
-(void) AddPanelThemeIDParameter:(DataHandler *) dataHandler valPanelThemeID:(NSNumber *) valPanelThemeID;	

-(void) AddThemeTemplateIDParameter:(DataHandler *) dataHandler valThemeTemplateID:(NSNumber *) valThemeTemplateID;	

-(void) AddPanelIDParameter:(DataHandler *) dataHandler valPanelID:(NSNumber *) valPanelID;	

-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyPanelThemeID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyPanelThemeID query:(NSString *) query;

-(id<IPanelThemeData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IPanelThemeData>) FindByPanelThemeID:(NSNumber *) fieldValue;
-(id<IPanelThemeData>) FindByThemeTemplateID:(NSNumber *) fieldValue;
-(id<IPanelThemeData>) FindByPanelID:(NSNumber *) fieldValue;
-(id<IPanelThemeData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<IPanelThemeData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IPanelThemeData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IPanelThemeData>) FindObject :(NSNumber *) keyPanelThemeID ;
        
-(id<IPanelThemeData>) Find:(DataHandler *) dataHandler;
        
-(id<IPanelThemeData>) FindAllObjects;

-(id<IPanelThemeData>) FindAllObjects:(NSString *) orderByField;

-(id<IPanelThemeData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IPanelThemeData>) CreatePanelTheme:(id<IDataReader>) reader;
		
-(id<IPanelThemeData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IPanelThemeData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end