//------------------------------------------------------------------------
// Generated on 10/12/2014 09:22:40 for Sachin\Sachin
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------
#import <Foundation/Foundation.h>
#import "PanellistProfileVariableFactoryBase.h"
#import "PanellistProfileVariable.h"
#import "IPanellistProfileVariableData.h"
#import <OnePointFramework/IDisposable.h>
//package OnePoint.POM.Model 

@interface PanellistProfileVariableFactory : PanellistProfileVariableFactoryBase<IDisposable> {
}

@end

