// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PanellistProfileVariableResponseBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanellistProfileVariableResponse.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IPanellistProfileVariableResponseData.h"



#import "IPanellistProfileData.h";
#import "PanellistProfileFactory.h";
#import "IPanellistProfileVariableData.h";
#import "PanellistProfileVariableFactory.h";
#import "IPanellistProfileVariableDataTypeData.h";
#import "PanellistProfileVariableDataTypeFactory.h";
#import "IPanelData.h";
#import "PanelFactory.h";

//package OnePoint.POM.Model 
    
	

    
@interface  PanellistProfileVariableResponseBase : DataObject<DataObject, IPanellistProfileVariableResponseData>
{
@private NSNumber *PanellistProfileVariableResponseID;
        
@private NSNumber *PanelID;
        
@private NSNumber *PanellistID;
        
@private NSNumber *VariableID;
        
@private NSNumber *TypeID;
        
@private NSString *TextVal;
        
@private NSNumber *RealVal;
        
@private NSDate *DateVal;
        
@private NSMutableData *ObjectVal;
        
@private NSNumber *IsDeleted;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private id<IPanellistProfileData> relPanellistProfile; 
@private id<IPanellistProfileVariableData> relPanellistProfileVariable; 
@private id<IPanellistProfileVariableDataTypeData> relPanellistProfileVariableDataType; 
@private id<IPanelData> relPanel; 
}


	  

	@property(nonatomic,retain) NSNumber *PanellistProfileVariableResponseID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *PanelID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *PanellistID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *VariableID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *TypeID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *TextVal;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *RealVal;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSDate *DateVal;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSMutableData *ObjectVal;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *IsDeleted;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	@property(readwrite,strong) id<IPanellistProfileData> RelPanellistProfile; 
@property(readwrite,strong) id<IPanellistProfileVariableData> RelPanellistProfileVariable; 
@property(readwrite,strong) id<IPanellistProfileVariableDataTypeData> RelPanellistProfileVariableDataType; 
@property(readwrite,strong) id<IPanelData> RelPanel; 
@end
         

    

    