// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PanelThemeBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanelTheme.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IPanelThemeData.h"



#import "IPanelData.h";
#import "PanelFactory.h";
#import "IThemeTemplateData.h";
#import "ThemeTemplateFactory.h";

//package OnePoint.POM.Model 
    
	

    
@interface  PanelThemeBase : DataObject<DataObject, IPanelThemeData>
{
@private NSNumber *PanelThemeID;
        
@private NSNumber *ThemeTemplateID;
        
@private NSNumber *PanelID;
        
@private NSNumber *IsDeleted;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private id<IPanelData> relPanel; 
@private id<IThemeTemplateData> relThemeTemplate; 
}


	  

	@property(nonatomic,retain) NSNumber *PanelThemeID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *ThemeTemplateID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *PanelID;

	
	@property(nonatomic,retain) NSNumber *IsDeleted;

	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	@property(readwrite,strong) id<IPanelData> RelPanel; 
@property(readwrite,strong) id<IThemeTemplateData> RelThemeTemplate; 
@end
         

    

    