// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in Panel.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IPanelData.h"
#import "IPanelFactoryBase.h"

//package OnePoint.POM.Model; 
  

/// <summary>
/// Creates and finds Panel objects
/// </summary>



@interface  PanelFactoryBase : DataObjectFactory<IPanelData,IPanelFactoryBase>
{
}

+(NSString*)  FIELD_NAME_PANELID;
+(NSString*)  FIELD_NAME_THEMETEMPLATEID;
+(NSString*)  FIELD_NAME_NAME;
+(NSString*)  FIELD_NAME_DESCRIPTION;
+(NSString*)  FIELD_NAME_PANELTYPE;
+(NSString*)  FIELD_NAME_SEARCHTAG;
+(NSString*)  FIELD_NAME_REMARK;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*)  FIELD_NAME_USERID;
+(NSString*) PARAMETER_NAME_PANELID;
+(NSString*) PARAMETER_NAME_THEMETEMPLATEID;
+(NSString*) PARAMETER_NAME_NAME;
+(NSString*) PARAMETER_NAME_DESCRIPTION;
+(NSString*) PARAMETER_NAME_PANELTYPE;
+(NSString*) PARAMETER_NAME_SEARCHTAG;
+(NSString*) PARAMETER_NAME_REMARK;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_USERID;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyPanelID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyPanelID;
// Define input parameters once only so they can be reused by other methods
-(void) AddPanelIDParameter:(DataHandler *) dataHandler valPanelID:(NSNumber *) valPanelID;	

-(void) AddThemeTemplateIDParameter:(DataHandler *) dataHandler valThemeTemplateID:(NSNumber *) valThemeTemplateID;	

-(void) AddThemeTemplateIDNullParameter:(DataHandler *) dataHandler; 
-(void) AddNameParameter:(DataHandler *) dataHandler valName:(NSString *) valName;	

-(void) AddDescriptionParameter:(DataHandler *) dataHandler valDescription:(NSString *) valDescription;	

-(void) AddPanelTypeParameter:(DataHandler *) dataHandler valPanelType:(NSNumber *) valPanelType;	

-(void) AddSearchTagParameter:(DataHandler *) dataHandler valSearchTag:(NSString *) valSearchTag;	

-(void) AddRemarkParameter:(DataHandler *) dataHandler valRemark:(NSString *) valRemark;	

-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(void) AddUserIDParameter:(DataHandler *) dataHandler valUserID:(NSNumber *) valUserID;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyPanelID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyPanelID query:(NSString *) query;

-(id<IPanelData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IPanelData>) FindByPanelID:(NSNumber *) fieldValue;
-(id<IPanelData>) FindByThemeTemplateID:(NSNumber *) fieldValue;
-(id<IPanelData>) FindByName:(NSString *) fieldValue; 
-(id<IPanelData>) FindByDescription:(NSString *) fieldValue; 
-(id<IPanelData>) FindByPanelType:(NSNumber *) fieldValue;
-(id<IPanelData>) FindBySearchTag:(NSString *) fieldValue; 
-(id<IPanelData>) FindByRemark:(NSString *) fieldValue; 
-(id<IPanelData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<IPanelData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<IPanelData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(id<IPanelData>) FindByUserID:(NSNumber *) fieldValue;
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IPanelData>) FindObject :(NSNumber *) keyPanelID ;
        
-(id<IPanelData>) Find:(DataHandler *) dataHandler;
        
-(id<IPanelData>) FindAllObjects;

-(id<IPanelData>) FindAllObjects:(NSString *) orderByField;

-(id<IPanelData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IPanelData>) CreatePanel:(id<IDataReader>) reader;
		
-(id<IPanelData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IPanelData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end