// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PanellistProfileBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in PanellistProfile.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IPanellistProfileData.h"



#import "ICountryData.h";
#import "CountryFactory.h";

//package OnePoint.POM.Model 
    
	

    
@interface  PanellistProfileBase : DataObject<DataObject, IPanellistProfileData>
{
@private NSNumber *PanellistID;
        
@private NSString *Title;
        
@private NSString *FirstName;
        
@private NSString *LastName;
        
@private NSString *UserName;
        
@private NSString *Email;
        
@private NSString *MobileNumber;
        
@private NSString *Password;
        
@private NSString *PasswordEncrypted;
        
@private NSDate *PasswordLastUpdated;
        
@private NSDate *DOB;
        
@private NSString *Website;
        
@private NSString *Address1;
        
@private NSString *Address2;
        
@private NSString *PostalCode;
        
@private NSString *GeoLocation;
        
@private NSString *MediaID;
        
@private NSNumber *CountryCode;
        
@private NSNumber *TermsCondition;
        
	@private BOOL isTermsConditionSpecified;
@private NSNumber *Status;
        
@private NSNumber *IsDeleted;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private NSString *SearchTag;
        
@private NSString *Remark;
        
@private NSNumber *Gender;
        
	@private BOOL isGenderSpecified;
@private NSNumber *MaritalStatus;
        
	@private BOOL isMaritalStatusSpecified;
@private id<ICountryData> relCountry; 
}


	  

	@property(nonatomic,retain) NSNumber *PanellistID;

	
	@property(readwrite,strong) NSString *Title;

	
	@property(readwrite,strong) NSString *FirstName;

	
	@property(readwrite,strong) NSString *LastName;

	
	@property(readwrite,strong) NSString *UserName;

	
	@property(readwrite,strong) NSString *Email;

	
	@property(readwrite,strong) NSString *MobileNumber;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *Password;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *PasswordEncrypted;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSDate *PasswordLastUpdated;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSDate *DOB;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *Website;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *Address1;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *Address2;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *PostalCode;

	
	@property(readwrite,strong) NSString *GeoLocation;

	
	@property(readwrite,strong) NSString *MediaID;

	/// <summary>
/// Gets or sets the Country code
/// </summary>

	@property(nonatomic,retain) NSNumber *CountryCode;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *TermsCondition;

		///<summary>Determines whether TermsCondition currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isTermsConditionSpecified;
	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *Status;

	
	@property(nonatomic,retain) NSNumber *IsDeleted;

	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *SearchTag;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *Remark;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *Gender;

		///<summary>Determines whether Gender currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isGenderSpecified;
	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *MaritalStatus;

		///<summary>Determines whether MaritalStatus currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isMaritalStatusSpecified;
	@property(readwrite,strong) id<ICountryData> RelCountry; 
@end
         

    

    