// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SampleQueryCondition.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "ISampleQueryConditionData.h"
#import "ISampleQueryConditionFactoryBase.h"

//package OnePoint.POM.Model; 
  

/// <summary>
/// Creates and finds SampleQueryCondition objects
/// </summary>



@interface  SampleQueryConditionFactoryBase : DataObjectFactory<ISampleQueryConditionData,ISampleQueryConditionFactoryBase>
{
}

+(NSString*)  FIELD_NAME_SAMPLEQUERYCONDITIONID;
+(NSString*)  FIELD_NAME_NAME;
+(NSString*)  FIELD_NAME_DESCRIPTION;
+(NSString*)  FIELD_NAME_OPERATOR;
+(NSString*)  FIELD_NAME_SQLOPERATOR;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*)  FIELD_NAME_LASTUPDATEDDATE;
+(NSString*) PARAMETER_NAME_SAMPLEQUERYCONDITIONID;
+(NSString*) PARAMETER_NAME_NAME;
+(NSString*) PARAMETER_NAME_DESCRIPTION;
+(NSString*) PARAMETER_NAME_OPERATOR;
+(NSString*) PARAMETER_NAME_SQLOPERATOR;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_LASTUPDATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keySampleQueryConditionID ;
//-(BOOL) DeleteByPk:(NSNumber *) keySampleQueryConditionID;
// Define input parameters once only so they can be reused by other methods
-(void) AddSampleQueryConditionIDParameter:(DataHandler *) dataHandler valSampleQueryConditionID:(NSNumber *) valSampleQueryConditionID;	

-(void) AddNameParameter:(DataHandler *) dataHandler valName:(NSString *) valName;	

-(void) AddDescriptionParameter:(DataHandler *) dataHandler valDescription:(NSString *) valDescription;	

-(void) AddOperatorParameter:(DataHandler *) dataHandler valOperator:(NSString *) valOperator;	

-(void) AddSqlOperatorParameter:(DataHandler *) dataHandler valSqlOperator:(NSString *) valSqlOperator;	

-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(void) AddLastUpdatedDateParameter:(DataHandler *) dataHandler valLastUpdatedDate: (NSDate *) valLastUpdatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keySampleQueryConditionID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keySampleQueryConditionID query:(NSString *) query;

-(id<ISampleQueryConditionData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<ISampleQueryConditionData>) FindBySampleQueryConditionID:(NSNumber *) fieldValue;
-(id<ISampleQueryConditionData>) FindByName:(NSString *) fieldValue; 
-(id<ISampleQueryConditionData>) FindByDescription:(NSString *) fieldValue; 
-(id<ISampleQueryConditionData>) FindByOperator:(NSString *) fieldValue; 
-(id<ISampleQueryConditionData>) FindBySqlOperator:(NSString *) fieldValue; 
-(id<ISampleQueryConditionData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<ISampleQueryConditionData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(id<ISampleQueryConditionData>) FindByLastUpdatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<ISampleQueryConditionData>) FindObject :(NSNumber *) keySampleQueryConditionID ;
        
-(id<ISampleQueryConditionData>) Find:(DataHandler *) dataHandler;
        
-(id<ISampleQueryConditionData>) FindAllObjects;

-(id<ISampleQueryConditionData>) FindAllObjects:(NSString *) orderByField;

-(id<ISampleQueryConditionData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<ISampleQueryConditionData>) CreateSampleQueryCondition:(id<IDataReader>) reader;
		
-(id<ISampleQueryConditionData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<ISampleQueryConditionData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end