// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SampleQueryElementBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in SampleQueryElement.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "ISampleQueryElementData.h"



#import "ISampleData.h";
#import "SampleFactory.h";

//package OnePoint.POM.Model 
    
	

    
@interface  SampleQueryElementBase : DataObject<DataObject, ISampleQueryElementData>
{
@private NSNumber *SampleQueryElementID;
        
@private NSString *AndOr;
        
@private NSString *FieldName;
        
@private NSNumber *ConditionID;
        
@private NSString *FieldValue;
        
@private NSNumber *SampleID;
        
@private NSNumber *IsBasic;
        
@private NSNumber *Type;
        
@private NSNumber *VariableID;
        
	@private BOOL isVariableIDSpecified;
@private NSNumber *PanelID;
        
@private NSNumber *IsDeleted;
        
@private NSNumber *InUse;
        
	@private BOOL isInUseSpecified;
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private NSNumber *QuotaExpressionID;
        
	@private BOOL isQuotaExpressionIDSpecified;
@private id<ISampleData> relSample; 
}


	  

	@property(nonatomic,retain) NSNumber *SampleQueryElementID;

	
	@property(readwrite,strong) NSString *AndOr;

	
	@property(readwrite,strong) NSString *FieldName;

	
	@property(nonatomic,retain) NSNumber *ConditionID;

	
	@property(readwrite,strong) NSString *FieldValue;

	
	@property(nonatomic,retain) NSNumber *SampleID;

	
	@property(nonatomic,retain) NSNumber *IsBasic;

	
	@property(nonatomic,retain) NSNumber *Type;

	
	@property(nonatomic,retain) NSNumber *VariableID;

		///<summary>Determines whether VariableID currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isVariableIDSpecified;
	
	@property(nonatomic,retain) NSNumber *PanelID;

	
	@property(nonatomic,retain) NSNumber *IsDeleted;

	
	@property(nonatomic,retain) NSNumber *InUse;

		///<summary>Determines whether InUse currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isInUseSpecified;
	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	
	@property(nonatomic,retain) NSNumber *QuotaExpressionID;

		///<summary>Determines whether QuotaExpressionID currently is set to NULL. Used in XML Serialisation.</summary>      
	@property(nonatomic,assign) BOOL isQuotaExpressionIDSpecified;
	@property(readwrite,strong) id<ISampleData> RelSample; 
@end
         

    

    