//------------------------------------------------------------------------
// Generated on 10/12/2014 09:22:40 for Sachin\Sachin
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------
#import <Foundation/Foundation.h>
#import "SampleQueryConditionFactoryBase.h"
#import "SampleQueryCondition.h"
#import "ISampleQueryConditionData.h"
#import <OnePointFramework/IDisposable.h>
//package OnePoint.POM.Model 

@interface SampleQueryConditionFactory : SampleQueryConditionFactoryBase<IDisposable> {
}

@end

