// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ThemeTemplateBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in ThemeTemplate.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IThemeTemplateData.h"




//package OnePoint.POM.Model 
    


    
@interface  ThemeTemplateBase : DataObject<DataObject, IThemeTemplateData>
{
@private NSNumber *ThemeTemplateID;
        
@private NSString *Name;
        
@private NSString *Description;
        
@private NSNumber *IsDeleted;
        
@private NSDate *CreatedDate;
        
@private NSDate *LastUpdatedDate;
        
@private NSNumber *UserID;
        
}


	  

	@property(nonatomic,retain) NSNumber *ThemeTemplateID;

	/// <summary>
/// Gets or sets the Should be unique
/// </summary>

	@property(readwrite,strong) NSString *Name;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *Description;

	
	@property(nonatomic,retain) NSNumber *IsDeleted;

	
	@property(readwrite,strong) NSDate *CreatedDate;

	
	@property(readwrite,strong) NSDate *LastUpdatedDate;

	
	@property(nonatomic,retain) NSNumber *UserID;

	@end
         

    

    