// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ThemeElementTypeBase.java" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in ThemeElementType.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObject.h>
#import "IThemeElementTypeData.h"




//package OnePoint.POM.Model 
    


    
@interface  ThemeElementTypeBase : DataObject<DataObject, IThemeElementTypeData>
{
@private NSNumber *ThemeElementTypeID;
        
@private NSNumber *Name;
        
@private NSString *Description;
        
@private NSNumber *IsDeleted;
        
@private NSDate *CreatedDate;
        
}


	  
/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *ThemeElementTypeID;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *Name;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSString *Description;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(nonatomic,retain) NSNumber *IsDeleted;

	/// <summary>
/// Gets or sets the 
/// </summary>

	@property(readwrite,strong) NSDate *CreatedDate;

	@end
         

    

    