// --------------------------------------------------------------------------------------------------------------------
// <copyright file="model.cs" company="OnePoint Global">
//   Copyright (c) 2012 OnePoint Global Ltd. All rights reserved.
// </copyright>
// <summary>
//   This file was autogenerated and you should not edit it. It will be 
//   regenerated whenever the schema changes.
//   All changes should be made in ThemeElementType.cs and the mode.xml. 
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#import <Foundation/Foundation.h>
#import <OnePointFramework/DataObjectFactory.h>
#import "IThemeElementTypeData.h"
#import "IThemeElementTypeFactoryBase.h"

//package OnePoint.POM.Model; 
  

/// <summary>
/// Creates and finds ThemeElementType objects
/// </summary>



@interface  ThemeElementTypeFactoryBase : DataObjectFactory<IThemeElementTypeData,IThemeElementTypeFactoryBase>
{
}

+(NSString*)  FIELD_NAME_THEMEELEMENTTYPEID;
+(NSString*)  FIELD_NAME_NAME;
+(NSString*)  FIELD_NAME_DESCRIPTION;
+(NSString*)  FIELD_NAME_ISDELETED;
+(NSString*)  FIELD_NAME_CREATEDDATE;
+(NSString*) PARAMETER_NAME_THEMEELEMENTTYPEID;
+(NSString*) PARAMETER_NAME_NAME;
+(NSString*) PARAMETER_NAME_DESCRIPTION;
+(NSString*) PARAMETER_NAME_ISDELETED;
+(NSString*) PARAMETER_NAME_CREATEDDATE;

/// <summary>
/// The Microsoft SQL statement to join one table to another and perform it.
/// </summary>
-(BOOL) DeleteByPk :(NSNumber *) keyThemeElementTypeID ;
//-(BOOL) DeleteByPk:(NSNumber *) keyThemeElementTypeID;
// Define input parameters once only so they can be reused by other methods
-(void) AddThemeElementTypeIDParameter:(DataHandler *) dataHandler valThemeElementTypeID:(NSNumber *) valThemeElementTypeID;	

-(void) AddNameParameter:(DataHandler *) dataHandler valName:(NSNumber *) valName;	

-(void) AddDescriptionParameter:(DataHandler *) dataHandler valDescription:(NSString *) valDescription;	

-(void) AddIsDeletedParameter:(DataHandler *) dataHandler valIsDeleted:(NSNumber *) valIsDeleted;	

-(void) AddCreatedDateParameter:(DataHandler *) dataHandler valCreatedDate: (NSDate *) valCreatedDate;	

-(BOOL) ProcessPkStatement :(NSNumber *) keyThemeElementTypeID   query:(NSString *) query;
//-(BOOL) ProcessPkStatement:(NSNumber *) keyThemeElementTypeID query:(NSString *) query;

-(id<IThemeElementTypeData>) Find:(NSString *) attributeName attributeValue:(id) attributeValue;

-(id<IThemeElementTypeData>) FindByThemeElementTypeID:(NSNumber *) fieldValue;
-(id<IThemeElementTypeData>) FindByName:(NSNumber *) fieldValue;
-(id<IThemeElementTypeData>) FindByDescription:(NSString *) fieldValue; 
-(id<IThemeElementTypeData>) FindByIsDeleted:(NSNumber *) fieldValue;
-(id<IThemeElementTypeData>) FindByCreatedDate:(NSDate *) fieldValue;  
-(void) AppendSqlParameters:(DataHandler *) dataHandler dataObject:(DataObject *)dataObject mode:(DataMode *) mode;      
-(id<IThemeElementTypeData>) FindObject :(NSNumber *) keyThemeElementTypeID ;
        
-(id<IThemeElementTypeData>) Find:(DataHandler *) dataHandler;
        
-(id<IThemeElementTypeData>) FindAllObjects;

-(id<IThemeElementTypeData>) FindAllObjects:(NSString *) orderByField;

-(id<IThemeElementTypeData>) FindAllObjects:(NSString *) orderByField resultLimit:(int)resultLimit;	

-(id<IThemeElementTypeData>) CreateThemeElementType:(id<IDataReader>) reader;
		
-(id<IThemeElementTypeData>) createObjectFromDataReader:(id<IDataReader>) reader withPopulate:(BOOL)populateRelatedObject;

-(id<IThemeElementTypeData>) Build:(DataHandler *) currentDataHandler closeConnection:(BOOL)closeConnection;
       
@end